### ISSUE TITLE
リーダブルコード：グループで共有したリーダブルなコード

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#1]
参加者がグループ内で共有したリーダブルなコードのうち、2つ選んでここに書き込んでください。

共有したリーダブルなコードには次の情報を含めてください。
- 名前（またはタイトルあるいは一言説明）
- 実際のコード（またはURL）
- どうしてリーダブルだと考えたかの説明
- 見つけた経緯（またはきっかけ）

例:
### 名前

自己記述的定数名
### 実際のコード

https://github.com/doraemon13x/doraemon13x-sezemi-2014-readable-code-2/blob/master/mission3.c#L9

``` c
exit(EXIT_FAILURE); /* エラーの場合は異常終了する */
```
### どうしてリーダブルだと考えたかの説明

コマンドの終了ステータスは、正常終了するときは`0`、異常終了するときは`0`以外の値を返すのが通例です。そのため、このコードは次のようにしても通例通りの動きになります。

``` c
exit(1);
```

ただ、動くのは動きますが、`EXIT_FAILURE`という名前を使っている方が「失敗して終了するんだな」というのがわかりやすいのでリーダブルだと考えました。

なお、`EXIT_SUCCESS`というのもあるので、同様の理由で正常終了するときはそれを使うのがよいと思います。
### 見つけた経緯

ちゃんとエラー処理をしていて立派だなぁと思って読み進めたら異常終了することがわかりやすいコードだと気づきました。

**Comment by yudmo** [comment]
# 開発言語グループ:C言語

### 実際のコード

https://github.com/HirotakaTakayama/HirotakaTakayama-sezemi-2015-readable-code

```
    if( argc != ARG_NUM + 1 ) {
        printf("指定する引数の数が違います.\n");
        exit( EXIT_FAILURE );
    }
```

### リーダブルだと思った理由

括弧の前後にスペースが入っていたりいなかったりするが、これはダブルクォーテーションは空白部分が大きくスペースに近い見た目をしているのでカッコと ダブルクォーテーションが連続するときはあえてスペースを入れていないのだと思う。

### この書き方の一言説明

見た目を考慮した空白のルール

---

### 実際のコード

```
void spec5(char* recipeFileName, int argRecipeId); /* 実際の処理を行う関数*/

int main(int argc, char* argv[]){
    int argRecipeId;
　
    if (argc != 2) { /* 引数エラーチェック */
        printf("Usage Error: recipe.exe [File Name] [Recipe ID]");
        exit(EXIT_FAILURE);
    }

    argRecipeId = atoi(argv[2]);

    spec5(argv[1], argRecipeId);
}
```

### リーダブルだと思った理由

main文に実際の処理を書かないで関数化している。
理由：関数が増えた時に読みやすくなるから。

### この書き方の一言説明

使う関数をファイルの冒頭に記述
理由：どんな関数があるか把握してからmain文が読めるから。

**Comment by riekot** [comment]
# 開発言語グループ：C言語(前列右から2番目のグループ)

---

## 単語の境目の文字を大文字にしてリーダブル
1. https://github.com/riekot/korinbojoke-sezemi-2015-readable-code/blob/master/readable-2015/recipe.c#L5

``` c
void printRecipe(char *);   //レシピを表示するための関数
```

2．命名の時に単語の境目に大文字を挟むことで読みやすくなっている．

3．単語の境目が大文字になると読みやすい

---

## 機能ごとにブロック分けでリーダブル

1．https://github.com/riekot/korinbojoke-sezemi-2015-readable-code/blob/master/readable-2015/recipe.c#L8

``` c
int main(void){
    FILE *file;
    char recipe[MAX_STRING];

    /*file open*/
    file = fopen("recipe.txt", "r");
    if (file == NULL){
        perror("file open error");
    }

    /*fgets*/
    if (fgets(recipe, MAX_STRING, file) < 0){
        perror("file write error");
    }

    /*printRecipe*/
    printRecipe(recipe);
    return 0;
}
```

2．コードが，機能ごとにブロック分けされているので，何をする部分か分かりやすい

3．機能ごとにブロック分けでリーダブル

**Comment by akkiihs** [comment]
# 開発言語グループ:PHP

## 見つけたリーダブルコード.01

### 実際のコード

https://github.com/tsss-a/-sivukai--sezemi-2015-readable-code/blob/master/method/json_loader.php

### どうしてリーダブルだと思っているかの説明

読み込み用の関数群をまとめたファイルがあることで汎用性をもたせていること。
以下のコードでは、単に"UTF-8に変換"と書くのではなく、"文字化けするかもしれないので"という変換する理由が記述されていて、**なぜ**その処理を実行する必要があるのかが明示されていた

``` php
// 文字化けするかもしれないのでUTF-8に変換
$json = mb_convert_encoding($json, 'UTF8','ASCII,JIS,UTF-8,EUC-JP,SJIS-WIN');
```

### この書き方の一言説明

理由記述コメントアウト

---

## 見つけたリーダブルコード.02

### 実際のコード

https://github.com/tsss-a/-sivukai--sezemi-2015-readable-code/blob/master/method/json_loader.php

### どうしてリーダブルだと思っているかの説明

今後、このファイルにいくつもの関数が記述されることを予想すると、関数自体に対するコメントと関数内のコメントを区別するために、関数に対するコメントは目立つようにすると関数を追うことが容易になると思う。

``` php
/**
 * Jsonファイルをデコードする関数
 *
 * @param String $filename
 * @return array
 */
function json_load($filename){
```

### この書き方の一言説明

関数に関するコメントは目立つように

**Comment by yokoto** [comment]
## 開発言語グループ:Ruby

### 実際のコード01

https://github.com/yokoto/yokoto-sezemi-2015-readable-code/issues/2#issuecomment-109540414

``` rb
  def recipe_id
    ARGV[1].to_i - 1 if valid_recipe_id?
  end
```

### リーダブルだと思った理由

例外処理などが簡潔に一行で書かれていたので、わかりやすかった

### この書き方の一言説明

綺麗な条件分岐

---

### 実際のコード02

https://github.com/yokoto/yokoto-sezemi-2015-readable-code/issues/2#issuecomment-109539812

``` rb
  def recipe_file_path
    @recipe_file_path ||= (ARGV[0] || DEFALUT_FILE_PATH)
  end
```

### どうしてリーダブルだと思っているかの説明

[全体的](https://github.com/ganmacs/ganmacs-sezemi-2015-readable-code/blob/master/lib/recipe.rb)にメソッド名が綺麗でとても見やすかった
特にload_recipe_fileが何を引っ張ってきているかわかりやすかった。

### この書き方の一言説明

わかりやすいメソッド命名

**Comment by HSKKOU** [comment]
# 開発言語グループSwift

---

## この書き方の一言説明

目的ごとに変数定義

## 実際のコード

``` swift
//NSBundeに入れる
        let path : String = NSBundle.mainBundle().pathForResource("recipe-data", ofType: "txt")!
        let fileHandle : NSFileHandle = NSFileHandle(forReadingAtPath: path)!
        let data : NSData = fileHandle.readDataToEndOfFile()
```

## どうしてリーダブルだと考えたかの説明

目的ごとに変数定義（名前付け）していて段階を踏んで機能自体を理解しやすい

## 見つけた経緯

コードの流れを読むとき

---

## この書き方の一言説明

ファイルパスの「定数」定義

## 実際のコード

``` swift
let filePath = NSBundle.mainBundle().pathForResource("recipe-data", ofType: "csv")
```

## どうしてリーダブルだと考えたかの説明

変数名からファイルを読み込むのに必要なパスを取得したことがわかった。
ファイルパスはたしかに変わらないものであるということがわかる。

## 見つけた経緯

コードを読んだ時（すっと意味が伝わってきた）

**Comment by Vetteru** [comment]
# 開発言語グループ: C++

## 実際のコード

https://github.com/Vetteru/Vetteru-sezemi-2015-readable-code/blob/master/recipe_managing_system.cpp

```
const int WILD_CARD = -1;
void display_recipe_in_file_with_URL(char* filename, int index = WILD_CARD){
  fstream file(filename);
  string recipe_name, recipe_URL;
  int idx = 0;
  while(file >> recipe_name >> recipe_URL){
    idx++;
    if(idx == index || index == WILD_CARD) cout << idx << ": " << recipe_name << " " << recipe_URL << endl;
  }
}
```

## 理由

使う場面に応じて変数名を変えているから

## 見つけた経緯

コードを読み下していて見つけた

**Comment by yu1ro** [comment]
# Java

### 実際のコード

``` Recipe.java
        catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("使い方 - java Recipe <ファイル名>");
        }
```

### 見つけた経緯と、どうしてリーダブルだと考えたかの説明

初めて実行しようとしたときにこのメッセージのお陰でわかったから

### この書き方の一言説明

わかりやすいエラーコード

**Comment by Vetteru** [comment]
# 開発言語グループ: C++

## 実際のコード

https://github.com/Vetteru/Vetteru-sezemi-2015-readable-code/blob/master/README.md

## 理由

実行時にエラーが起こった時の対処法まで書いてあった

## 見つけた経緯

実際にエラーが発生した

**Comment by sesta** [comment]
# 開発言語グループ : JavaScript + Node.js

## 見つけたリーダブルコード 1

### 名前

変数スキーム統一

### 実際のコード

https://github.com/45deg/qzwpq-sezemi-2015-readable-code/blob/master/app.js#L39

``` javascript
var printIdAndName = function(recipe) {
    var recipeName = recipe.name;
    var recipeId = getRecipeId(recipeName);
    console.log(recipeId + ': ' + recipeName);
};
```

### どうしてリーダブルだと思っているかの説明

変数名がrecipieXXXで統一しててよいと感じた。このことによって単にname, idと「何」の情報だけではなく「どのような」という情報が得られる。

### 見つけた経緯

関数の中身を調べているとき
意味( これは何のNameなのか )がすぐわかった

---

## 見つけたリーダブルコード 2

### 名前

なんちゃってmain関数

### 実際のコード

https://github.com/qzwpq/45deg-sezemi-2015-readable-code/blob/db23e9bf24507b80a918510c276bebc4d145f692/app.js#L7

``` javascript
// モジュール読み込み
var fs = require('fs');
var rl = require('readline');

(function main(){
```

### どうしてリーダブルだと思っているかの説明

処理全体を(function main(){ ... }()でくくっている モジュールの読み込みと分かれていて読みやすい 

### 見つけた経緯

上から読んでいて
何を実行しているか分かりやすかったため

**Comment by k5trismegistus** [comment]
# Python うしろ軍団

# ソースコードの問題点を記載してある点

## コード

``` python
# TODO: idが範囲外のときにErrorなどを出す refer to memo.md
# TODO: id が正しくないものを出力してしまうのを直す        
```

## どうしてリーダブルなのか

ソースコードの問題点を記載しており、続く人が何をすればよいか明確にわかる

# ライブラリに処理を移譲

## コード

``` python
# -*- coding: utf-8 -*-
import pandas as pd
import sys

user_name = str(sys.argv[1])
recipe_data = pd.read_csv('./recipe-data-utf.csv')

print recipe_data[recipe_data.Users==user_name]
```

## どうしてリーダブルなのか

課題8時点でこの短さであり、pandasライブラリを知っていれば読みやすい。
この程度の短さであれば、コメント等がないほうが簡潔で読みやすい。

**Comment by ayemos** [comment]
# Java

## 実際のコード

https://github.com/ayemos/ayemos-sezemi-2015-readable-code/blob/master/src/recipe/RecipeLoader.java#L52

## どうしてリーダブルだと考えたかの説明

recipeModels.add(new RecipeModel(child.getNodeValue()));
と一行で書くことも出来ますが、以下の理由から二行に分けたほうがリーダブルです。
- 行がわかれていることにより、スタックトレースの行情報を活かしやすい and デバッガの操作(主にステップインとステップオーバー)が有効に使える
- (今回は見た目から明らかだが、)new RecipeModelが何を返すか、recipeModel.add()にどんな引数を与えているかが(一行の場合に比べて)明確

## 一言

処理の分離

**Comment by issei1992** [comment]
C++
[実際のコード]
https://github.com/NariyoshiChida/NariyoshiChida-sezemi-2015-readable-code/blob/master/recipe.cc#L12
 https://github.com/NariyoshiChida/issei-sezemi-2015-readable-code/blob/master/assignment1/assignment1/main.cpp#L15 https://github.com/NariyoshiChida/issei-sezemi-2015-readable-code/blob/master/assignment1/assignment1/main.cpp#L22 https://github.com/NariyoshiChida/issei-sezemi-2015-readable-code/blob/master/assignment1/assignment1/main.cpp#L92 https://github.com/NariyoshiChida/issei-sezemi-2015-readable-code/blob/master/assignment1/assignment1/main.cpp#L95

[どうしてリーダブルだと考えたのか]
変数の間にスペースを置くことで式の意味を強調しているし、見やすくなる。
関数名、変数名の命名規則が明確で理解しやすい

**Comment by takuti** [comment]
### Python :sushi: 前

#### 実際のコード

https://github.com/takuti/kabayan55-sezemi-2015-readable-code/blob/3d2f3913fd6b8ac9e6efcb6dd65f7590e342e479/recipe.py

#### どうしてリーダブルだと思っているのかの説明

共通部分は括りだして、同じ処理をしている関数内の見通しをよくした。
- formattingして出力するのは下の2つの関数に共通する処理
- 今後URLとか扱うものが増えた時に嬉しくなってくる

``` python
def printRecipe(recipe_id, recipe_name):
  print str(recipe_id)+': '+ recipe_name

def searchRecipeById(recipe_id):
  searched_recipe_name = three_recipes[recipe_id]
  printRecipe(recipe_id, searched_recipe_name)

def printAllRecipes():
  for recipe_id, recipe_name in three_recipes.items():
    printRecipe(recipe_id, recipe_name)
```

#### 一言説明

共通処理のくくりだし

**Comment by takuti** [comment]
#### 実際のコード

https://github.com/takuti/kabayan55-sezemi-2015-readable-code/blob/3d2f3913fd6b8ac9e6efcb6dd65f7590e342e479/recipe.py

#### どうしてリーダブルだと思っているのかの説明

共通部分は括りだして、同じ処理をしている関数内の見通しをよくした。

```python
def printRecipe(recipe_id, recipe_name):
  print str(recipe_id)+': '+ recipe_name

def searchRecipeById(recipe_id):
  searched_recipe_name = three_recipes[recipe_id]
  printRecipe(recipe_id, searched_recipe_name)

def printAllRecipes():
  for recipe_id, recipe_name in three_recipes.items():
    printRecipe(recipe_id, recipe_name)
```

#### 一言説明

共通処理のくくりだし

**Comment by ghost** [comment]
# Python

### 実際のコード

https://github.com/ch1ca0/dorapon2000-sezemi-2015-readable-code/blob/master/recipe.py#L8

### 処理内容

recipe-data.txt(recipes)の各行に対して繰り返し処理を行う

### コード

``` Python
def print_recipe(recipes, recipe_query_id):
    for recipe in recipes:
```

### 説明
- recipes(集合)からひとつを取り出しているので、recipe(単数)とすることでリーダブル

### 一言説明

英文法的変数名
