### ISSUE TITLE
OSS Hack 4 Beginners：対象OSS案のリスト

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#10]
対象OSSに使えそうなOSSを集める。

対象OSSに使えそうなOSSの条件は次の通り。
- (1)必須：自分が開発に参加しているOSS
  - 「pull requestやissueは自分が見るからビビらなくて大丈夫だよ、失敗しても大丈夫だよ」と参加者を安心させることができるから。
  - イベント時間内に「開発者とのやりとり」を経験できるから。
- (2)あるとよい：難易度が低い
  - イベント時間内で「動かすこと」に到達しやすくなりそうだから。
- (3)あるとよい：日本語を使ってもよい
  - 実際は英語を使うことになるが今回は日本語でも使ってよいことにしたい。そうすることで一連のプロセスを体験して不安を解消することにつながりそうだからである。

現在の対象OSSリスト：
- Java: [Mixer2](http://mixer2.org/site/ja/)
- Ruby（Rails経験者）: [jpmobile](http://jpmobile-rails.org/)
- Ruby（Rails未経験者）: [rws-ruby-sdk](https://github.com/rakuten-ws/rws-ruby-sdk)
- C: [Groonga](http://groonga.org/ja/)
- Python: [Pikzie](http://pikzie.sourceforge.net/index.html.ja)
- Node.js: [Sharetary](https://github.com/clear-code/sharetary)
- PHP: 募集中

**Comment by kou** [comment]
例：
- OSS名：[Rabbit](http://rabbit-shocker.org/)
- 言語：Ruby
- 「開発参加の敷居が低いOSS」で満たしている条件： 1, 3
  - 備考：GNU/Linux環境なら2も満たすけどWindowsやOS Xでは環境構築の敷居が高そう

**Comment by okkez** [comment]
- OSS名: [るりま](https://github.com/rurema/doctree)
- 言語: Ruby と日本語
- 満たしている条件: (1),(2),(3)

サンプルコードの修正や提供でコードを書くこともできるし、Ruby2.2対応など比較的とっつきやすそうなタスクもあります。
