### ISSUE TITLE
リーダブルコード筑波：Cグループのリーダブルコード集め場所

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#12]
次のことを書く場所です。
- 自分で書いていて工夫したところ（リーダブルに書いたと思っているところ）
- 他の人のコードを読んでリーダブルだと思ったところ

↑について次のテンプレートを埋めてコメントに書いてください。1つの↑につき1つのコメントにしてください。つまり、1人で4個の↑を書くときは、1つのコメントに4個書くのではなく、4つコメントにわけて書きます。

`````` text
### 実際のコード

（ここに実際のコードを張る）

ヒント：

    ```sh
    echo "Hello"
    ```

↑というように

    ```言語名
    （コード）
    ```

というように囲むとコードが色付きになる。

### どうしてリーダブルだと考えたかの説明

（ここに↑のコードがどうしてリーダブルだと考えたか説明する）

### 見つけたきっかけ

（他の人のコードから見つけた時だけ、ここに見つけたきっかけを書く。）
``````

例（他の人のコードから見つけた場合）：

``````
### 実際のコード

```c
exit(EXIT_FAILURE); /* エラーの場合は異常終了する */
```

### どうしてリーダブルだと考えたかの説明

コマンドの終了ステータスは、正常終了するときは`0`、異常終了するときは`0`以外の値を返すのが通例です。そのため、このコードは次のようにしても通例通りの動きになります。

```c
exit(1);
```

ただ、動くのは動きますが、`EXIT_FAILURE`という名前を使っている方が「失敗して終了するんだな」というのがわかりやすいのでリーダブルだと考えました。

なお、`EXIT_SUCCESS`というのもあるので、同様の理由で正常終了するときはそれを使うのがよいと思います。

### 見つけた経緯

ちゃんとエラー処理をしていて立派だなぁと思って読み進めたら異常終了することがわかりやすいコードだと気づきました。
``````

**Comment by ikegawa-koshi** [comment]
### 実際のコード

clang readable-code.c -o readable-code.o
./readable-code.o

### どうしてリーダブルだと考えたかの説明

C言語の場合はコンパイルをしなくてはならない。
コンパイルした後にできる実行ファイルの名前を指定する。
そうすることで、リーダブルになる

**Comment by ghost** [comment]
### 実際のコード

``` c
#define RECIPE_LEN 100 //レシピタイトルの長さの最大文字数
　　　　　　　...
  char recipe_title[RECIPE_LEN];
　　　　　　　...
  fgets( recipe_title, RECIPE_LEN, fp )
```

### どうしてリーダブルだと考えたかの説明

例えば配列の大きさをrecipe_title[100]の様に書いても問題なく動作しますが、
100が何かがぱっと見わからないので、レシピタイトルの最大値文字数という意味でRECIPE_LENという名前をつけた

**Comment by ikegawa-koshi** [comment]
### 実際のコード

FILE *p_recipe_file;

### どうしてリーダブルだと考えたかの説明

FILEポインタの変数名に p_ をつけることで、ポインタだとすぐ分かる。

**Comment by ikegawa-koshi** [comment]
### 実際のコード

for(int id=0; (fscanf(p_recipe_file, "%s",s) != EOF); id++)
{
    printf("%03d: %s\n",id, s);
}

### どうしてリーダブルだと考えたかの説明

ループの名前をidにすることで、このループがIDを表すのだと分かる

**Comment by ghost** [comment]
### 実際のコード

``` c
char    *receipe_title = "オムライス";
```

### どうしてリーダブルだと考えたかの説明

オムライスを表示するだけだったらprintf("オムライス");で出力する事が出来るが、
それだとオムライスがレシピのタイトルなのか、好きな料理名なのかがわからない。
そこで変数名としてrecipe_titleという名前をつけてそのオムライスが何なのかわかる様にした。

**Comment by ghost** [comment]
### 実際のコード

``` c
if( fp == NULL )
```

### どうしてリーダブルだと考えたかの説明

if文の条件式の括弧の部分の最初と最後に空白をつける事によって条件文が見やすくなると考えた

**Comment by ghost** [comment]
### 実際のコード

``` c
printf("%03d: %s\n",id, buffer);
```

### どうしてリーダブルだと考えたかの説明

idを%03dのように表示することによって、idが増えた時に見やすい

### 見つけた経緯

自分がやってなかった

**Comment by ghost** [comment]
### 実際のコード

``` c
int main(int argc, char *argv[])
{
    all_recipe_output();

    return 0;
}
```

### どうしてリーダブルだと考えたかの説明

処理する部分をmainに書くのではなく、関数に分けて書く事で見栄えが良い。

### 見つけた経緯

自分が関数を使っていなかったため

**Comment by ikegawa-koshi** [comment]
### 実際のコード

#define RECIPE_LEN 100 //レシピタイトルの長さの最大文字数

### どうしてリーダブルだと考えたかの説明

buffer sizeの指定をdefineですることで、今後の変更がしやすい
bufferの使い道が書かれていて良い

### 見つけたきっかけ

自分はbufferとしか書いていなかったから

**Comment by ghost** [comment]
### 実際のコード

コマンドラインで [$ sh make_do.sh]を実行してください。

### どうしてリーダブルだと考えたかの説明

シェルスクリプトを作ってくれた事によって実行がとてもしやすくなった。

### 見つけた経緯

次に開発する人の事を考えて手順を単純化してくれる事はとてもありがたい

**Comment by ikegawa-koshi** [comment]
###実際のコード
int id=0;

###どうしてリーダブルだと考えたのか説明
ループ名をidとすることで、idの割り振りに使うとよくわかった

###見つけた経緯
同じことをしていた

**Comment by ikegawa-koshi** [comment]
### 実際のコード

int id=0;

### どうしてリーダブルだと考えたのか説明

ループ名をidとすることで、idの割り振りに使うとよくわかった

### 見つけた経緯

同じことをしていた

**Comment by ghost** [comment]
### 実際のコード

#recipe-data.txtの編集方法#
プログラムではfscanfによってファイル内の文字列を読み込みます。
料理名はスペースもしくは改行で区切ってください。
    ex1. オムライス 親子丼 杏仁豆腐
    ex2.    オムライス
            親子丼
            杏仁豆腐

### どうしてリーダブルだと考えたかの説明

ファイルを追加する時の仕様をしっかりと書いてある為、レシピを追加する時に迷わないからリーダブル

### 見つけた経緯

しっかりと次の人の事を考えて作られていて、わかりやすいと思った為

**Comment by ikegawa-koshi** [comment]
### 実際のコード

  if( fp == NULL ){  //ファイルオープンエラー処理
    printf( "%sファイルが開けません\n", fname ); 
    return -1;
  }

### どうしてリーダブルだと考えたかの説明

エラーメッセージ
ファイルが開けなかった例外処理を予め書いていることがよくわかった

### 見つけたきっかけ

自分はファイルが読み込めなかった時はなにもしないようにしていた

**Comment by ghost** [comment]
### 実際のコード

``` c
    select_id = atoi(argv[1]);
```

### どうしてリーダブルだと考えたかの説明

ユーザが入力したidをselect_idという名前の変数に格納する事で、どのidがついたレシピを表示すれば良いかがわかると思った為

**Comment by ghost** [comment]
### 実際のコード

```
(注1) この時説明文の途中で改行しない。
(注2) 説明文は4000文字以内にしてください。
```

### どうしてリーダブルだと考えたかの説明

README.txtに注意書きを書く事で仕様以外のものは書かないようにしているところがリーダブル

**Comment by ikegawa-koshi** [comment]
### 実際のコード

```
if(argc == 1) all_output();
else for(int select_id=1; select_id<argc; select_id++)
{
    select_output( atoi(argv[select_id] ) );
}
```

### どうしてリーダブルだと考えたかの説明

こうすることで、{}の数を減らして、コードが読みやすくなりリーダブル

**Comment by ikegawa-koshi** [comment]
### 実際のコード

```
else for(int select_id=1; select_id<argc; select_id++)
{
    select_output( atoi( argv[select_id] ) );
}
```

### どうしてリーダブルだと考えたかの説明

select_idという名前をつけることで、選ばれたIDだということが分かる
