### ISSUE TITLE
 リーダブルコード筑波：C++グループのリーダブルコード集め場所

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#13]
次のことを書く場所です。
- 自分で書いていて工夫したところ（リーダブルに書いたと思っているところ）
- 他の人のコードを読んでリーダブルだと思ったところ

↑について次のテンプレートを埋めてコメントに書いてください。1つの↑につき1つのコメントにしてください。つまり、1人で4個の↑を書くときは、1つのコメントに4個書くのではなく、4つコメントにわけて書きます。

`````` text
### 実際のコード

（ここに実際のコードを張る）

ヒント：

    ```sh
    echo "Hello"
    ```

↑というように

    ```言語名
    （コード）
    ```

というように囲むとコードが色付きになる。

### どうしてリーダブルだと考えたかの説明

（ここに↑のコードがどうしてリーダブルだと考えたか説明する）

### 見つけたきっかけ

（他の人のコードから見つけた時だけ、ここに見つけたきっかけを書く。）
``````

例（他の人のコードから見つけた場合）：

``````
### 実際のコード

```c
exit(EXIT_FAILURE); /* エラーの場合は異常終了する */
```

### どうしてリーダブルだと考えたかの説明

コマンドの終了ステータスは、正常終了するときは`0`、異常終了するときは`0`以外の値を返すのが通例です。そのため、このコードは次のようにしても通例通りの動きになります。

```c
exit(1);
```

ただ、動くのは動きますが、`EXIT_FAILURE`という名前を使っている方が「失敗して終了するんだな」というのがわかりやすいのでリーダブルだと考えました。

なお、`EXIT_SUCCESS`というのもあるので、同様の理由で正常終了するときはそれを使うのがよいと思います。

### 見つけた経緯

ちゃんとエラー処理をしていて立派だなぁと思って読み進めたら異常終了することがわかりやすいコードだと気づきました。
``````

**Comment by ArGxento** [comment]
### 実際のコード

``` C++
/**
\brief デバッグ時に内容を読むために、コンソールを一時停止する
*/
void haltConsole() {
    char tmp = 0;
    std::cin >> tmp; // 結果が読めるようにコンソールを停止する
}
```

### どうしてリーダブルだと考えたかの説明

Doxygen形式で説明を書くことで、そのコードの機能をひと目で把握できるようになるので

**Comment by ArGxento** [comment]
### 実際のコード

``` C++
void outputFileToConsole(std::string const& fileName) {
    std::ifstream ifs(fileName, std::ios_base::binary); // コンソールに鸚鵡返しするためにバイナリオープンする

    // ファイルから1byteづつ読み取ってコンソールに出力
    for (auto it = std::istreambuf_iterator<char>(ifs); it != std::istreambuf_iterator<char>(); it++) {
        std::cout << *it;
    }

    // フラッシュされない可能性があるのでフラッシュする
    std::cout << std::flush;

    haltConsole();
}
```

### どうしてリーダブルだと考えたかの説明

コメントはなるべく **what** を書かず、 **why** を書くようにする
ひと目で what がわからなくなってしまうことが避けられないコードは、whatも併記する
こうすることで書き手の意図がコードに残り、読みやすいコードになると考えたので

**Comment by ArGxento** [comment]
### 実際のコード

``` C++
std::ifstream ifs(fileName, std::ios_base::binary);
```

### どうしてリーダブルだと考えたかの説明

名前空間を省略すると、多数の名前空間や入り組んだ名前空間を使用した時に読みにくいコードになるので、名前空間をなるべく省略しないことで、その名前がどの機能に属するかを明らかにすることでコードを読みやすくできるのではないかと考えました

**Comment by prpr-man** [comment]
### 実際のコード

``` c++
    using namespace std;
```

### どうしてリーダブルだと考えたかの説明

std::を書かないことで見やすいと考えた．

**Comment by prpr-man** [comment]
### 実際のコード

``` C++
string getRecipeName(string recipe_file_path){
  ifstream recipe_file(recipe_file_path);
  if(recipe_file.fail()){
    cout << "レシピファイルが見つかりません" << endl;
    exit(EXIT_FAILURE);
  }

  string recipe_name;
  recipe_file >> recipe_name;

  return recipe_name;
}
```

### どうしてリーダブルだと考えたかの説明

関数化することにより何をしているかをわかりやすくした．
変数名もrecipe_fileや，recipe_nameなど，何を格納する変数なのかを分かりやすくした．

**Comment by prpr-man** [comment]
### 実際のコード

``` C++
string recipe_file_path = argv[1];
  printRecipeNames(recipe_file_path);
```

### どうしてリーダブルだと考えたのかの説明

コマンドライン引数を変数に一度入れることで，なんのデータがコマンドライン引数から得たのかをわかりやすく表示をしてみた．

**Comment by Butanosuke** [comment]
### 実際のコード

``` c++
void input_file(vector<string> &recipe, char* file_name) {
  ifstream ifs(file_name);
  string tmp;
  while(getline(ifs, tmp)){
    recipe.push_back(tmp);
  }
}
```

### どうしてリーダブルだと考えたかの説明

ファイルから読み取って配列化して返すのを関数化したほうが見やすいと思った.

**Comment by prpr-man** [comment]
### 実際のコード

``` C++
void printRecipeNames(string recipe_file_path){
  // レシピファイルが見つからなかった時のエラー処理
  ifstream recipe_file(recipe_file_path);
  if(recipe_file.fail()){
    cout << "レシピファイルが見つかりません" << endl;
    exit(EXIT_FAILURE);
  }

  // レシピファイルから一行ずつ読み出力する
  string recipe_name;
  while(getline(recipe_file, recipe_name)){
    cout << recipe_name << endl;
  }
}
```

### どうしてリーダブルだと考えたかの説明

spec3では表示部分がmain文に書かれていたので，表示部分まで行うことにより，分かりやすくなると考えた．

**Comment by ken-3d** [comment]
### 実際のコード

```
string recipeID; // recipe ID container
string recipeName;   // single recipe container
```

### どうしてリーダブルだと考えたかの説明

2つの英単語の組み合わせと大文字で分ける変数名を採用している。
これで変数の内容をよりわかりやすくしている

**Comment by Butanosuke** [comment]
### 実際のコード

``` c++
void printRecipeNames(string recipe_file_path)
```

### どうしてリーダブルだと考えたかの説明

単語の頭文字を大文字にすることで単語の区切れ目が一目でわかる。

### 見つけたきっかけ

何をする関数なのか読んでいて気付いた。

**Comment by prpr-man** [comment]
### 実際のコード

``` c++
 input_file(recipe_data, recipe_name);
  for(int i=0; i<recipe_data.size(); i++) {
    cout << recipe_data[i] << endl;
  }
```

### どうしてリーダブルだと考えたかの説明

ファイルを読み込む処理とその内容を出力する処理がしっかり分けられていて，読みやすく，理解しやすいと感じました．

### 見つけた経緯

自分のプログラムでは，ファイルを読み込む処理と出力する処理が同じ関数になっており，すこし読みにくいなと感じていたため，このプログラムをみて読みやすいと感じたため．

**Comment by ArGxento** [comment]
### 実際のコード

``` C++
string recipeName;
```

### どうしてリーダブルだと考えたかの説明

変数名が機能を表していて把握しやすい

### 見つけたきっかけ

眺めていてひと目でわかったため

**Comment by Butanosuke** [comment]
### 実際のコード

``` sh
// レシピファイルが見つからなかった時のエラー処理
```

### どうしてリーダブルだと考えたかの説明

スラッシュから空白をあけることでコメントを読みやすくしている。

### 見つけたきっかけ

コメントを読んでいて思った。

**Comment by Butanosuke** [comment]
### 実際のコード

``` c++
if(recipe_file.fail()){
...
}
```

### どうしてリーダブルだと考えたかの説明

どんな場合にif文に入るのか一目でわかる。

### 見つけたきっかけ

自分のプログラム中でエラー処理をどうしようか考えていたため。

**Comment by ken-3d** [comment]
### 実際のコード

```
outputFileToConsole(std::string(argv[1]));
```

### どうしてリーダブルだと考えたかの説明

何を行う関数か一目で検討がつく。

### 見つけたきっかけ

出力をどこで行っているか見ていたため。

**Comment by Butanosuke** [comment]
### 実際のコード

``` c++
printRecipeNames(recipe_file_path, select_ID);
```

### どうしてリーダブルだと考えたかの説明

関数名は単語を引っ付け、変数名はアンダースコアをつけているので関数か変数か一目でわかる。

### 見つけたきっかけ

関数を使うときに思った。

**Comment by ArGxento** [comment]
### 実際のコード

``` c++
    string recipeID; // recipe ID container
    string recipeName;   // single recipe container
    string recipeDescription;   // recipe description
```

### どうしてリーダブルだと考えたかの説明

関連する変数がまとまった場所にあり、統一されたプレフィクスがつけられているので機能が把握しやすい

### 見つけたきっかけ

読んでいて目につきました

**Comment by prpr-man** [comment]
### 実際のコード

``` c++
  if(id == NOT_EXIST_ID) print_recipe_all(recipe_data);
  else                   print_recipe_by_id(recipe_data, id);
```

### どうしてリーダブルだと考えたかの説明

NOT_EXIST_IDを定義することにより，idが指定されなかった時とそうでない時の処理がわかりやすくなると考えた．

**Comment by ArGxento** [comment]
### 実際のコード

``` c++
 while(file.good()){
```

### どうしてリーダブルだと考えたかの説明

否定演算子を使っていないので、見落としにくく、可読性があがると考えました

### 見つけたきっかけ

メンターの方に指摘していただきました
