### ISSUE TITLE
リーダブルコード筑波：Javaグループのリーダブルコード集め場所

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#14]
次のことを書く場所です。
- 自分で書いていて工夫したところ（リーダブルに書いたと思っているところ）
- 他の人のコードを読んでリーダブルだと思ったところ

↑について次のテンプレートを埋めてコメントに書いてください。1つの↑につき1つのコメントにしてください。つまり、1人で4個の↑を書くときは、1つのコメントに4個書くのではなく、4つコメントにわけて書きます。

`````` text
### 実際のコード

（ここに実際のコードを張る）

ヒント：

    ```sh
    echo "Hello"
    ```

↑というように

    ```言語名
    （コード）
    ```

というように囲むとコードが色付きになる。

### どうしてリーダブルだと考えたかの説明

（ここに↑のコードがどうしてリーダブルだと考えたか説明する）

### 見つけたきっかけ

（他の人のコードから見つけた時だけ、ここに見つけたきっかけを書く。）
``````

例（他の人のコードから見つけた場合）：

``````
### 実際のコード

```c
exit(EXIT_FAILURE); /* エラーの場合は異常終了する */
```

### どうしてリーダブルだと考えたかの説明

コマンドの終了ステータスは、正常終了するときは`0`、異常終了するときは`0`以外の値を返すのが通例です。そのため、このコードは次のようにしても通例通りの動きになります。

```c
exit(1);
```

ただ、動くのは動きますが、`EXIT_FAILURE`という名前を使っている方が「失敗して終了するんだな」というのがわかりやすいのでリーダブルだと考えました。

なお、`EXIT_SUCCESS`というのもあるので、同様の理由で正常終了するときはそれを使うのがよいと思います。

### 見つけた経緯

ちゃんとエラー処理をしていて立派だなぁと思って読み進めたら異常終了することがわかりやすいコードだと気づきました。
``````

**Comment by chamstorage** [comment]
### 実際のコード

``` java
FileInputStream inputStream = new FileInputStream(filename);
BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
```

### どうしてリーダブルだと考えたかの説明

変数名に過度な略称を使っていないため、この先変数名を見た時なんのクラスなのか分かりやすいので、リーダブルだと考えた

### 見つけたきっかけ

（自分のコードなのでなし）

**Comment by tsss-j** [comment]
### 実際のコード

ヒント：

``````
```
        /*
     * ディレクトリ構造が変わったらrecipe-data.txt
     * へのfilePassを変更する必要あり
     */
    final String filePass = "C:/Users/jun/pleiades/workspace/test/recipe-data.txt";

```
``````

### どうしてリーダブルだと考えたかの説明

他の人の実行環境ではファイルのある階層が変わるので注記した点。

### 見つけた経緯

自分のコードなので無し

**Comment by chiemi627** [comment]
### 実際のコード

``` java
public class RecipeManager {
  ArrayList<Recipe> recipe;
}
...
public class Recipe {
  String title;
}
```

### どうしてリーダブルだと考えたかの説明

クラスの構成の作り方で
- RecipeMangerがRecipeを持っている
- RecipeManagerが管理しているRecipeを出力する
  という構成を用意した

### 見つけた経緯

**Comment by tsukumaru** [comment]
### 実際のコード

``` java
//ファイル入出力処理における例外処理
        try {
            //ファイル読み込み
            BufferedReader br = new BufferedReader(new FileReader(new File("recipe-title-data.txt")));

            String title = br.readLine();
            System.out.println(title);

            br.close();
        } 
```

### どうしてリーダブルだと考えたかの説明

ややこしそうなところへのコメントでの補助。
処理の塊ごとに改行を使うことで、処理を追いやすくした。

**Comment by chamstorage** [comment]
### やったこと

実行環境がEclipseのとき、srcファイルのみをプッシュした

### どうしてリーダブルだと考えたかの説明

binフォルダ以下も書き変えられているが、それは自動で書き換えられたところであり、自分が書き換えたわけではない。
それなのにbinを更新してしまうと、見た人がそこも何か変更があったのだと勘違いしてしまうので、更新しない方がリーダブルだと考えた。

### 見つけたきっかけ

（自分のコードなのでなし）

**Comment by chamstorage** [comment]
### 実際のコード

``` java
if(args.length==0){
    System.out.println("please input filename");
    return;
}
```

### どうしてリーダブルだと考えたかの説明

・ファイル名が指定されていない時、何も書かずに終了するよりも、その警告を出力したほうが良いと考えた
・また、コードを見た人がprint文を見ることで「ファイル名がないときの処理」と分かると考えた

### 見つけたきっかけ

（自分のコードなのでなし）

**Comment by gmcgsokdeuvmt** [comment]
仕様1

### 実際のコード
- [OmuriceGenerator.java](https://github.com/gmcgsokdeuvmt/gmcgsokdeuvmt-readable-code-tsukuba/blob/master/java/OmuriceGenerator.java#L1)

1行目

``` java
public class OmuriceGenerator {
...
}
```

### どうしてリーダブルだと思っているかの説明

オムライスを作るクラスなので、`OmuriceGenerator` というクラス名をつけた。仕様では「レシピを出力」とあるが、実際にできるのは「オムライス」なので、それがわかるクラス名にしたほうがいいと思った。

**Comment by ksfee684** [comment]
### 実際のコード
- RecipeManager.java

``` Java
private RecipeList recipeList;

public RecipeManager() {
    initRecipeList();
}

private void initRecipeList() {
    recipeList = new RecipeList();
    recipeList.readRecipeData();
}
```

### どうしてリーダブルだと考えたかの説明

`RecipeManager`が一度`RecipeList`とラップしたものを持っているため、メソッドを細かく分けることができて読みやすい

### 見つけたきっかけ

**Comment by chamstorage** [comment]
### 実際のコード

``` java
while ((outputLine = br.readLine()) != null) {
    System.out.println(id + ": " + outputLine);
    id++;
    }
```

### どうしてリーダブルだと考えたかの説明

・readLineした結果を入れる変数名を、「line」ではなく「outputLine」としていて、出力するために読み込んだということが分かりやすい

### 見つけたきっかけ

ファイル読み込み処理を見ていて、変数名の意味を考えずに読み進められたから

**Comment by chiemi627** [comment]
### 実際のコード

```
public class OmuriceGenerator {
```

### どうしてリーダブルだと考えたかの説明

仕様１が「オムライス」と出力する、という仕様。
Recipeクラスが「オムライス」と出力すると一般性が異なるので、
仕様１の段階でクラス名がOmuriceGeneratorとなっているのは妥当だと思いました。

ただレシピごとにGeneratorを用意するのは今後大変になりそうです。

### 見つけた経緯

クラス名を最初に見たときの感想です。

**Comment by chamstorage** [comment]
### 実際のコード

``` java
catch(IOException e){
      System.out.println(e + "ファイル操作エラー");
}
```

### どうしてリーダブルだと考えたかの説明

・エラー処理をデフォルトの文章だけに頼っていないので分かりやすいと思ったから

### 見つけたきっかけ

・読み進めていて、自分の書き方（エラー文をデフォルトの文のまま出力する）と違うところがあったから

**Comment by tsss-j** [comment]
### 実際のコード

```
Boolean fileNameExists = false;
```

### どうしてリーダブルだと考えたかの説明

意味の分かりやすい変数名

### 見つけたきっかけ

普通に読んでてもbooleanを使ってる理由が分かった

**Comment by chamstorage** [comment]
### 実際のコード

``` java
final String filePass = "recipe-data.txt";
```

のfinalの部分

### どうしてリーダブルだと考えたかの説明

・この部分は今後変更しないということがわかったから

### 見つけたきっかけ

・読み進めていて、自分の書き方（その後変更することがない変数であっても別にfinalをつけない）と違うところがあったから

**Comment by ksfee684** [comment]
### 実際のコード

``` Java
BufferedReader br = new BufferedReader(new FileReader(new File("recipe-title-data.txt")));
```

### どうしてリーダブルだと考えたかの説明

Javaで`BuferedReader`を使う場合でよく使われる`br`を変数名として使っている

### 見つけたきっかけ

自分のコードと違ったため

**Comment by tsss-j** [comment]
###実際のコード   

```
public void init(String args[]){
        if(args.length==0){
　　　　　　　.......
        }
}
```

###どうしてリーダブルだと考えたかの説明
初期の基本処理を別関数にくくり出しているから
###きっかけ
自分は分けていなかったので

**Comment by chiemi627** [comment]
### 実際のコード

``````
in README.md 
#### コンパイルできない？

もし、コンパイルができない場合、ファイル名・クラス名を間違えている可能性があります。java の場合、ファイル名とクラス名が一致する必要がありますので、よく確認してみてください。

#### そもそも javac できない

そもそも javac 出来ない可能性があります。Windows の場合 javac のプログラムは
```C:\\Program Files\\Java\\jdk1.8.0_40\\bin\\```下にあると思います。ここにパスを通すようにしてみて下さい。
``````

実行するための説明がかなり丁寧に書かれている。

### どうしてリーダブルだと考えたかの説明

コードを見る前にそもそも実行できないと仕方が無いので、
実行するまでの方法や、実行できないときの対処があるのは良いと思いました。

### 見つけた経緯

どのように実行するのか確認しようとREADME.mdをみて。

**Comment by tsukumaru** [comment]
### 実際のコード

``` java
public static void main(String[] args) {
        displayRecipeNames();
    }

    private static void displayRecipeNames() {
```

### どうしてリーダブルだと考えたかの説明

ただmainの中にダラダラ書くのではなく関数名でmainの中の処理を表現されていて、
わかりやすかった。

### 見つけた経緯

自分はmainの中にダラダラ書いてしまっていたため。

**Comment by tsss-j** [comment]
### 実際のコード

```
    public static void main(String[] args) {
        // TODO Auto-generated method stub
        ReadableCode rc = new ReadableCode(args);
    }
```

### どうしてリーダブルだと考えたかの説明

main中の記述が少なくてスリム

### 見つけた経緯

mainを見るのが一回で済んだので

**Comment by tsukumaru** [comment]
### 実際のコード

![2015-07-04 14 05 04](https://cloud.githubusercontent.com/assets/5095933/8506587/134a944a-2256-11e5-82fc-72e6dd7a8df0.png)

### どうしてリーダブルだと考えたかの説明

mainの書かれているクラス(Cooking)と他のクラスで階層を分けることで最初ソースコードを追うときに追いやすかったため。

### 見つけた経緯

自分は階層で分けていなく、新たな発見だったため。

**Comment by gmcgsokdeuvmt** [comment]
### 実装のコード

public class Recipe {
...
}

### どうしてリーダブルだと考えたかの説明

レシピの内容をここに書き込むようにすればいいということがわかる

### 見つけた経緯

自分がレシピ単位でのクラス分けを意識していなかったため

**Comment by chamstorage** [comment]
### 実際のコード

``` java
BufferedReader br = new BufferedReader(new FileReader(filePass));
```

のfinalの部分

### どうしてリーダブルだと考えたかの説明

・読み込みが一行でまとまっていて分かりやすかったから

### 見つけたきっかけ

・読み進めていて、自分の書き方（いちいちFileReaderを宣言して〜みたいなやり方）と違うところがあったから

**Comment by gmcgsokdeuvmt** [comment]
### 実装のコード

```
public static Recipe makeRecipeFromCSV(String line){
...
}
```

### どうしてリーダブルだと考えたかの説明

Recipeを作るために、何が基になっているのかがすぐわかる。
メインの流れでこのメソッドが使用される必要があり、このメソッドでファイル読み込みの流れがわかると考えたため。

### 見つけた経緯

どうやってRecipeクラスのインスタンスを生成するのかがすぐにわかったため。

**Comment by chiemi627** [comment]
### 実際のコード

``` java
  public class RecipeGenerator {
    List<Recipe> recipeList = new ArrayList<Recipe>();
    ...
    public void generateRecipesFromFile(){
    }
```

### どうしてリーダブルコードだと考えたか

元のクラス名Generatorに合わせて、ファイルからクラスをGenerateするようにしたから。

**Comment by chamstorage** [comment]
### 実際のコード

``` java
final int RECIPE_NAME = 0;
final int METHOD = 1;

String recipeName = contents[RECIPE_NAME];
String method = contents[METHOD];
```

のfinalの部分

### どうしてリーダブルだと考えたかの説明

・読み込んだ文のなかから、何を取り出したのか分かりやすくなるから
（enum使いたかったのですがjavaでの挙動がいまいち分かってません）

### 見つけたきっかけ

（自分のなので無し）

**Comment by chiemi627** [comment]
### 実際のコード

クラス構成の話。処理系をRecipeGeneratorにおき、
Recipeオブジェクト用にRecipeクラスを用意した。

### どうしてリーダブルコードだと考えたかの説明

処理系とデータ定義を分離しやすい。
レシピ属性の変更に対応しやすいから。

**Comment by chiemi627** [comment]
### 実際のコード

``` java
public class Recipe{
    public int id;
    public static int lastID = 0;

    public Recipe(){
        id = lastID;
        lastID++;
    }
}
```

### どうしてリーダブルコードだと考えたかの説明

Recipeオブジェクトを生成すると自動的にＩＤが振られる

**Comment by gmcgsokdeuvmt** [comment]
## 実際のコード

```
                while ((line = br.readLine()) != null) {
                    //行ごとの処理はRecipeクラスで行っています
                    Recipe recipe = Recipe.makeRecipeFromCSV(line);
                    this.addRecipe(recipe);
                }
```

## どうしてリーダブルコードだと考えたかの説明

CSVのラインごとにレシピが生成されることがわかり、CSVファイルの扱われ方がよくわかるコードだったから

## 見つけたきっかけ

仕様4でのデータ追加による拡張が楽だったため

**Comment by tsukumaru** [comment]
### 実際のコード

``` java
public void showRecipeName(int id){

public void showAllRecipeNames() {

public void showAllRecipeNamesWithId(){
```

### どうしてリーダブルだと考えたかの説明

引数のあるなし、レシピを全出力させる関数にAllとつける、With~~でなにが一緒に出力されるのかなどをぱっと見でわかるようになっている

**Comment by chiemi627** [comment]
### 実際のコード

class RecipeManager
    public boolean initManager(){

### どうしてリーダブルだと思ったか

起動時に行う処理をinitにまとめたので。
