### ISSUE TITLE
リーダブルコード筑波：Swiftグループのリーダブルコード集め場所

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#17]
次のことを書く場所です。
- 自分で書いていて工夫したところ（リーダブルに書いたと思っているところ）
- 他の人のコードを読んでリーダブルだと思ったところ

↑について次のテンプレートを埋めてコメントに書いてください。1つの↑につき1つのコメントにしてください。つまり、1人で4個の↑を書くときは、1つのコメントに4個書くのではなく、4つコメントにわけて書きます。

`````` text
### 実際のコード

（ここに実際のコードを張る）

ヒント：

    ```sh
    echo "Hello"
    ```

↑というように

    ```言語名
    （コード）
    ```

というように囲むとコードが色付きになる。

### どうしてリーダブルだと考えたかの説明

（ここに↑のコードがどうしてリーダブルだと考えたか説明する）

### 見つけたきっかけ

（他の人のコードから見つけた時だけ、ここに見つけたきっかけを書く。）
``````

例（他の人のコードから見つけた場合）：

``````
### 実際のコード

```c
exit(EXIT_FAILURE); /* エラーの場合は異常終了する */
```

### どうしてリーダブルだと考えたかの説明

コマンドの終了ステータスは、正常終了するときは`0`、異常終了するときは`0`以外の値を返すのが通例です。そのため、このコードは次のようにしても通例通りの動きになります。

```c
exit(1);
```

ただ、動くのは動きますが、`EXIT_FAILURE`という名前を使っている方が「失敗して終了するんだな」というのがわかりやすいのでリーダブルだと考えました。

なお、`EXIT_SUCCESS`というのもあるので、同様の理由で正常終了するときはそれを使うのがよいと思います。

### 見つけた経緯

ちゃんとエラー処理をしていて立派だなぁと思って読み進めたら異常終了することがわかりやすいコードだと気づきました。
``````

**Comment by minami1389** [comment]
### 実際のコード

``` Swift
//${プロジェクトの絶対パス}/${プロジェクト名}/
let kFileRepositryPath = "/Users/minami/readable-code/minami1389-readable-code-tsukuba/minami1389-readable-code-tsukuba/"
```

### どうしてリーダブルだと考えたかの説明

ファイルが置いてある場所のパスを他の環境でも指定しやすいように、指定の仕方をコメントとして書いた。

**Comment by gates1de** [comment]
### 実際のコード

``` swift
func readRecipeData() {
        let filePath = "/Users/gates1de/develop/swift/readable-code-tsukuba/readable-code-tsukuba/recipe-data.txt"
        self.recipeDataString = String(contentsOfFile: filePath, encoding: NSUTF8StringEncoding, error: nil)
}
```

### リーダブルな理由

txtファイルの読み込みは一行で書けてしまうが, ファイルのパスをそのままinitializerの引数に入れてしまうとコード自体見にくくなるため, ファイルのパスは別の変数に格納する

**Comment by minami1389** [comment]
### 実際のコード

``` Swift
let recipeDataFileName = kFileRepositryPath + "recipe-data.txt"
if let recipe = String(contentsOfFile: recipeDataFileName, encoding: NSUTF8StringEncoding, error: nil) {
    println(recipe)
}
```

### どうしてリーダブルだと考えたかの説明

一度ファイル名を定数に入れてから使用することで、この文字列(kFileRepositryPath + "recipe-data.txt")がレシピデータのファイルネームを表しているかことが分かりやすいようにした。

**Comment by miup** [comment]
### 実際のコード

``` Swift
func splitLine(str: String) -> [String] {
    return split(str) { contains("\n", $0) }
}
```

### どうしてリーダブルだと考えたかの説明

split関数の見た目が直感的にわかりにくいため、行で分割のメソッドを別に作成した

**Comment by minami1389** [comment]
### 実際のコード

```Swift
//1行ごとに文字列を抜き出す
    recipe.enumerateLines({
        line, stop in
        println(line)
    })
```

### どうしてリーダブルだと考えたかの説明
見慣れないメソッドを使用したので、メソッドの内容をコメントした。

**Comment by minami1389** [comment]
### 実際のコード

``` Swift
//enumerateLines:1行ごとに文字列を抜き出すメソッド
//recipesの中から1つずつrecipeを取り出し表示する
recipes.enumerateLines({
    recipe, stop in
    println(recipe)
})
```

### どうしてリーダブルだと考えたかの説明

見慣れないメソッドを使用したので、実装の意味をコメントした。

**Comment by gates1de** [comment]
### 実際のコード

``` swift
func separtLines(originalString: String) {
    originalString.enumerateLines( { (line, stop) in
        let index = self.recipeDataStringArray.count + 1
        self.recipeDataStringArray.append("\(index): \(line)")
    })
}
```

### リーダブルな理由

ファイルを1行ずつ読み込む処理にindexは付与されていない. enumerateLines()の外でvar i = 1と宣言して, enumerateLines()の中で++iとかでやってもいいと思うけど, functionの中身が増えてくると可読性が下がる, はず.

**Comment by gates1de** [comment]
### 実際のコード

``` swift
// MARK: 表示系関数
func printAllRecipeData() {
    println(self.recipeDataString)
}
```

### リーダブルな理由

functionを作っていくと編集したいfunctionを探す時に厳しくなるので, MARKをつける

**Comment by minami1389** [comment]
### 実際のコード

``` Swift
var recipe = Recipe()

recipe.readRecipeData()
recipe.printSeparateRecipeData()
```

### どうしてリーダブルだと考えたかの説明

Recipeクラスを作ることで、コード量が分割され単純に見やすいし、Recipeの内部実装を気にせずに
利用することができると思った。

### 見つけた経緯

コードをぱっと見たときに、Recipeインスタンスの作成とrecipeの処理だけが目に入ってきてわかりやすいと思ったから。

**Comment by gates1de** [comment]
### 実際のコード

``` swift
//TODO: input your file path
    let yourFilePath = "/Users/Illya/develop/miuP-readable-code-tsukuba/reabable-code-tsukuba/reabable-code-tsukuba/recipe-data.txt"
```

### どうしてリーダブルだと考えたかの説明

他の人と一緒にプログラミングする時, 自分が動いている環境と合わせるため, 他の人に「これをやってね」という意味でTODOをつけるのは非常に良い.

### 見つけた経緯

自分がファイルの指定について説明をmarkdownに書くの忘れたと思ったら, miuPの方には書いてあったので, おぉ〜と思った次第です!

**Comment by miup** [comment]
### 実際のコード

``` Swift
displayRecipe(recipeDictionary)        
displayRecipeById(2, recipeDictionary)
```

### どうしてリーダブルだと考えたかの説明

直にprintlnを書かず、メソッドを切り分けることで汎用性の高いコードになっていて良いと思った

### 見つけた経緯

main()を見て簡潔にまとまっていて良いと思ったため

**Comment by gates1de** [comment]
### 実際のコード

``` swift
return textData ?? "error"
```

### どうしてリーダブルだと考えたかの説明

本当は1行くらいしか処理を書かないのに, if-else文をつけるのは面倒だし, パッと見ても処理が見にくいこともあるため, このくらい簡潔にかけると読みやすくなると考えたから.

### 見つけた経緯

普段自分が使わない(知らなかった)記法だけど, 初見でも全然理解できたので, おぉ〜と思った次第です!←

**Comment by gates1de** [comment]
### 実際のコード

``` swift
if input == 0 {
    for (var i = 1; i <= count(recipesDict); i++) {
        println("\(i): " + recipesDict[i]!)
    }
} else {
    println(recipesDict[input] ?? "Not Found")
}
```

### どうしてリーダブルだと考えたかの説明

if-else文を書くときは, if文の括弧閉じの隣にelseを書くと, 縦に長くなくて見やすいと感じたから

### 見つけた経緯

確かリーダブルコード勉強会に参加したことのある友達が言っていた気がして, それを思いだした次第です!

**Comment by minami1389** [comment]
### 実際のコード

``` Swift
var recipeDataString: String!
var recipeDataStringArray = Array<String>()
```

### どうしてリーダブルだと考えたかの説明

各所で使う変数をインスタンス変数として宣言することで、Recipeの持ち物であることがわかり、わかりやすいと思ったから。

### 見つけた経緯

その後の実装がしやすいと感じたため。

**Comment by minami1389** [comment]
### 実際のコード

``` swift
func separtLines(originalString: String) {
    originalString.enumerateLines( { (line, stop) in
            let index = self.recipeDataStringArray.count + 1
            self.recipeDataStringArray.append("\(index): \(line)")
    })
}
```

### どうしてリーダブルだと考えたかの説明

この部分をメソッドとして切り出すことで、なにをしているかわかりやすいと感じたから。

### 見つけた経緯

何行にも渡るメソッドがないことに気づいたから。

**Comment by minami1389** [comment]
### 実際のコード

``` swift
init() {
        readRecipeData()
    }
```

### どうしてリーダブルだと考えたかの説明

txtからRecipeDataを読み込むメソッドを初期化の時に呼ぶことで、Recipeを利用しやすくなった感じたため。

**Comment by minami1389** [comment]
### 実際のコード

``` swift
self.recipeDataDictionary =  self.convertDataStringToDictionary(recipeDataString)
```

### どうしてリーダブルだと考えたかの説明

self.recipeDataDictionaryへの値代入を、convertDataStringToDictionary内ではなく、メソッドの返り値を代入にすることによって行うことで、何が行われているかわかりやすくなったと感じたから。

**Comment by minami1389** [comment]
### 実際のコード

``` swift
func printAllRecipeData() {
        for var i = 1; i <= self.recipeDataDictionary.count; i++ {
            printRecipeDataById(i)
        }
    }
```

### どうしてリーダブルだと考えたかの説明

printRecipeDataByIdを利用してこのメソッドを実装することで、すべてのIdを一つずつprintしていることがわかりやすくなったと感じたから。

**Comment by gates1de** [comment]
### 実際のコード

``` swift
for doCount in 0..<userCount {
    let (userName, recipeId) = getStdIn()
    allUserName.append(userName)
    allUserRecipe.append(recipeId)
}
```

### どうしてリーダブルだと考えたかの説明

標準出力の結果を受け取って配列に入れる処理をmain関数で実装した結果, 最小コードになって, しかも何が取得できたのかがわかると感じたから
