### ISSUE TITLE
リーダブルコード筑波：Luaグループのリーダブルコード集め場所

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#18]
次のことを書く場所です。
- 自分で書いていて工夫したところ（リーダブルに書いたと思っているところ）
- 他の人のコードを読んでリーダブルだと思ったところ

↑について次のテンプレートを埋めてコメントに書いてください。1つの↑につき1つのコメントにしてください。つまり、1人で4個の↑を書くときは、1つのコメントに4個書くのではなく、4つコメントにわけて書きます。

`````` text
### 実際のコード

（ここに実際のコードを張る）

ヒント：

    ```sh
    echo "Hello"
    ```

↑というように

    ```言語名
    （コード）
    ```

というように囲むとコードが色付きになる。

### どうしてリーダブルだと考えたかの説明

（ここに↑のコードがどうしてリーダブルだと考えたか説明する）

### 見つけたきっかけ

（他の人のコードから見つけた時だけ、ここに見つけたきっかけを書く。）
``````

例（他の人のコードから見つけた場合）：

``````
### 実際のコード

```c
exit(EXIT_FAILURE); /* エラーの場合は異常終了する */
```

### どうしてリーダブルだと考えたかの説明

コマンドの終了ステータスは、正常終了するときは`0`、異常終了するときは`0`以外の値を返すのが通例です。そのため、このコードは次のようにしても通例通りの動きになります。

```c
exit(1);
```

ただ、動くのは動きますが、`EXIT_FAILURE`という名前を使っている方が「失敗して終了するんだな」というのがわかりやすいのでリーダブルだと考えました。

なお、`EXIT_SUCCESS`というのもあるので、同様の理由で正常終了するときはそれを使うのがよいと思います。

### 見つけた経緯

ちゃんとエラー処理をしていて立派だなぁと思って読み進めたら異常終了することがわかりやすいコードだと気づきました。
``````

**Comment by rizaudo** [comment]
### 実際のドキュメント

``` org
* 概要
リーダブルコード勉強会の課題向けのリポジトリです。

** 動作環境
Mac OSX 10.10.4常にHomeBrewでLua 5.2.3を入れて動作確認をしています。
```

### コードでないのにリーダブルコードだと思う理由

現在書いているものはまだモジュールも無い等、複雑でないですが、大きいプロジェクトならば依存関係が複雑になり、動く環境をそもそも作れないという事態が発生します。
ここでこのドキュメントを書くことで、少なくとも動く環境がわかり、他の人がプロジェクトのビルドをする手助けになる事から、リーダブルなコードにつながる物だと考えたからです。

### 見つけたきっかけ

メンターの方と話していた時に、アドバイスを頂いて。

**Comment by rizaudo** [comment]
### 実際のコード

``` lua
filename = arg[1]
```

### リーダブルコードである理由

Luaでは渡された引数はargというテーブルに入れられるのですが、引数はarg[1]からarg[N]となりarg[0]はスクリプト名が入っています。
このままではarg[X]といれられた際に即座に変数が持つ型や目的がわからないため、明確に用途がわかる変数に入れ直しているためです。

### 見つけたきっかけ

自分のコードを見直していた際に。

**Comment by rizaudo** [comment]
### 実際のコード(spec3時点)

``` lua
--[[
recipe.lua - レシピ管理プログラム
HOWTOUSE: 'lua recipe.lua "FILENAME"'

Copyright (c) 2015 Kei Hosoya
This software is released under the MIT License, see LICENSE.txt.
]]
```

### リーダブルコードである理由

プログラムコードを何の用途か明示的に最初のバナーで書かない場合、複数のソースコードをプロジェクト内で扱う時にコードが理解できても、このモジュールの目的が理解できません。
そこでバナーを書いて、使用方法やライセンスを書く事で目的を明示し、コードを理解する一助としたからです。

### 見つけたきっかけ

自分のコードを見直していた際に。

**Comment by rizaudo** [comment]
okkezさんのコードをcloneしました。

### 実際のコード

``` lua
for line in io.lines(filename) do
   id = id + 1
   if tonumber(target_id) == id then
      print(string.format("%d: %s", id, line))
      os.exit()
   end
   if not target_id then
      print(string.format("%d: %s", id, line))
   end
end
```

os.exit()の部分がこの場合なら良いと思っています。

### 理由

私の感覚ではforで回すのはごく少数の有限回なので、回しても良いと思ったのですが、このような例だとos.exit()は理にかなっていると考えました。
os.exit()はエラー処理か終了処理にしか使われません、なのでわざとfor文の中でBreak文のように使う事でif文の目的を二つに絞れます。
これは目的を理解しやすくするのに効果的であると思います。

### きっかけ

メンターの方とのお話で、当初は自分のCなどの感覚で、よくないと考えていましたが、Luaでかつこのプログラムならば綺麗な使いかただと思いなおしたのがきっかけです。

**Comment by Nymphium** [comment]
### 実際のコード

``` lua
local get_recipe = function(filename)
    local f = io.open(filename)
    local ret_tbl = {}

    for l in f:lines() do
        table.insert(ret_tbl, l)
    end

    f:close()

    return ret_tbl
end
```

### リーダブルな理由

3つある｡
- `local`プレフィクスを付けスコープを限定することでコードを追いやすくなる｡
- 戻り値のサフィックスに型の省略名を書くことでわかりやすくする｡
- 関数名のプレフィクスに`get_`などを付けることで､関数の働きをわかりやすくした｡

### 見つけたきっかけ

教えてもらった等

**Comment by Nymphium** [comment]
### 実際のコード

``` Lua
local output_recipes = function(usr, filename, id)
    local recipe = get_recipe(filename)
    local fmt = "%2d: %s"
    print("User Name: " .. usr)

    if type(id) == "number" then
        print(fmt:format(id, recipe[id + 1]))
    else
        for i = 0, #recipe - 1 do
            print(fmt:format(i, recipe[i + 1]))
        end
    end
end
```

### リーダブルな理由

`string.format()`に渡す書式文字列を`fmt`として定義することで見やすくする｡
また､`print()`の引数が長くならずにコロン記法で完結に記述できるようになる｡

### 見つけた理由

見やすいように工夫した結果

**Comment by rizaudo** [comment]
### 実際のコード

``` lua
print(string.format("ユーザー: %d: %s", user_id, user_name))
```

### リーダブルな理由

Cのprintfと同じ書式を使えることで、Luaの連結演算子(..)などよりも構造的に文章を定義できている。

### 見つけた理由

CのPrintfのフォーマットがそこそこ好きなため。
