### ISSUE TITLE
リーダブルコード筑波：各グループでのリーダブルコード

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#19]
各グループで、「自分たちがリーダブルだと思うコード上位2つ」を選んでここに書いてください。

ここに書いてもらったものをトレーナーが参加者全員に紹介します。（紹介しているときにトレーナーがわからなかったらグループに質問します。）

次のテンプレートを埋めてください。

``` text
## グループ名

（ここにグループ名を書く）

## 自分たちのグループでリーダブルなコード1

### 実際のコード

（ここに実際のコードを張る）

### どうしてリーダブルだと考えたかの説明

（ここに↑のコードがどうしてリーダブルだと考えたか説明する）

### 見つけたきっかけ

（他の人のコードから見つけた時だけ、ここに見つけたきっかけを書く。）

## 自分たちのグループでリーダブルなコード2

### 実際のコード

（ここに実際のコードを張る）

### どうしてリーダブルだと考えたかの説明

（ここに↑のコードがどうしてリーダブルだと考えたか説明する）

### 見つけたきっかけ

（他の人のコードから見つけた時だけ、ここに見つけたきっかけを書く。）
```

例：

``````
## グループ名

Cグループ

## 自分たちのグループでリーダブルなコード1

### 実際のコード

```c
exit(EXIT_FAILURE); /* エラーの場合は異常終了する */
```

### どうしてリーダブルだと考えたかの説明

コマンドの終了ステータスは、正常終了するときは`0`、異常終了するときは`0`以外の値を返すのが通例です。そのため、このコードは次のようにしても通例通りの動きになります。

```c
exit(1);
```

ただ、動くのは動きますが、`EXIT_FAILURE`という名前を使っている方が「失敗して終了するんだな」というのがわかりやすいのでリーダブルだと考えました。

なお、`EXIT_SUCCESS`というのもあるので、同様の理由で正常終了するときはそれを使うのがよいと思います。

### 見つけたきっかけ

ちゃんとエラー処理をしていて立派だなぁと思って読み進めたら異常終了することがわかりやすいコードだと気づきました。

## 自分たちのグループでリーダブルなコード2

（↑と同様）
``````

**Comment by Nymphium** [comment]
## グループ名

Luaグループ

## 自分たちのグループでリーダブルなコード1

### 実際のコード

``` lua
--[[
recipe.lua - レシピ管理プログラム
HOWTOUSE: 'lua recipe.lua "FILENAME"'

Copyright (c) 2015 Kei Hosoya
This software is released under the MIT License, see LICENSE.txt.
]]
```

### どうしてリーダブルだと考えたかの説明

プログラムコードを何の用途か明示的に最初のバナーで書かない場合、複数のソースコードをプロジェクト内で扱う時にコードが理解できても、このモジュールの目的が理解できません。
そこでバナーを書いて、使用方法やライセンスを書く事で目的を明示し、コードを理解する一助としたからです。

### 見つけたきっかけ

自分のコードを見直していた際に。

## 自分たちのグループでリーダブルなコード2

### 実際のコード

``` lua
local output_recipes = function(usr, filename, id)
    local recipe = get_recipe(filename)
    local fmt = "%2d: %s"
    print("User Name: " .. usr)

    if type(id) == "number" then
        print(fmt:format(id, recipe[id + 1]))
    else
        for i, j in pairs(recipe) do
            print(fmt:format(i - 1, j))
        end
    end
end
```

### どうしてリーダブルだと考えたかの説明

`string.format()`に渡す書式文字列をfmtとして定義することで見やすくする｡
また､`print()`の引数が長くならずにコロン記法で完結に記述できるようになる｡

### 見つけたきっかけ

見やすいように工夫した結果

**Comment by tsukumaru** [comment]
## グループ名

Java(通路側)

## 自分たちのグループでリーダブルなコード1

### 実際のコード

``` java
final String filePass = "recipe-data.txt";
```

### どうしてリーダブルだと考えたかの説明

この部分は今後変更しないということがわかったから

### 見つけたきっかけ

読み進めていて、自分の書き方（その後変更することがない変数であっても別にfinalをつけない）と違うところがあったから

## 自分たちのグループでリーダブルなコード2

### 実際のコード

![2015-07-04 14 05 04](https://cloud.githubusercontent.com/assets/5095933/8506818/cee1c58c-2262-11e5-89af-385c30e7f660.png)

### どうしてリーダブルだと考えたかの説明

mainの書かれているクラス(Cooking)と他のクラスで階層を分けることで最初ソースコードを追うときに追いやすかったため。

### 見つけたきっかけ

自分は階層で分けていなく、新たな発見だったため。

**Comment by HirokiCHIBA** [comment]
## グループ名

JavaScriptグループ

## 自分たちのグループでリーダブルなコード1

### 実際のコード

``` javascript
var users = [
    {
        recipes: [
            {
                id: 1,
                name: "オムライス",
                detail: "卵を焼いてご飯に載せる",
            },
            {
                id: 2,
                name: "親子丼",
                detail: "鶏肉を焼いて卵でとじてご飯にのせる",
            },
            {
                id: 3,
                name: "杏仁豆腐",
                detail: "牛乳と砂糖をまぜてゼラチンで固める",
            },
        ],
        name: 'user1',
    },
    {
        recipes: [      // 以下省略
```

### どうしてリーダブルだと考えたか

適切にインデントすることで、データのオブジェクト・配列の包含関係がわかりやすい。

## 自分たちのグループでリーダブルなコード2

### 実際のコード

``` javascript
 console.log(users[j].recipes[i].id+": "+users[j].recipes[i].name+" "+users[j].recipes[i].detail);
```

### どうしてリーダブルだと考えたか

オブジェクトのプロパティは「['キー']」でも書けるが今回は「.」でつなぐことで表し、配列のみ「[]」で表すことで、両者を区別している。

**Comment by ksfee684** [comment]
## グループ名

Java - 窓際側

## 自分たちのグループでリーダブルなコード1

### 実際のコード

``` Java
BufferedReader br = new BufferedReader(new FileReader(new File("recipe-title-data.txt")));
```

### どうしてリーダブルだと考えたかの説明

Javaで`BuferedReader`を使う場合でよく使われる`br`を変数名として使っている

### 見つけたきっかけ

自分のコードと違ったため

## 自分たちのグループでリーダブルなコード2

### 実際のコード

``` Java
public void init(String args[]){
        if(args.length==0){
　　　　　　　.......
                .......
        }
}
```

### どうしてリーダブルだと考えたかの説明

初期の基本処理を別関数にくくり出しているから

### きっかけ

自分は分けていなかったので

**Comment by kentya6** [comment]
## グループ名

Swift

## 自分たちのグループでリーダブルなコード1

### 実際のコード

``` swift
let recipeDataFileName = kFileRepositryPath + "recipe-data.txt"
if let recipe = String(contentsOfFile: recipeDataFileName, encoding: NSUTF8StringEncoding, error: nil) {
    println(recipe)
}
```

### どうしてリーダブルだと考えたかの説明

一度ファイル名を定数に入れてから使用することで、この文字列(kFileRepositryPath + "recipe-data.txt")がレシピデータのファイルネームを表しているかことが分かりやすい。

定数の命名規則がAppleのガイドラインに沿っている。

## 自分たちのグループでリーダブルなコード2

### 実際のコード

``` swift
var recipe = Recipe()

recipe.readRecipeData()
recipe.printSeparateRecipeData()
```

### どうしてリーダブルだと考えたかの説明

Recipeクラスを作ることで、コード量が分割され単純に見やすいし、Recipeの内部実装を気にせずに
利用することができると思った。

### 見つけたきっかけ

コードをぱっと見たときに、Recipeインスタンスの作成とrecipeの処理だけが目に入ってきてわかりやすいと思ったから。

**Comment by ghost** [comment]
## グループ名

C言語グループ

## 自分たちのグループでリーダブルなコード1

### 実際のコード

``` c
#define RECIPE_LEN 100 //レシピタイトルの長さの最大文字数
```

### どうしてリーダブルだと考えたかの説明

buffer sizeの指定をdefineですることで、今後の変更がしやすい
bufferの使い道が書かれていて良い

### 見つけたきっかけ

自分はbufferとしか書いていなかったから

## 自分たちのグループでリーダブルなコード2

### 実際のコード

for(int id=0; (fscanf(p_recipe_file, "%s",s) != EOF); id++)
{
printf("%03d: %s\n",id, s);
}

### どうしてリーダブルだと考えたかの説明

ループの名前をidにすることで、このループがIDを表すのだと分かる

**Comment by pyonnuka** [comment]
## グループ名

Ruby

## 自分たちのグループでリーダブルなコード1

### 実際のコード

``` ruby
def show_recipes_all(recipes)
    recipes.each_with_index do |recipe, id|
        show_recipe(recipe, id)
    end
end

def show_recipe_by_id(recipes, id)
    show_recipe(recipes[id], id)
end

#...中略...

show_id = ARGV[1].to_i
if show_id
    show_recipe_by_id(recipes, show_id)
else
    show_recipes_all(recipes)
end
```

### どうしてリーダブルだと考えたかの説明

show_recipe_by_idやshow_recipes_allはメソッドの命名が明示的なので、具体的な実装を見なくてもどんな動作をするのか推測しやすい。

## 自分たちのグループでリーダブルなコード2

### 実際のコード

``` ruby
target_recipe_id = ARGV[0]
```

### どうしてリーダブルだと考えたかの説明

ひと目で，第一引数が，recipeのidを指定しているんだなと分かる．

**Comment by mtjune** [comment]
## グループ名

Ruby - スクリーン側

## 自分たちのグループでリーダブルなコード1

### 実際のコード

``` ruby
class Recipe
  def initialize(filename)
    @file = File.open(ARGV[0])   
    @recipes = []
  end

  def print_recipes_all
    ## 略
  end

  def print_recipes_by_id(search_id)
    ## 略
  end

  def read
    ## 略
  end
end

filename = ARGV[0]
search_id = ARGV[1]

recipe = Recipe.new(filename)
recipe.read

if search_id.nil?
  recipe.print_recipes_all
else 
  recipe.print_recipes_by_id(search_id)
end
```

### どうしてリーダブルだと考えたかの説明

素直にオブジェクト指向に則って書くほうが役割がわかりやすい.  
（内部の処理が分離されていて分かりやすい）

### 見つけたきっかけ

処理の内容がクラス化されていたので、
実行部分を見てみると何を行っているかが一目で分かるようになっていました。

## 自分たちのグループでリーダブルなコード2

### 実際のコード

``` ruby
filename = ARGV[0]
```

### どうしてリーダブルだと考えたかの説明

ARGVのままだと何を表しているのかわからなが,  
filenameという変数に置くことでわかるようになる.

### 見つけたきっかけ

ARGVが最初の方にしか出てきていなかったため.

**Comment by Butanosuke** [comment]
## グループ名

C++Love(しーぷらぶ)

## 自分たちのグループでリーダブルなコード1

### 実際のコード

``` c++
string recipe_file_path = argv[1];
printRecipeNames(recipe_file_path);
```

### どうしてリーダブルだと考えたかの説明

コマンドライン引数を変数に一度入れることで，何のデータをコマンドライン引数から得たのかわかりやすく表示しました.

## 自分たちのグループでリーダブルなコード2

### 実際のコード

``` c++
while(file.good()){
    ...
}
```

### どうしてリーダブルだと考えたかの説明

条件式に否定演算子を使っていないので、見落としにくく、可読性があがると考えました.

### 見つけたきっかけ

メンターの方に指摘していただきました.
