### ISSUE TITLE
リーダブルコード：メンターが紹介したいリーダブルなコード

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#2]
メンターは、全体に紹介したいリーダブルなコードをここにコメントしてください。

リーダブルなコードは参加者がグループ内で共有した中から選んでもよいですし、自分で参加者のコードを読んでいる中で見つけたものでも構いません。

紹介したいリーダブルなコードには少なくとも次の情報を含めてください。
この内容は各メンターが自分で紹介するので、アドリブでいろいろ話せるならここに書いておく内容はざっくりしたものでも構いません。ただし、コードを画面に表示させながら紹介するので、実際のコード（またはURL）は必ず書いてください。哨戒スルときは、これらの項目以外のことも話して構いません。
- 名前（またはタイトルあるいは一言説明）
- 実際のコード（またはURL）
- どうしてリーダブルだと考えたかの説明
- 見つけた経緯（またはきっかけ）

例:
### 名前

自己記述的定数名
### 実際のコード

https://github.com/doraemon13x/doraemon13x-sezemi-2014-readable-code-2/blob/master/mission3.c#L9

``` c
exit(EXIT_FAILURE); /* エラーの場合は異常終了する */
```
### どうしてリーダブルだと考えたかの説明

コマンドの終了ステータスは、正常終了するときは`0`、異常終了するときは`0`以外の値を返すのが通例です。そのため、このコードは次のようにしても通例通りの動きになります。

``` c
exit(1);
```

ただ、動くのは動きますが、`EXIT_FAILURE`という名前を使っている方が「失敗して終了するんだな」というのがわかりやすいのでリーダブルだと考えました。

なお、`EXIT_SUCCESS`というのもあるので、同様の理由で正常終了するときはそれを使うのがよいと思います。
### 見つけた経緯

ちゃんとエラー処理をしていて立派だなぁと思って読み進めたら異常終了することがわかりやすいコードだと気づきました。

**Comment by bash0C7** [comment]
Ruby島のみんなのコードから特にリーダブルなポイントを拾いだしました。

---

# 一言

"さもなくば死ね"

## https://github.com/ganmacs/ganmacs-sezemi-2015-readable-code/blob/master/lib/recipe.rb

``` ruby
    File.exist?(recipe_file_path) or raise "#{recipe_file_path} does not exist."
```

## リーダブルな理由

やりたい処理 or raiseという書き方で、処理が失敗したら例外を送出して失敗の旨を伝える意図が明らかになっている

---

# 一言

名前重要

## https://github.com/hoshitocat/hoshitocat-sezemi-2015-readable-code/blob/master/task3.rb

``` ruby
file.each_line { |line| recipes << line }
```

## リーダブルな理由

receipesという名前で何かの集合を扱うを示唆している。
また<<によってreceipesに送り込んでいる様子も、集合を扱っている様子の示唆を補強している。

---

# 一言

責務分割

## https://github.com/takujifunao/takujifunao-sezemi-2015-readable-code/blob/master/readable.rb

``` ruby
File::open("spec4-data.txt") {|f|
  f.each {|recipe| puts recipe}
}
```

## リーダブルな理由

ファイルに関する処理をブロックに閉じ込めることで、ファイルのクローズという代表的なリソース解放処理をアプリケーションから排して、間違いなくクローズされることを保証できる。

---

# 一言

意図を語るコメント

## https://github.com/yokoto/yokoto-sezemi-2015-readable-code/blob/master/recipe.rb

``` ruby
recipe_content = gets # IO#getsを使ってファイルの内容を取得
```

## リーダブルな理由

端的に書ける場合、あまりに端的すぎて人間には読みにくくなってしまう。コメントで意図の説明を補足することで補強できる。

---

# 一言

防御的プログラミング

## https://github.com/takujifunao/ganmacs-sezemi-2015-readable-code/blob/master/lib/recipe.rb#L50

``` ruby
    YAML.load_file(recipe_file_path) if exist_recipe_file?
```

## リーダブルな理由

存在しないファイルを読まない様にしている様が明確である

---

# 一言

演算子の計算順位の明示

## https://github.com/takujifunao/ganmacs-sezemi-2015-readable-code/blob/master/lib/recipe.rb#L50

``` ruby
    @recipe_file_path ||= (ARGV[0] || DEFALUT_FILE_PATH)
```

## リーダブルな理由

@recipe_file_pathの初期化処理として2つの状況があるが、()で囲まれているため正確に読み解く事ができる

---

# 一言

言語の文化に沿った命名

## https://github.com/yokoto/hoshitocat-sezemi-2015-readable-code/blob/master/task.rb

``` ruby
    recipe = recipes[recipe_id - 1]
```

## リーダブルな理由

集合には複数形を、1つだけなら単数系をつかうという、railsっぽい規則で書かれている。Rubyistならだいたいそうするだろう

---

# 一言

オブジェクト指向プログラミング

## https://github.com/hoshitocat/yokoto-sezemi-2015-readable-code/blob/master/recipe.rb

``` ruby
# レシピ情報を管理するためのクラス
class Recipe
```

## リーダブルな理由

レシピとは何かを、どういう振る舞いを行うかが、レシピというクラスとしてまとめあげられている。
レシピとはRecipeなのだということが明確になっている。

---

# 一言

心地いいテンポでのくりかえし

## https://github.com/hoshitocat/yokoto-sezemi-2015-readable-code/blob/master/recipe.rb

``` ruby
    if select_id == 1
      puts recipe_formator(recipe_name, recipe_id, url)
      break
    elsif select_id == 2
      puts recipe_formator(recipe_name, recipe_id, url)
      break
    elsif select_id == 3
      puts recipe_formator(recipe_name, recipe_id, url)
      break
    else
      puts recipe_formator(recipe_name, recipe_id, url)
    end
```

## リーダブルな理由

ifという基礎の基礎の分を繰り返しているが、1のとき2のとき3のときそれ以外のときと4種類の状況に切り分けて対応している様子がみてとれて、ここちがいい。
この程度の分岐数なら、こういう平易な書き方が理解コストが低い。

**Comment by sunaot** [comment]
### 実際のコード

処理をしたらすぐに検査をして、異常があればすぐに失敗しているのがいい。

https://github.com/akaimo/akaimo-sezemi-2015-readable-code/blob/9a02f7ab44aafeb9b81d2f79a38ba1bbdfe8e2f6/recipe.c#L8-L13

``` c
    fname = fopen(argv[1], "r");

    if (fname == NULL) {
        printf("%sが開けません\n", argv[1]);
        exit(1);
    }
```

### どうしてリーダブルだと思っているか？

`fname` の変数名のスコープの中で最短距離でエラーの検査をしています。読んでいて思考がジャンプしなくても何をしているか理解できるし、他の処理が挟まらないうちに `exit` で失敗してくれるのでファイルの open 失敗による他の影響を考える負担から解放され、リーダブルだと思いました。

### この書き方の一言説明

早めの検査、早めの失敗

### 見つけた経緯

`NULL` チェックの `==` `!=` の違いによるリーダブルなコードを探そうと見ていて、どうしてここで `NULL` をチェックしているんだっけ？と考えたときにこのコードはリーダブルだと気付きました。

**Comment by okkez** [comment]
コピペしてもらえると助かります！

**Comment by sunaot** [comment]
しました！

**Comment by piroor** [comment]
# 情報の由来が分かる変数名
- コード：https://github.com/Vetteru/yuyashiraki-sezemi-2015-readable-code/blob/master/displayRecipe.cpp#L14
- 理由：外部から与えられた情報に「input」と付いているので、どこ由来の情報かがすぐ分かる。安全な情報かどうかを判別しやすい。
- きっかけ：読み下していて、変数名にprefixが付いていて目立っていた。

# マジックナンバーの定数化
- コード： https://github.com/yuyashiraki/Vetteru-sezemi-2015-readable-code/blob/master/recipe_managing_system.cpp#L16
- 理由：値の変更が容易だし、参照箇所のコードを見たときに意味が分かりやすい。
- きっかけ：読み下していて、すべて大文字の名前が目立っていた。

# ゆとりのあるコード
- コード：https://github.com/KaieYT/oleom-sezemi-2015-readable-code/blob/master/main.cpp#L36
- 理由：どこからどこまでがループの初期化なのか、終了条件なのか、などを一目で区別できる。
- きっかけ：ここがギュッと詰まったコードを読んだあとで、このコードを読んだので。

**Comment by sunaot** [comment]
### 実際のコード
- https://github.com/shopetan/shopetan-sezemi-2015-readable-code/blob/master/code/no4.c#L10-L11
- https://github.com/shopetan/shopetan-sezemi-2015-readable-code/blob/master/code/no4.c#L23-L24

``` c
   /*file open*/
   fp = fopen(fname,"w");

     ...

   /*file close*/
   fclose(fp);
```

### どうしてリーダブルだと思っているか？

`fopen` や `fclose` にたいして同義のコメントをつける価値はあるのか？という話もあると思いますが、全体の構成の中で `fclose` を忘れないために対称性のある書式でコメントをつけているように読めたので、閉じ忘れの工夫としてリーダブルだと思いました。

### この書き方の一言説明

リソース解放に意識的なコメント

### 見つけた経緯

Ruby だと閉じ忘れにくい機能あるけれど C だと漏れそうという視点で眺めていたときに、構造の中で目に付きやすいようになっていたことに気付きこれは工夫なのかな？と思いリーダブルに挙げてみました。

**Comment by noriki-nakamura** [comment]
# 一言

単純な名前

# コード

https://github.com/k5trismegistus/k5trismegistus-sezemi-2015-readable-code/blob/master/cookingpapa.py

``` python
def load_recipe_data(csv_name):

def print_recipe_all(recipe_list):

def print_recipe_by_id(recipe_list, wanted_id):
```

# リーダブルな理由

関数名からこの関数が何を実行するのかがわかりやすい。
また、引数も何を必要としているのかが一目で見て理解することができる。

**Comment by cesare** [comment]
## 開発言語

Ruby

## 実際のコード

https://github.com/ganmacs/ganmacs-sezemi-2015-readable-code/blob/master/lib/recipe.rb#L58

``` ruby
puts Recipe.new.all_with_id
```

## どうしてリーダブルだと思っているか？

レシピの集合から「全部、ID付きで取ってくる」というニュアンスが `#all_with_id` というメソッド名に現れていて良い。
何をやっているかが明確になっている。

## この書き方の一言説明

名前重要

**Comment by myokoym** [comment]
### 名前（またはタイトルあるいは一言説明）

デバッグに必要な情報の出力

### 実際のコード（またはURL）

https://github.com/shopetan/akaimo-sezemi-2015-readable-code/blob/master/recipe.c#L15

``` c
    if (fname == NULL) {
        printf("%sが開けません\n", argv[1]);  /* ← ここ */
        exit(1);
    }
```

### どうしてリーダブルだと考えたかの説明

エラーになったファイルのパスが表示されるので、なぜエラーになったか見つけやすい

### 見つけた経緯（またはきっかけ）

目に飛び込んできた

**Comment by kawahara** [comment]
# 開発言語クループ: PHP

https://github.com/tsss-a/tsss-a-sezemi-2015-readable-code/issues/2

## 関数ドキュメント

https://github.com/sivukai/tsss-a-sezemi-2015-readable-code/blob/master/task/recipe_load.php#L2

``` php
//ファイル名を受け取ってそのファイル内のデータを１行ずつ取得
//配列に格納して返す
function file_load($filename){
```

---

https://github.com/tsss-a/-sivukai--sezemi-2015-readable-code/blob/master/method/json_loader.php#L2

``` php
/**
 * Jsonファイルをデコードする関数
 *
 * @param String $filename
 * @return array
 */
function json_load($filename){
```

変数が何が必要で、何を返すのかがわかる。

### 見つけた経緯

関数の機能を見た時に、何を渡す必要があるかを確認したときに、すぐに理解することができた。

## 変数タイプ命名

https://github.com/Asuforce/satoichiki-sezemi-2015-readable-code/blob/master/task/recipe.php#L2

``` php
    $recipe_array = array();
```

リストとわかるような変数名前付けがされている。

https://github.com/iLoiLohas/iLoiLohas-sezemi-2015-readable-code/blob/master/shiyou5/shiyou5.php#L5

``` php
$recipeContent  = file_get_contents($recipeJsonFile);
$recipeContentJson  = json_decode($recipeContent);
```

JSON のデータかどうかがわかるようにしている。

### 見つけた経緯

ファイルからロードされた文字列なのか、JSONデコードされたオブジェクトなのかをすぐに判断することができた。

**Comment by ghost** [comment]
### 名前

データソースが明らかなデータ取得処理

### 実際のコード

https://github.com/ayemos/ayemos-sezemi-2015-readable-code/blob/master/src/recipe/RecipeLoader.java#L36

``` java

    private static Set<RecipeModel> loadRecipesFromLocalXML(String path)

```

### どうしてリーダブルだと思っているかの説明

メソッド名だけで、どのデータソースからレシピ情報を読み出しているかが明白。
もし「XML」がないメソッド名だと、データソースが追加された場合、既存のメソッドに手を入れる選択肢しかなくなるが、
データソースが追加・変更になった場合に、別のメソッドとして実装すべきことを暗黙的に定義している点もマル。

### 経緯

ソース読んでて発見

**Comment by repeatedly** [comment]
プログラミング言語C島

---

## 実際のコード

https://github.com/ramesses2nd/tiwawan-sezemi-2015-readable-code/blob/20440ce7790f5a2d4d13a600c6f0be1fef02ce87/recipe.c#L13

``` c
/* コマンド引数の順序 */
#define CMD_MAX 4
#define CMD_DATA 2
#define CMD_TARGET 3
#define CMD_USER 1
```

## どうしてリーダブルだと思っているか？

ソースの中でマジックナンバーを使わずにどの部分の値を使っているかわかりやすい．名前にも`CMD`
というprefixがあり，どのための値かわかりやすくなっている．

**Comment by upinetree** [comment]
## 実際のコード

``` c
//TODO: バグがある
//例: recipe-data.txtを入れた時に発生
```

https://github.com/HirotakaTakayama/ramesses2nd-sezemi-2015-readable-code/blob/master/main.c#L47

## リーダブルな理由

既知のバグをに対して、適切なコメントをつけていると思いました。
実際の再現手順付きの役に立つコメントなのでリーダブルだと思いました。

**Comment by cesare** [comment]
## 開発言語

Ruby

## 実際のコード

https://github.com/hoshitocat/hoshitocat-sezemi-2015-readable-code/blob/master/task.rb#L24-L26

``` ruby
    recipes.each_with_index do |recipe, id| 
      puts "#{id + 1}: #{recipe}"
    end
```

## どうしてリーダブルだと思っているか？

ブロックの引数に `recipe`, `id` と、意味の分かる名前をつけているのが良い。それぞれ何を表しているのかが明確。(`#each_with_index` ブロックの引数ってどっちがどっちだっけ？となりがち)

## この書き方の一言説明

意味のわかる変数名

**Comment by jflute** [comment]
# 一言

readLine()の戻りが oneRecipe
https://github.com/yu1ro/yu1ro-sezemi-2015-readable-code/blob/master/src/Recipe.java#L11

```
        String oneRecipe = recipeBuff.readLine();
        while (oneRecipe != null) {
            System.out.println(oneRecipe);
            oneRecipe = recipeBuff.readLine();
        }
```

# どうしてリーダブルだと思っているか？

一行に一つのRecipeであることを明示している。
慣れてしまうと当たり前になってしまってなかなか one まで付けなかったりもするが、
特に「読み込んだファイルの仕様が不明なとき」には、とても愛おしい名前になる。

**Comment by suzukiyuichi** [comment]
## 実際のコード（またはURL）

https://github.com/NariyoshiChida/issei-sezemi-2015-readable-code/blob/master/assignment1/assignment1/main.cpp

## どうしてリーダブルだと考えたかの説明

関数名および変数名がすべて以下の記法で統一されている。

＜関数名＞
　１．　ロアーキャメル記法で統一
　２．　動詞＋目的語で統一

＜変数名＞
　１．スネークケースで統一

## 見つけた経緯（またはきっかけ）

見ていて

**Comment by okkez** [comment]
# 実際のコード

https://github.com/HirotakaTakayama/HirotakaTakayama-sezemi-2015-readable-code/blob/master/recipe.c#L5

# どうしてリーダブルだと考えたかの説明

与えることができる引数の個数を定数にしており、いくつの引数を処理できるかわかりやすかった。

# 見つけた経緯

リーダブルコードを探していたところ見つけることができた。

**Comment by redfigure** [comment]
## 名前

### [名は体を表す](https://github.com/Vetteru/Vetteru-sezemi-2015-readable-code/blob/master/recipe_managing_system.cpp#L10)

## 理由

関数が何をするかシンプルに表現している（英単語を省略しないのが好き）。

> void display_recipe_in_file_with_URL(char\* filename, int index = WILD_CARD){
> ...
> }

**Comment by mrkn** [comment]
Swif島

## 名前

責任と関心の分離

## 実際のコード

https://github.com/HSKKOU/orimomo-sezemi-2015-readable-code/blob/master/SEzemi/SEzemi/ViewController.swift#L19

## どうしてリーダブルだと考えたのかの説明

データファイルの入出力と UI に関するコードを分離し、それぞれに集中できるため。

## 見つけた経緯 (またはきっかけ)

ViewController.swift を読んでいるときに UI に無関係なファイル操作が出てこない事。

**Comment by repeatedly** [comment]
## 実際のコード

https://github.com/ramesses2nd/tiwawan-sezemi-2015-readable-code/blob/20440ce7790f5a2d4d13a600c6f0be1fef02ce87/recipe.c#L66
https://github.com/yudmo/mthiroshi-sezemi-2015-readable-code/blob/4b8dca71c1ffe35876c9b54c5e51879d87b93851/recipe.c#L13

``` c
  /* データファイルからfgets()でレシピ名を読み込む */
  while(recipe_num<MAX_RECIPE_NUM){
    if(!fgets(f_str[recipe_num], MAX_STR_LEN, f_recipe)){

      break;
    }else{
      recipe_num++;
    }
  }
```

## どうしてリーダブルだと考えたのかの説明

Cだと他の言語に比べて配列の要素数をとるのが面倒なので，あらかじめそれ用の変数を用意することで，後から見てもその変数を使えば実際に読み込めた数で処理出来るとわかりやすい．

**Comment by mumoshu** [comment]
# JavaScript + Node.js

## 名前

実装コードを読まなくても内容がわかる関数名

## 実際のコード

https://github.com/noopy05/Sesta-sezemi-2015-readable-code/blob/master/recipe3.js

``` javascript
var filePath = 'recipe-data.txt';
// (略)
var recipeData = readRecipeFromFile( filePath );
// (略)
function readRecipeFromFile( path )
```

## どうしてリーダブルだと思っているかの説明

関数名と引数名と合わせて英語のように読めて、実装を読まなくても何をしてくれる関数なのか過不足無く伝わるから。

「実装を読まなくても何をしてくれる関数なのかひと目で分かる」ような命名は、言語問わず大切だと思います。

## 見つけた経緯

上から順にコードを読んでいて、関数の実装コードにたどり着かなくても内容を理解できた・・後、関数の実装コードを読んでも理解に間違いがなかったとわかった・・というタイミングで、「これは命名がよかったからだ」と気づきました。
