### ISSUE TITLE
リーダブルコード筑波：メンターが紹介したいリーダブルなコード

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#20]
メンターは、全体に紹介したいリーダブルなコードをここにコメントしてください。

リーダブルなコードは参加者がグループ内で共有した中から選んでもよいですし、自分で参加者のコードを読んでいる中で見つけたものでも構いません。

紹介したいリーダブルなコードには少なくとも次の情報を含めてください。
この内容は各メンターが自分で紹介するので、アドリブでいろいろ話せるならここに書いておく内容はざっくりしたものでも構いません。ただし、コードを画面に表示させながら紹介するので、実際のコード（またはURL）は必ず書いてください。紹介するときは、これらの項目以外のことも話して構いません。
- 名前（またはタイトルあるいは一言説明）
- 実際のコード（またはURL）
- どうしてリーダブルだと考えたかの説明
- 見つけた経緯（またはきっかけ）

例:

``````
### 名前

自己記述的定数名

### 実際のコード

```c
exit(EXIT_FAILURE); /* エラーの場合は異常終了する */
```

### どうしてリーダブルだと考えたかの説明

コマンドの終了ステータスは、正常終了するときは`0`、異常終了するときは`0`以外の値を返すのが通例です。そのため、このコードは次のようにしても通例通りの動きになります。

```c
exit(1);
```

ただ、動くのは動きますが、`EXIT_FAILURE`という名前を使っている方が「失敗して終了するんだな」というのがわかりやすいのでリーダブルだと考えました。

なお、`EXIT_SUCCESS`というのもあるので、同様の理由で正常終了するときはそれを使うのがよいと思います。

### 見つけた経緯

ちゃんとエラー処理をしていて立派だなぁと思って読み進めたら異常終了することがわかりやすいコードだと気づきました。
``````

**Comment by sympe** [comment]
### 名前

変数名で何をしたいのかを語る

### 実際のコード

``` c
//idを指定して表示する（未実装）
void id_select_output
{
    FILE *p_recipe_file;
    FILE *p_id_file;
                :
```

### どうしてリーダブルだと考えたかの説明

実際にこの関数はまだ未完成で、p_id_fileというポインタ変数はまだ使われていない。しかし、p_id_fileという名前にすることで、idを指定する処理が必要であるということと、それがまだできていないことを変数名で語っている。

### 見つけた経緯

未実装の関数で、使われていない変数があったので、なんだろうと思ったときに見つけた。

**Comment by ug23** [comment]
### 名前

引数水先案内

### 実際のコード

`README.md` 内

``` txt
＜任意のレシピファイル、任意のIDを読み込む方法＞
・EclipseのRun→Run Configurations→ArgumentタブのProgram arguments欄に「ファイル名 見たいID」を書く
例：recipe-data.txt 2
・ウィンドウ右下のRunで実行すると指定したIDのレシピが出てくる
※IDを指定しなかった場合はすべてのレシピが出てきます
```

### どうしてリーダブルだと考えたかの説明

コマンドライン引数の編集方法は、IDEだと忘れがち。
（特に自分はよく忘れるので）
ちょうどそこが知りたかったんだ、ということまで書いてあったのがよい。
書いた人自身もそこで詰まって、メモに記したのかも。
引き継ぐ人への心遣いを感じる。
今回はeclipse同士で交換してもらったので特に効いたと思う。

### 見つけた経緯

どうやって実行するのか調べている間に。

**Comment by sesta** [comment]
## JavaScript

### 名前

変数の細分化

### 実際のコード

https://github.com/HirokiCHIBA/HirokiCHIBA-readable-code-tsukuba/blob/master/recipe.js

``` javascript
  var fileName = './recipe-data.txt';

  var httpObj = new XMLHttpRequest();

  // recipe-data.txtを非同期読み込み
  httpObj.open('GET', fileName, true);

  // 読み込み時に実行する関数の登録
  httpObj.onreadystatechange = function() {
    if (httpObj.readyState == 4) {
      var readText = httpObj.responseText;

      // 改行文字で分割し、1行ずつ配列に格納
      var recipes = readText.split('\n');
      var recipeDataArray = [];

```

### どうしてリーダブルだと考えたかの説明

文字列やオブジェクトを細かく変数に代入することで
変数の中身がシンプルでわかりやすい

### 見つけた経緯

``` javascript
  httpObj.open('GET', fileName, true);
```

などの処理を見たときに、
引数の内容が一目で分かった

**Comment by sesta** [comment]
## JavaScript

### 名前

改行の活用

### 実際のコード

https://github.com/Ruby1995/HirokiCHIBA-readable-code-tsukuba/blob/master/recipe.js

``` javascript
        recipeDataArray.push(recipeData);
        recipeKeys.push(i);

      }


      // IDによる検索
      targetId = window.prompt("IDを指定してください。");
      var recipeCount = recipeDataArray.length; // レシピの数

      for (var i=0; i<recipeCount; i++) {
```

### どうしてリーダブルだと考えたかの説明

処理の内容が変わる場所で
他の場所よりも多く改行を入れている。
これにより処理のまとまりがすぐに理解できる。

### 見つけた経緯

ファイルを開いた瞬間に
処理の切れ目がわかった

**Comment by sesta** [comment]
## JavaScript

### 名前

読み込むファイルの説明

### 実際のコード

https://github.com/Ruby1995/HirokiCHIBA-readable-code-tsukuba/blob/master/recipe.js

``` javascript
  httpObj.onreadystatechange = function() {
    if (httpObj.readyState == 4) {
      // txtファイルには
      // 1行目にはユーザー名
      // 2行目以降にレシピ情報
      var readText = httpObj.responseText;
```

### どうしてリーダブルだと考えたかの説明

ファイルを読み込むコードの中で
読み込む対象となるtxtファイルの内容を説明してくれているので
txtファイルを見に行かなくて済む

### 見つけた経緯

読み込む処理の最初に
コメントで記述されているため
すぐに目に入った

**Comment by akkiihs** [comment]
## JavaScript

### 名前

関数化およびパラメータの型を表示

### 実際のコード

``` javascript
// すべてのレシピを出力する関数
/**
 * @params allRecipe Array
 */
function allRecipeOutput(allRecipe) {
    var recipeLen = allRecipe.length;

    for (var i =0; i<recipeLen; i++) {
        console.log((i+1) + ":" + allRecipe[i].name + allRecipe[i].data);
    }
}
```

### どうしてリーダブルだと考えたかの説明

ある程度まとまりのあるコードを関数にして切り出すことで、関数が呼び出されたときに関数の中までコードを読まなくても関数名で、だいたい何をするのかが分かる。
パラメータの型が示されていると、JavaScriptでは型を意識して宣言することが少ないので、パラメータallRecipeはArray（配列）であることを意識しながらコードを読むことができる。

### 見つけた経緯

メインとなるコードを読んでいたときに、関数を呼び出しているようだったので気づいた。

**Comment by yudmo** [comment]
## 言語グループ:C

### 名前

未実装を素直に認めてリーダブル

### 実際のコード

``` c
//以下未実装
//id_select_output;
```

### どうしてリーダブルだと考えたかの説明

コメントアウトしたものを他の人が見た際に，なぜコメントアウトされているのか，消すべきなのかどうか等を考えてしまうため，理由が書いてあることで誤解をなくせる．

### 見つけた経緯

進捗をチェックしようした際に発見

**Comment by yudmo** [comment]
## 言語グループ:C

### 名前

グローバル変数名でリーダブル

### 実際のコード

``` c
#define RECIPE_LEN 100 //レシピタイトルの長さの最大文字数
```

### どうしてリーダブルだと考えたかの説明

定数を定義する際に変数名をすべて大文字にし，コメントをつけていてリーダブル
プログラムが複雑になるにつれて多くの変数が使用されるため，全て大文字にすることで他の変数を区別することが可能になり，コメントからその変数の目的がわかる．

### 見つけた経緯

上から読み進めて，2行目にあったから．

**Comment by mthiroshi** [comment]
## 言語グループ:Java

### 名前

for each文使うやつ

### 実際のコード

``` c
public void showRecipeNames() {
        for (Recipe recipe : recipeList.getRecipeList()) {
            System.out.println(recipe.getRecipeName());
        }
    }
```

### どうしてリーダブルだと考えたかの説明

for文の条件式がスッキリとしていて読みやすい。

### 見つけた経緯

自分があまり書き慣れていないので、目に止まった。

**Comment by mthiroshi** [comment]
## 言語グループ：Java

### 名前

変数名から目的がわかるやつ

### 実際のコード

``` c
boolean targetIDExists = false;
...
if(targetIDExists){
            if(id==targetID)System.out.println(id + " 料理名：" + recipeName + "　作り方：" + method);
        }
```

### どうしてリーダブルだと考えたかの説明

if文の条件式にこの変数名を入れることで、条件式の意味がわかりやすい。

### 見つけた経緯

if文を見ていてすぐに意味がわかったから。

**Comment by yudmo** [comment]
## 言語グループ:C

### 名前

関数名直感的でリーダブル

### 実際のコード

``` c
//コマンドライン引数の有無で場合分け
if(argc == 1) all_output();
else for(int select_id=1; select_id<argc; select_id++)
{
    select_output( atoi(argv[select_id] ) );
}
```

### どうしてリーダブルだと考えたかの説明

全てのレシピを表示するall_output()，選択されたものを表示するselect_output()という関数名を見ただけである程度の処理を想像することができ，リーダブル．

### 見つけた経緯

main関数内でコマンドライン引数による場合分けで，どのような処理を行っているかを見た際に，読みやすいなと感じた．

**Comment by mthiroshi** [comment]
## 言語グループ：Java

### 名前

メソッド名から何をするメソッドかわかるやつ

### 実際のコード

``` c
public static Recipe makeRecipeFromCSV(String line){
```

### どうしてリーダブルだと考えたかの説明

英語と同じように読める

### 見つけた経緯

メソッドの名前を見た

**Comment by hoshitocat** [comment]
### 名前

共通財産 :octocat: 

### 実際のコード

``` ruby
class Recipe
  def initialize(filename)
    @file = File.open(ARGV[0])   
    @recipes = []
  end

  def print_recipes_all
    @recipes.each do |recipe| 
      puts "#{recipe[:id]}: #{recipe[:name]} #{recipe[:recipe]}"
    end
  end

  def print_recipes_by_id(search_id)
    @recipes.each do |recipe|
      if search_id == id  
        puts "#{recipe[:id]}: #{recipe[:name]} #{recipe[:recipe]}"
      end
    end
  end

  def read
    @file.each_line.with_index(1) do |row, id|
      recipe = row.split(" ")
      @recipes.push({:id => id.to_i, :name => recipe[0], :recipe => recipe[1]})
    end
  end
end
```

### どうしてリーダブルだと考えたかの説明

再利用性が高く、各メソッド名とかinitializeメソッドを見ればすぐに分かると思いました。

### 見つけた経緯

書いているところを覗いたら見つけた😇

**Comment by kentya6** [comment]
## 言語グループ : Swift

### 名前

Nil Coalescing Operatorチョットデキル

### 実際のコード

``` swift
println(recipesDict[input] ?? "Not Found")
```

### どうしてリーダブルだと考えたかの説明

Nil Coalescing Operatorを使用しているので、冗長なコードにならずにまとまっており、それぞれの処理の流れが容易に把握できる。

もしNil Coalescing Operatorを使用しないと

``` swift
if recipesDict[input] != nil {
    println(recipesDict[input])
} else {
    println("Not Found")
}
```

のように記述する必要が出てしまう。

言語の演算子を適切に使用していていいなと思った。

### 見つけた経緯

ざっと読んでいて目に止まった。

**Comment by kentya6** [comment]
## 言語グループ : Swift

### 名前

Trailing Closure使用

### 実際のコード

``` swift
split(str) { contains("\n", $0) }
```

### どうしてリーダブルだと考えたかの説明

Swiftのsplitメソッドは、引数でクロージャを与えるけど、最後の引数がクロージャを渡すということで、trailing closureとして記述している。

これは[RayWenderlichのコーディング規約](https://github.com/raywenderlich/swift-style-guide)にも準拠していて、読みやすかった。
もしtrailing closureを使用しないと

``` swift
split(str, { contains("\n", $0) } )
```

のように記述することになる。

※ 今回はクロージャ部分の処理が1行だが、これが複数行になったときに最後の括弧の位置が把握しにくくなる。

### 見つけた経緯

ざっと読んでいて目に止まった。

**Comment by hoshitocat** [comment]
### 名前

IDとご一緒に！ :octocat: 

### 実際のコード

``` ruby
file.each_line.with_index(1) do |recipe, id|
```

### どうしてリーダブルだと考えたかの説明

`file.each_line` ファイルから一行ずつ取得するときに `with_index(1)` インデックスの番号（スタートは１から）も取得しますってことが一目で分かると思いました。

### 見つけた経緯

こんな書き方あるんだと思って見つけました。知らない書き方していたので勉強になりました 😇

**Comment by ghost** [comment]
# C++

### 名前

プライベートは隠したい

### 実際のコード

``` c++
private:
    recipeNode(); // 空のレシピを作りたくないので、デフォルトコンストラクタを隠蔽
protected:
    std::string name = std::string();
public:
    std::string const& getName() const{
        return name;
    }
    void setName(std::string const& nameOfCuisine) {
        name = nameOfCuisine;
    }
    void print(std::ostream & os) const {
        os << name;
    }
```

### どうしてリーダブルだと考えたかの説明

public/protected/privateでも良いところを、privateを最初に持ってくることで
privateでいいものは絶対privateにしたいという強い意志を感じました。
コメントなしでも作者の雰囲気がわかるのでリーダブルだと考えました。

### 見つけた経緯

自分は普段public/protected/privateで書くことが多いので、すぐに見つかりました。

**Comment by sympe** [comment]
# C言語

### 名前

こまめな空白を忘れない

### 実際のコード

``` c
fp = fopen( fname, "r" );

    if( fp == NULL ){  //ファイルオープンエラー処理
      printf( "%sファイルが開けません\n", fname );
      return;
    }

    while( (fgets( recipe_title, RECIPE_LEN, fp )) != NULL ){
      id++;
      printf( "%d. %s", id, recipe_title );
    }
    fclose( fp );
```

### どうしてリーダブルだと考えたかの説明

ついつい忘れてしまいがちな()の中身の半角スペースを忘れずに
つけているので中身がとても見やすい

### 見つけた経緯

見やすかったので

**Comment by suiyujin** [comment]
# Ruby

### 名前

リーダブルメソッド

### 実際のコード

https://github.com/himkt/nkmrya-readable-code-tsukuba/blob/50c8db07866265f178491a7e7536cc84dd8f8956/app.rb#L3-5

``` ruby
def show_recipe(recipe, id)
    puts "#{id}: #{recipe["name"]} #{recipe["description"]}"
end
```

### どうしてリーダブルだと考えたかの説明

recipeというハッシュを使うことで、
このメソッドだけ見ても何を出力しているのか分かりやすい

### 見つけた経緯

最初に書かれているメソッドだったので読んでみたら、
このメソッドだけ読んでも分かりやすいということに気づきました。
