### ISSUE TITLE
OSS Hack Weekend：OSS開発参加に関してメンターが意識していること

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#23]
OSSの開発参加にあたってメンターが意識していることがあったらコメントに概要を書いてください。参加者に紹介してもらいます。

アドバイスというよりも、自分はこうしている参考にするかどうかは参加者が考えて、くらいの方が参加者がいろいろ考える機会を奪わなくて（鵜呑みにしなくて）いいんじゃないか。

**Comment by okkez** [comment]
まず最初はテストがあれば、テストを動かすようにしています。
失敗しているものがあれば、それを直すところから始めるようにしています。

**Comment by okkez** [comment]
プロジェクトごとの流儀に合わせるために、そのプロジェクトのドキュメントを読むようにしています。
