### ISSUE TITLE
OSS Hack Weekend：ふりかえりをしてメンターが印象に残った他の参加者に共有したいこと

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#24]
参加者とふりかえりをする中でメンターが印象に残ったことのうち、他の参加者に共有したいことをコメントに書いてください。1日目の最後（かどこか）で全員に共有する機会を作ります。

メンター自身に紹介してもらうので自分が思い出せれば一言二言で構いません。

**Comment by piroor** [comment]
いろんなやり方があるとき、どんなやり方を検討して、それぞれにどんなメリットとデメリットがあるのか考えたということが記録に残っていると、最終的な選択の妥当性を判断する材料になると同時に、同じことで悩んでいる人や将来の自分のための情報提供にもなるのではないか。

**Comment by nabedge** [comment]
OSSはその歴史が古いほど「既にどこかで誰かが使っている」ものです。
そのため、既存のメソッド（それがイケてないメソッド名とかであっても）を
うっかり治すと、既にそのOSSを使っている誰かのアプリが
コンパイルエラーを起こすかもしれません。
そういう場合は、既存のメソッドを治すよりも、新たなメソッド名で追加するほうがよいかもね。

**Comment by piroor** [comment]
issueを登録しておいたら作者の人が先に直してしまった、という時もそれを今後に活かす事が大事。
- 自分の案と比較することで、自分の案が本当に妥当だったのか、他にもっと良い直し方があったのか、を確認できる。
- アドホックな対応に終わったコミットだったなら、根本的対応のためのプルリクエストの余地はある。

**Comment by piroor** [comment]
英語の文章を考える時は、難しく考えないほうがいい。

**Comment by tnakamoto-cosylab** [comment]
> 英語の文章を考える時は、難しく考えないほうがいい。
+1

**Comment by rust** [comment]
すべてを一回で解決しないでもいい、ということは念頭においておいたほうがいい。

**Comment by tnakamot** [comment]
コミットする前にdiffして確認するという作業が出来ている学生がいてとても良かった。

Gitのドキュメントではないのですが、Subversionというバージョン管理システムの[ドキュメント](http://svnbook.red-bean.com/en/1.7/svn.tour.cycle.html#svn.tour.cycle.examine)にこんなことが書かれているので、ぜひ全ての学生さんに参考にしてもらいたいです。

> Once you've finished making changes, you need to commit them to the repository, but before you do so, it's usually a good idea to take a look at exactly what you've changed. By examining your changes before you commit, you can compose a more accurate log message (a human-readable description of the committed changes stored alongside those changes in the repository). You may also discover that you've inadvertently changed a file, and that you need to undo that change before committing. Additionally, this is a good opportunity to review and scrutinize changes before publishing them.

**Comment by okkez** [comment]
1つエラーを解決して、次のエラーで詰まったとしても、できたことと、できなかったことを報告しておくことが重要です。
できたところまでを報告することで、他の人がアドバイスしてくれたり、続きをやってくれたり、未来の自分の役に立ったりする。

**Comment by tatsuosakurai** [comment]
紙とかに図を描きながらやっている人が数人いましたが、考えやすくなったり、相談しやすくなったり、議論しやすくなるので、とてもいいなーと思いました:)
