### ISSUE TITLE
OSS Hack Weekend: HSKKOU: SwiftHTTP: Swift: 作業ログ

### ISSUE THREAD

**Issue by HSKKOU** [clear-code/sezemi-2015#25]
SwiftHTTP：https://github.com/daltoniam/SwiftHTTP

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by HSKKOU** [comment]
### 0.事前に準備しているときに詰まったところ

---

#### 思ったこと
- cocoapodsでプロジェクトに入れたが、これでPullRequestを出すにはどうするのか？
- ~~Podsのプロジェクトが自分のプロジェクトに入っていない~~
  - 解決済：Podsのインストールで違うプロジェクトが生成されているからそっちを使う
- ~~Podsには入れたが、動かない！？~~
  - 解決済：入れたPodsのBuildをしていなかった

備考

**Comment by HSKKOU** [comment]
### 作業1. RESTful APIに存在しないメソッドを投げた

---

#### 思ったこと
- printlnででるerrorの種類が少なすぎて何のエラーが出ているのかわからない

**Comment by HSKKOU** [comment]
### 作業2. HTTPTask.swiftのHTTPOperationクラスを読んで

---

#### 思ったこと
- StatusとなるものがStringで書かれていたのでenumにまとめたい

**Comment by HSKKOU** [comment]
### 作業3. プロジェクトにあるテストを便利にする

---

#### 思ったこと
- テストの数が少なくて実際に動くか不安
  - GET, Authentication, OparationQueueのテストのみ
- テストの柔軟性が悪く、様々なテストができない
  - 既存のテキトーなWebサイトのURLにHTTPRequestを投げていて、自分のAPIをテストするには先にAPIの実装が必要

---

#### 解決方法
- アプリ内でテストを完結できるようにする
  - OHHTTPStubsのライブラリを用いて仮想APIを実行プロジェクト内に作成し、様々なResponseを返すことができるようにする

---

#### 進捗
- [x] OHHTTPStubsをプロジェクトに追加する
- [x] 簡単な方法でOHHTTPStubsでHTTPRequestを乗っ取れるようにする
- [x] OHHTTPStubsによる仮想APIで、ダミーResponseやエラーResponseを返せるようにする
- [x] 柔軟なテストケースを考える
- [x] ↑を実装する

**Comment by HSKKOU** [comment]
### 作業4. 自分のWiFiルーターを用いてTestを実行した

---

#### 起きたこと
- WiFiの速度が制限されていて、下のように設定されている時間内にテストが完了せず、タイムアウトした。

``` swift
waitForExpectationsWithTimeout(30, handler: nil)
```

---

#### 思ったこと
- 全部30秒でタイムアウトするように設計されているが、テスト上にグローバル定数でタイムアウト時間を設定しておいた方がよいのでは？

---

#### 追記（7/12）
- 落ち着いて考えてみたら、テスト自体は各テスト内容によって処理時間が変わるのでそのテストごとに時間を設定するべきだと思った。

**Comment by gfx** [comment]
テストのタイムアウトですが、基本HTTP clientはすべてmock （OHHTTPStub）でするのが正しくて、実際のURLにアクセスするのはよくないです。なので、理想的にはtimeout値は1秒くらいで十分なんですよね。

その意味では、30secから1secに変更しやすいように、定数にしておくというのはいい考えです。

**Comment by HSKKOU** [comment]
とりあえず、SwiftHTTP作者が作ったTestコードは触らずに新しくTestファイルを生成して
自分の作ったTestコードと、作業４のことについてを書き足しました

**Comment by HSKKOU** [comment]
gfxさんの指示のように、別ファイルで作ることはやめてあくまで作者のテストコードそのものを修正する方針に変更しました。

**Comment by HSKKOU** [comment]
### 作業5. OHHTTPStubsでauthenticationをシミュレートする。

---

#### 起きたこと
- OHHTTPStubs内で認証処理を実現するものがなく、自分で実装するしかなかった。
- HTTPTaskでauthの登録はできるが、authenticationの処理自体はdelegateで実装されているのでテストしにくい（仕方ないのか？）

---

#### 思ったこと
- 認証処理は複雑で難しい
- 各テストケースで分割してPRを送るのもいいかも

**Comment by HSKKOU** [comment]
### 作業6. PRする

---

#### メッセージ

  Your project's tests access existing web service. So, first, I update the methods "testGetRequest" in test file to access virtual API by using OHHTTPStubs.（https://github.com/AliSoftware/OHHTTPStubs）
  And I try to send PR about other test methods.
  Please install OHHTTPStubs by CocoaPods to Tests.

**Comment by HSKKOU** [comment]
https://github.com/HSKKOU/SwiftHTTP
にpushしました

**Comment by gfx** [comment]
(1) なにが良くなくてどうなおそうとしたのか書くほうがよい
(2) 英文法の修正

Your project's tests access existing web services but I think it's not a good idea, so I've fixed `testGetRequest()` to use [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs) in order to mock HTTP requests. Please install OHHTTPStubs by CocoaPods to run tests.

If you welcome this pull-request, I'd like to add more tests which use OHHTTPStubs.

こんなんでどうでしょ。

**Comment by HSKKOU** [comment]
### 作業7. PRする（２回目）

---

#### どんなPR？

project: https://github.com/HSKKOU/SwiftHTTP/tree/AddTests_OHHTTPStubs_OperationQueue
- 前回のはシンプルなHTTPRequestのテストだったが、今回は複数のHTTPRequestを処理するOperationQueueについてのテストにOHHTTPStubsを適応させた。

---

#### 思ったこと
- OHHTTPStubsのOHHTTPStubsResponseのクラス自体に

``` swift
requestTime(requestTime: NSTimeInterval, responseTime: NSTimeInterval)
```

というRequestとResponseにかかる時間を指定するmethodがあったので簡単にできた。

---

#### PRのメッセージ案

I sent a PR some time ago. I could also apply [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs) to the method `testOperationQueue()`.

If you welcome this pull-request, I'd like to add more tests which use OHHTTPStubs.
