### ISSUE TITLE
OSS Hack Weekend: makky3939: React: JavaScript: 作業ログ

### ISSUE THREAD

**Issue by makky3939** [clear-code/sezemi-2015#26]
https://github.com/facebook/react

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by makky3939** [comment]
- 作業：インストールを始めた
- 思っていること：ドキュメント通りに進めれば大丈夫だろう

**Comment by makky3939** [comment]
- 作業：ビルド出来た
- 思っていること：インストールじゃなくてビルドだった

**Comment by makky3939** [comment]
- 作業：手元でテストが通った
- 思っていること：

**Comment by makky3939** [comment]
- 作業：ドキュメントを読む
- 思っていること：タイポがある

過去のPRを読んでた

備考
https://github.com/facebook/react/commit/e6832b51365b269f25d40b3a2eeed3e603a4fb7c
（docs/docs/09-tooling-integration.ja-JP.md）
のL9の
`ビルドたりデプロイするのに`
が
`ビルドしたりデプロイするのに`
の誤りだと思われる

**Comment by makky3939** [comment]
- 作業：サンプルコードを読む
- 思っていること：HTML5の書き方じゃない？

備考
https://github.com/facebook/react/blame/master/examples/basic-jsx-external/index.html#L4
の
`meta http-equiv='Content-type' content='text/html; charset=utf-8'`
が
`meta charset='utf-8'`
の方が簡潔なのではないか

**Comment by makky3939** [comment]
- 作業：サンプルコードを読む
- 思っていること：

備考
https://github.com/facebook/react/blob/master/examples/jquery-bootstrap/index.html#L17
scriptタグに
`type="text/javascript"`
って付けなくても良いのでは

**Comment by makky3939** [comment]
- 作業：sourceを読む
- 思っていること：

https://github.com/facebook/react/blob/master/src/shared/utils/ReactErrorUtils.js#L25
のnameって何に使われてるんだろう

このコードが使われている他のコードも確認する

**Comment by makky3939** [comment]
- 作業：なんとなくgulpのソースを読む
- 思っていること：

https://github.com/gulpjs/gulp-util/blob/master/lib/template.js#L16
は長すぎるのでif以下の処理はネストした方が良いのでは

同じような箇所がないか確認

**Comment by makky3939** [comment]
- 作業：なんとなくgulp-webserverを読む
- 思っていること：

https://github.com/schickling/gulp-webserver/blob/master/src/index.js#L59

は

```
} else {
  return true;
}
```

の方が読みやすいのではないか

同じような箇所がないか確認

**Comment by makky3939** [comment]
- 作業： Reactをフォークした

**Comment by makky3939** [comment]
https://github.com/clear-code/sezemi-2015/issues/26#issuecomment-120562467
- 作業：PRを作った

https://github.com/facebook/react/pull/4346
- 結果：マージされた

**Comment by makky3939** [comment]
https://github.com/clear-code/sezemi-2015/issues/26#issuecomment-120562615
- 作業：
- [x] Issueを作る
- [x] 確認してもらう

**Comment by makky3939** [comment]
https://github.com/clear-code/sezemi-2015/issues/26#issuecomment-120562884
- [x] 本家をpull（http://qiita.com/xtetsuji/items/555a1ef19ed21ee42873）
- [x]  `type="text/javascript"`を削除
- [x] push
- [x] PR作成
- [x] PR内容確認

**Comment by makky3939** [comment]
https://github.com/clear-code/sezemi-2015/issues/26#issuecomment-120563865
- [x] なんでnameを引数に取るのか調べる
- 理由：デバック用に宣言されていることが判明（コメントより

将来的にguard関数の実装が行われた際にname引数を使用すると考えられるため、修正作業は行わない

**Comment by makky3939** [comment]
https://github.com/clear-code/sezemi-2015/issues/26#issuecomment-120564637
- [x] コードの修正
- [x] Push
- [x] PR作成
- [x] PR確認

**Comment by makky3939** [comment]
https://github.com/clear-code/sezemi-2015/issues/26#issuecomment-120564920
- [x] コードの修正
- [x] Push
- [x] PR作成
- [x] PR確認（説明を修正）

**Comment by kohei-takata** [comment]
Reactに立てたIssueにコメントが返ってきてますね！PRもマージされたようで良かったです :+1:

**Comment by makky3939** [comment]
- 作業：電車の中で時間つぶし
- 思ったこと

早い
https://github.com/facebook/react/blame/master/docs/docs/03-interactivity-and-dynamic-uis.ja-JP.md#L50

BS
https://github.com/facebook/react/blame/master/docs/docs/07-forms.ja-JP.md#L80
https://github.com/facebook/react/blame/master/docs/docs/08.1-more-about-refs.ja-JP.md#L147
https://github.com/facebook/react/blame/master/docs/docs/10-addons.ja-JP.md#L22

Fluxにも type=‘text/javascript’があった
https://github.com/facebook/flux/blob/ac1e4970c2a85d5030b65696461c271ba981a2a6/website/core/Site.js#L25

**Comment by kohei-takata** [comment]
僕の翻訳したドキュメントに誤りがあるみたいですみません！
ぜひ修正してください！
あと2つPRがマージされたら、Reactのコントリビュータ一覧に名前が載りそうですね :)

**Comment by makky3939** [comment]
meta charset https://github.com/clear-code/sezemi-2015/issues/26#issuecomment-120573596
- [x] コード修正
- [x] Push
- [x] PR作成
- [x] PR確認

**Comment by makky3939** [comment]
hubコマンドでissueからPRを作るのは非推奨になったらしい

```
Warning: Issue to pull request conversion is deprecated and might not work in the future.
```

**Comment by makky3939** [comment]
typo https://github.com/facebook/react/blame/master/docs/docs/03-interactivity-and-dynamic-uis.ja-JP.md#L50
- [x] コード修正
- [x] Push
- [x] PR作成
- [x] PR確認

**Comment by makky3939** [comment]
controll character
https://github.com/facebook/react/blame/master/docs/docs/07-forms.ja-JP.md#L80
https://github.com/facebook/react/blame/master/docs/docs/08.1-more-about-refs.ja-JP.md#L147
https://github.com/facebook/react/blame/master/docs/docs/10-addons.ja-JP.md#L22
- [x] コード修正
- [x] Push
- [x] PR作成
- [x] PR確認

コミットは１つにまとめた

**Comment by makky3939** [comment]
- 作業：ふとSublime textで使用しているThemeのrepositoryを見る
- 思ったこと：READMEにタブ文字が混入

https://github.com/makky3939/material-theme/blame/master/README.md#L69

**Comment by makky3939** [comment]
READMEにタブ文字が混入 https://github.com/clear-code/sezemi-2015/issues/26#issuecomment-120683362

https://github.com/makky3939/material-theme/blame/master/README.md#L69
- [x] コード修正
- [x] Push
- [x] PR作成
- [x] PR確認

**Comment by makky3939** [comment]
Fluxにも type=‘text/javascript’があった
https://github.com/facebook/flux/blob/ac1e4970c2a85d5030b65696461c271ba981a2a6/website/core/Site.js#L25
- [x] コード修正
- [x] Push
- [x] PR作成
- [x] PR確認

**Comment by makky3939** [comment]
https://facebook.github.io/react/tips/self-closing-tag.html の日本語訳を作る
- [ ] 訳
- [ ] Push
- [ ] PR作成
- [ ] PR確認

**Comment by makky3939** [comment]
フィードバック：
- ログが見やすい（チェックボックスが分かりやすい
- 曖昧な箇所をPR出す前にissueで確認している
- マージされている
