### ISSUE TITLE
OSS Hack Weekend: shin-taro: twitter4j: Java: 作業ログ

### ISSUE THREAD

**Issue by nabesh1n** [clear-code/sezemi-2015#28]
https://github.com/yusuke/twitter4j/

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by nabesh1n** [comment]
- 作業：インストール
- 思っていること：とりあえず http://qiita.com/takke/items/888af6628e01de722a16 を参考に進めてみる

**Comment by nabesh1n** [comment]
- 作業：インストールが失敗した
- 思っていること：依存関係に問題がある？

備考：エラーメッセージは次の通り

``` text
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building twitter4j-stream 4.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.twitter4j:twitter4j-core:jar:4.0.5-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.twitter4j:twitter4j-async:jar:4.0.5-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.492 s
[INFO] Finished at: 2015-07-11T10:43:10+09:00
[INFO] Final Memory: 7M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project twitter4j-stream: Could not resolve dependencies for project org.twitter4j:twitter4j-stream:jar:4.0.5-SNAPSHOT: The following artifacts could not be resolved: org.twitter4j:twitter4j-core:jar:4.0.5-SNAPSHOT, org.twitter4j:twitter4j-async:jar:4.0.5-SNAPSHOT: Could not find artifact org.twitter4j:twitter4j-core:jar:4.0.5-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by nabesh1n** [comment]
- 作業：インストールが出来た
- 思っていること：各モジュールディレクトリでビルドする前にルートディレクトリでビルドしたらインストールできた

**Comment by nabesh1n** [comment]
- 作業：とりあえずTwitter4jを使ってみる
- 思っていること：TwitterTestというプロジェクトを作成し、コードサンプル http://twitter4j.org/ja/code-examples.html を実行してみる

**Comment by nabesh1n** [comment]
- 作業：とりあえずTwitter4jを使ってみた
- 思っていること：TwitterTestプロジェクトでRunしたらasyncについてUnsupportedExceptionを返された
  MainでRunしたらビルドされて動いた

**Comment by nabesh1n** [comment]
- 作業：自分のアカウントのタイムラインを取得する
- 思っていること：なぜかtwitter4jのアカウントでタイムライン取得をしていたのでtwitter4j.propertiesの中身を修正し、配置場所も修正したところ自分のアカウントで開けた。

**Comment by nabesh1n** [comment]
- 作業：Mavenプロジェクトで実行するようにした
- 思っていること：Mavenの方が動かしやすいと思った

**Comment by nabesh1n** [comment]
- 作業：自分のtwitter4jに依存するようにする
- 思っていること：pom.xmlからtwitter4jへの依存をなくして、ローカルでコンパイルして生成されたjarをそのままルート直下に配置すると動いた

**Comment by nabesh1n** [comment]
- 作業：試しにissueが立てられている内容に挑戦
- 思っていること：http://issue.twitter4j.org/youtrack/issues/TFJ に立てられているissueの内容に挑戦しよう

**Comment by nabesh1n** [comment]
- 作業：JavaDocの修正issueをやる
- 思っていること：超簡単な内容だけどまずはプルリクしよう

**Comment by nabesh1n** [comment]
- 作業：警告が出ている箇所の改善に取り組む
- 思っていること：Java5と互換性を持つ範囲で修正できるかどうかを確認しつつ取り組む

**Comment by nabesh1n** [comment]
- 作業：getRetweetCount()の返り値の型をlongではなくintにする
- 思っていること：getFavoriteCount()の返り値の型はintとなっており、retweet数の数値の大きさとしてもintの方が正しいと思われる。またissueが立てられていることでもあるため、この部分を修正してプルリクを出すことは良さそう。

**Comment by gfx** [comment]
> getRetweetCount()の返り値の型をlongではなくintにする

いやそれはどうでしょう。ちょっとtwitter APIの知識なしの状態での横槍で申し訳ないですが、その値ってもともと [JSON number type](https://tools.ietf.org/html/rfc7159#section-6) ですよね。これをJavaの整数で表現するのであればlongが正しいです。retweet数だから32bit intの範囲だろうと考えるのは間違いだと思います。

**Comment by nabesh1n** [comment]
- 作業：exampleを増やしてみる
- 思っていること：coreには実装されているけどexpamleがない機能を見つけてexampleの実装を試みる
