### ISSUE TITLE
OSS Hack Weekend: HirotakaTakayama: stepmania: C++: 作業ログ

### ISSUE THREAD

**Issue by HirotakaTakayama** [clear-code/sezemi-2015#32]
https://github.com/stepmania/stepmania
https://github.com/arduino/Arduino

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by HirotakaTakayama** [comment]
- 作業：forkしてインストールして実行
- 思っていること：ゲームをダウンロードしてきて遊んだことしか無いし、インストールドキュメント見当たら無いし不安

**Comment by HirotakaTakayama** [comment]
・作業：インストールして実行
・思っていること：Installing from Sourceにて、Buildフォルダを見ろって書いてあった。

**Comment by HirotakaTakayama** [comment]
・作業：インストールして実行（at README.md）
・思っていること：Build/README.mdをみたら、CMake Installationとされていたが、CMakeが入っていなかった。

```
-bash: cmake: command not found
```

・備考：各環境でのCMakeインストール方法から書いた方が良いと思う。Mac OS Xであれば、

```
$brew install cmake
```

**Comment by HirotakaTakayama** [comment]
・作業：インストールして実行（at README.md）
・思っていること：
https://github.com/HirotakaTakayama/stepmania/tree/master/Build#cmake-command-line 
が、CMake使っていない身だととても分かりづらい。サンプルが欲しい。

・備考：{YourGeneratorHere}にて、例えば選択肢からXcodeを選択した例をつけたい。

```
$ cmake -G Xcode .. && cmake ..
```

**Comment by HirotakaTakayama** [comment]
・作業：インストールして実行（at INSTALL.md）
・思っていること：
https://github.com/HirotakaTakayama/stepmania/blob/master/Build/INSTALL.md#mac-os-x
で、Using Xcode, simply build in Xcode and it will place the .app file in the correct directory. と書いてあるが、Buildフォルダ下に.xcodeproj というプロジェクトファイルが出来ていることをREADME.md側で書いておいた方が親切。

・備考
README.md側に追記して欲しい文章を考える感。

**Comment by HirotakaTakayama** [comment]
・プルリクエストログ（Add information: Build/README.md. #719）
日本語：cmakeコマンドを私の環境でインストールしておらず、初めに使うことが出来なかったので、各プラットフォームにおいて、cmakeインストールに関する記述が必要だと思いました。
ここでは私の環境がMac OS Xであるため、Mac OS Xにおいてcmakeインストールの方法について書きました。また、Windows、Linuxについても記述が必要だと思います。
英語：https://github.com/stepmania/stepmania/pull/719

**Comment by HirotakaTakayama** [comment]
・プルリクエストログ（Add example information: Build/README.md. #720）
日本語：https://github.com/stepmania/stepmania/tree/master/Build#cmake-command-line において、cmakeを使う時に、使い方が解りづらかった為、コマンド実行の例を記述した。
これを追加することで、CMake Installationがより円滑に行えることを期待する。
英語：I described cmake command execution because it's difficult to understand how to use.
By add this sentence, I expect that all of people can more easily to do CMake Installation.

**Comment by HirotakaTakayama** [comment]
・プルリクエストログ（Fix mistranslation in one line: Themes/_fallback/Languages/ja.ini #721）
日本語：Advanced Optionsの日本語バージョンにおいて、LIFE DIFFICULTYの説明にミス翻訳があったため修正。
英語文は「Increase this value to cause your life meter to drain faster and refill slower.」である。
このミス翻訳が直らないと、ユーザーがゲームクリアの為にゲームが簡単になることを期待してLIFE DIFFICULTYを上げたら、期待した動作にならず、困惑するかもしれない。
英語：I fixed mistranslation of explanation LIFE DIFFICULTY in Advanced Options Japanese version.
The English sentence is "Increase this value to cause your life meter to drain faster and refill slower".
When some user changes to increase LIFE DIFFICULTY for easier to expect clear the game, they will confuse.

Pull Request メモ：
・よく使われる言い回し
「期待した動作にならない」expected
「困惑させる」confuse

**Comment by HirotakaTakayama** [comment]
- 作業：OSSプロジェクトのコミット状況を眺める
- 思っていること：2010年辺りから開発がホットになってきている。2011年~2012年にかけて沢山コミットされており、その時程ではないが今でも活発的に活動されている。Pull Requestはcloseされたものも含め合計で400ぐらいあり、Issueも300ぐらい発行されている。

**Comment by hanubeki** [comment]
>LIFE DIFFICULTYの説明にミス翻訳
5.0 beta 3以前はLifeDifficultyの設定がLifeDifficultyScale表記(ライフの回復量、つまり大きい方が易しい)だったのが
5.0 beta 4にて3.9と同じ表記(大きい方が厳しい)になったのでこのようなことになったかと思います。
https://github.com/stepmania/stepmania/commit/4cf4e30bb98d0b865b4c6d34f884e58ee9aaadd3

**Comment by HirotakaTakayama** [comment]
ありがとうございます！そうなんですね、わかりました。

**Comment by hanubeki** [comment]
すいません、コメントを削除してしまったのでもう一度。

> LIFE DIFFICULTYの説明にミス翻訳

5.0 beta 3まではLifeDifficultyScale(ライフの回復量=大きいほど易しい)だったのが、
5.0 beta 4から3.9と同じ(大きいほど厳しい)になったのでこのようなことになったかと思われます。
参考: https://github.com/stepmania/stepmania/commit/4cf4e30bb98d0b865b4c6d34f884e58ee9aaadd3

**Comment by HirotakaTakayama** [comment]
:+1:

**Comment by HirotakaTakayama** [comment]
---

作業：2番目にやりたいと思っていたOSS（arduino）を対象とする。forkしてインストール。
思っていること：一番やりたいと思っていたOSSへコントリビュート出来た。ここからのコントリビュートはコードをしっかり読む必要が出る為、時間制限の都合上、2番目にやりたいと思っていたOSS（arduino）を対象とする。OSSコントリビュートの方法について学べたので、次に興味のあったarduinoを対象として開発環境を整える。

**Comment by HirotakaTakayama** [comment]
作業：arduinoの開発スタイルについて読む
思っていること：報告の仕方について理解した。簡単なバグや変更は、issue発行。複雑なものであれば、developerメーリングリストにて議論する。

**Comment by HirotakaTakayama** [comment]
作業：arduinoの開発者としてのインストールとビルド
思っていること：Installationに" Detailed instructions are in reference/Guide_Windows.html and reference/Guide_MacOSX.html "とあるが、どこか分からない。build/howto.txtに書いてあるURL（https://code.google.com/p/arduino/wiki/BuildingArduino ）の内容を参照すれば良いように思える。

**Comment by HirotakaTakayama** [comment]
作業：arduinoの開発者としてのインストールとビルド
思っていること：antコマンド入っていない！ install Apple's Developer Tools経由で取れるかもしれないけどコマンドベースで整えたい。

備考：$brew install ant でバイナリは拾える。ただし、以下のようになる。
$ant -version
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
No Java runtime present, requesting install.

**Comment by HirotakaTakayama** [comment]
- 作業：arduinoの開発者としてのインストールとビルド
- 思っていること：Java SE Development Kitをインストールすればantコマンド使用可能。ビルド成功。

$ant -version

Apache Ant(TM) version 1.9.5 compiled on May 31 2015

$brew -v

Homebrew 0.9.5

**Comment by HirotakaTakayama** [comment]
- プルリクエストログ（[Manual] Can't find reference/Guide_Windows.html and reference/Guide_MacOSX.html in README.md）

-日本語：
README.mdに書いてあるInstallationのreference/Guide_MacOSX.html というファイルが見つからなかった。
Detailed instructionsは、https://github.com/arduino/Arduino/wiki/Building-Arduino に書かれている内容では？

-英語：
README.md needs to be updated. 
Because I can't find reference/Guide_MacOSX.html file on README.md. 
Is the installation page "https://github.com/arduino/Arduino/wiki/Building-Arduino"?

This text should be changed:

```
Detailed instructions are in reference/Guide_Windows.html and reference/Guide_MacOSX.html. 
For Linux, see the Arduino playground: http://www.arduino.cc/playground/Learning/Linux
```

I recommend replacing it with this:

```
Detailed instructions are in https://github.com/arduino/Arduino/wiki/Building-Arduino
```

**Comment by HirotakaTakayama** [comment]
- 作業：日本語訳の追加
- 思ったこと：.po翻訳ファイルの編集をすることで日本語翻訳追加可能？日本語版は8割方は日本語だが、一部に英語が残っている。
- 備考：emacsでpoファイル編集したら壊れた。poeditなど、poファイル編集専用エディタで編集するべきか。
  また、更新にはビルド以外にupdate.shの実行が必要か？
  必要であればマニュアルのどこかに記載した方が良い。

**Comment by gfx** [comment]
- 貢献できそうなところをサクっと見つけて着手したのはとてもよいと思います
- 翻訳リソースはメンテが難しいので、先方がメンテできそうか確認してから作業しはじめてもよかったですね。今回はメンテできそうなのでよいと思います。

ぼくからは以上です！

**Comment by HirotakaTakayama** [comment]
- 2日間の感想

バグを直したいと思っていたプロジェクトにコントリビュートし、直すことが出来た為、非常に満足出来るイベントだった。
OSSチョットデキル自信がついた。これからもコントリビュートしていきたい。
