### ISSUE TITLE
OSS Hack Weekend: pyonnuka: redmine: Ruby: 作業ログ

### ISSUE THREAD

**Issue by pyonnuka** [clear-code/sezemi-2015#36]
https://github.com/redmine/redmine

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by pyonnuka** [comment]
- 作業：ログイン
- 思っていること：アカウント作成後にシステム管理人からの認証が必要らしい。rake taskで認証すればいいのかな？？

**Comment by pyonnuka** [comment]
- 作業：ログインできた
- 思っていること：引き続きいろいろ機能いじってみよう

**Comment by pyonnuka** [comment]
- 作業：公式ドキュメントに書かれているconfig/email.yml.exampleが存在しない
- 思っていること：config/configuration.yml.exampleに改名した？

**Comment by pyonnuka** [comment]
- 作業：日本語ドキュメントに沿ってインストールしてたけどやめた
- 思っていること：ファイルの名前とかも合ってないし、信頼性なさそう

**Comment by pyonnuka** [comment]
- 作業：テスト回すための初期設定する
- 思っていること：いつも通りのrailsの設定でいけそう

**Comment by pyonnuka** [comment]
- 作業：テスト回してる
- 思っていること：ユニットテストの量めちゃくちゃあるからSKIPした方がよさそう。エラー出てるところに対してユニットテスト回す方針でいこう。

**Comment by pyonnuka** [comment]
- 作業：テストでエラーでた
- 思っていること：データベース周りのことドキュメントに書かれてないか一度確かめてみよう

備考：エラーは以下の通り

``` text
IssueNestedSetConcurrencyTest#test_concurrency [/Users/masakinukaga/oss-hack/redmine/test/unit/issue_nested_set_concurrency_test.rb:45]:
Expected "Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: SELECT `issues`.`id` FROM `issues` WHERE (root_id IN (SELECT root_id FROM issues WHERE id IN (905,902)))  ORDER BY `issues`.`id` ASC FOR UPDATE" to be nil.
```

**Comment by pyonnuka** [comment]
- 作業：開発者用のドキュメントを読んで、データベース周りのことが書かれていないか調査
- 思っていること：テストの回し方とかにも特にデータベースのことについては書かれてなかった

**Comment by pyonnuka** [comment]
- 作業：Mysqlのエラーでてるところのユニットテスト回す
- 思っていること：ドキュメントに説明が足りない？Mysqlじゃなかったらどうなる？

備考：テストの結果は以下の通り

``` text
MasakiNukaga-no-MacBook-Pro:redmine masakinukaga$ bundle exec rake test test/unit/issue_nested_set_concurrency_test.rb
Run options: --seed 19299

# Running:

F.

Finished in 2.855391s, 0.7004 runs/s, 2.4515 assertions/s.

  1) Failure:
IssueNestedSetConcurrencyTest#test_concurrency [/Users/masakinukaga/oss-hack/redmine/test/unit/issue_nested_set_concurrency_test.rb:45]:
Expected "Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: SELECT `issues`.`id` FROM `issues` WHERE (root_id IN (SELECT root_id FROM issues WHERE id IN (1859,1856)))  ORDER BY `issues`.`id` ASC FOR UPDATE" to be nil.
```

**Comment by pyonnuka** [comment]
- 作業：postgersSQLのインストール
- 思っていること：ドキュメント通りに進める

**Comment by pyonnuka** [comment]
- 作業：postgresSQLの設定を書く
- 思っていること：ドキュメント通りに進める

**Comment by pyonnuka** [comment]
- 作業：postgresSQLのユーザ作成
- 思っていること：ドキュメント通りに進める

**Comment by pyonnuka** [comment]
- 作業：postgresSQLのサーバ起動してテスト実行
- 思っていること：作業ディレクトリ内のファイルが全部消えた？？

**Comment by pyonnuka** [comment]
- 作業：ディレクトリに入り直してpostgresでテスト実行
- 思っていること：Mysqlのときのテスト結果と違う

備考：テスト結果は以下の通り

``` text
  1) Error:
SearchTest#test_search_should_be_case_and_accent_insensitive_with_postgresql_and_noaccent_extension:
ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied to create extension "unaccent"
HINT:  Must be superuser to create this extension.
: CREATE EXTENSION IF NOT EXISTS unaccent
    test/unit/search_test.rb:178:in `test_search_should_be_case_and_accent_insensitive_with_postgresql_and_noaccent_extension'


  2) Failure:
AttachmentsControllerTest#test_show_text_file_should_send_if_too_big [/Users/masakinukaga/oss-hack/redmine/test/functional/attachments_controller_test.rb:186]:
Expected response to be a <success>, but was <404>


  3) Failure:
AttachmentsControllerTest#test_download_should_assign_better_content_type_than_application_octet_stream [/Users/masakinukaga/oss-hack/redmine/test/functional/attachments_controller_test.rb:269]:
Expected response to be a <success>, but was <404>


  4) Failure:
AttachmentsControllerTest#test_download_should_assign_content_type_if_blank [/Users/masakinukaga/oss-hack/redmine/test/functional/attachments_controller_test.rb:260]:
Expected response to be a <success>, but was <404>


  5) Failure:
AttachmentsControllerTest#test_download_text_file [/Users/masakinukaga/oss-hack/redmine/test/functional/attachments_controller_test.rb:238]:
Expected response to be a <success>, but was <404>


  6) Failure:
AttachmentsControllerTest#test_show_text_file [/Users/masakinukaga/oss-hack/redmine/test/functional/attachments_controller_test.rb:116]:
Expected response to be a <success>, but was <404>

3647 runs, 22090 assertions, 5 failures, 1 errors, 0 skips
```

**Comment by pyonnuka** [comment]
- 作業：sqliteでテスト実行
- 思っていること：データベースごとにテスト結果違う。設定ファイルの差見てみよう

備考：以下にテスト結果を示す

``` text
  1) Failure:
AttachmentsControllerTest#test_show_text_file [/Users/masakinukaga/oss-hack/redmine/test/functional/attachments_controller_test.rb:116]:
Expected response to be a <success>, but was <404>


  2) Failure:
AttachmentsControllerTest#test_show_text_file_should_send_if_too_big [/Users/masakinukaga/oss-hack/redmine/test/functional/attachments_controller_test.rb:186]:
Expected response to be a <success>, but was <404>


  3) Failure:
AttachmentsControllerTest#test_download_text_file [/Users/masakinukaga/oss-hack/redmine/test/functional/attachments_controller_test.rb:238]:
Expected response to be a <success>, but was <404>


  4) Failure:
AttachmentsControllerTest#test_download_should_assign_better_content_type_than_application_octet_stream [/Users/masakinukaga/oss-hack/redmine/test/functional/attachments_controller_test.rb:269]:
Expected response to be a <success>, but was <404>


  5) Failure:
AttachmentsControllerTest#test_download_should_assign_content_type_if_blank [/Users/masakinukaga/oss-hack/redmine/test/functional/attachments_controller_test.rb:260]:
Expected response to be a <success>, but was <404>
```

**Comment by pyonnuka** [comment]
- 作業：rubyを2.1.2から1.9に変更する
- 思っていること：rbenvでインストールして変更

**Comment by pyonnuka** [comment]
- 作業：ドキュメントを読み直した
- 思っていること：データベースに関する文書あったから試してみる

**Comment by pyonnuka** [comment]
- 作業：前項で発見したコマンドを打ってみた
- 思っていること：それらしいファイルが作成された

**Comment by pyonnuka** [comment]
- 作業：テストを実行した
- 思っていること：エラーが増えた。データベースに必要なデータが入ってないかも。

**Comment by pyonnuka** [comment]
- 作業：UIテスト実行
- 思っていること：エラー無しで正常だった

**Comment by pyonnuka** [comment]
- 作業：実際にプロジェクト作って動作確認してみた
- 思っていること：プロジェクトにメンバー追加するときのダイアログにtypo？

**Comment by pyonnuka** [comment]
- 作業：Typoらしいところを発見した
- 思っていること：プロジェクトのユーザ追加してるファイルかlocaleファイルかな

**Comment by pyonnuka** [comment]
- 作業：Typoを修正した
- 思っていること：プルリク？というかチケット発行がすごい大変そう

**Comment by pyonnuka** [comment]
- 作業：テストが全然通らないので、公式ドキュメントに記載されている実行環境に完璧に合わせに行く。まずはubuntu-11.10のインストール
- 思っていること：実行環境揃えればテストを通す希望出てきそう

**Comment by pyonnuka** [comment]
- 作業：ubuntuインストールしてる間にRedmineの機能をいろいろ触ってみる
- 思っていること：管理画面のワークフローのUIが不自然

備考：ロールやトラッカーが登録されていない状態で編集を押すとUIが崩れたり、リストの中身が真っ白になる

**Comment by pyonnuka** [comment]
- 作業：ubuntuに環境を設定していく
- 思っていること：ドキュメント通りに進める

備考：
Databases:
MySQL 5.1.58
PostgreSQL 9.1.1
Sqlite 3.7.7
SQL Server 2012
SCM:
Subversion 1.6.12
Mercurial 1.9.1
Git 1.7.5.4
CVS 1.12.13
Bazaar 2.4.1
Darcs 2.5.2

**Comment by pyonnuka** [comment]
- 作業：mysqlインストールした
- 思っていること：5.1.58が見つからない。とりあえず最新版で対応しておこう

**Comment by pyonnuka** [comment]
- 作業：subversionインストールした
- 思っていること：1.6.12見つからない。とりあえず全部最新版入れていこう。

**Comment by pyonnuka** [comment]
- 作業：Mercurial、Git、CVS、Bazaar、Darcsをインストール
- 思っていること：作業通りにやったら簡単だった

備考：ubuntuに入れたdatabaseとSCMのリスト
mysql         5.1.69　
subversion 1.6.12
mercurial    1.9.12
git               1.7.5.4
cvs              1.12.13
bazaar        2.4.2
darcs          2.5.2

| 名前 | インストールしたバージョン | Redmineで推奨されているバージョン |
| --- | --- | --- |
| mysql | 5.1.69 | *5.1.58 |
| subversion | 1.6.12 | 1.6.12 |
| mercurial | 1.9.1 | 1.9.1 |
| git | 1.7.5.4 | 1.7.5.4 |
| cvs | 1.12.13 | 1.12.13 |
| bazaar | 2.4.2 | *2.4.1 |
| darcs | 2.5.2 | 2.5.2 |

**Comment by rust** [comment]
FYI: ubuntu には redmine パッケージがありますね。

http://packages.ubuntu.com/trusty/redmine

**Comment by pyonnuka** [comment]
- 作業：ruby2.2.2インストールしようとした
- 思っていること：ruby2.2.2が見つからない。rbenvでインストールしよう

**Comment by pyonnuka** [comment]
- 作業：rbenvでruby2.2.2をインストールした
- 思っていること：rbenvのコマンドを勘違いしてて、ちょっとはまった

備考：rbenvでrubyをインストールするにはバージョン番号のみでいい

``` text
rbenv install 2.2.2
```

**Comment by pyonnuka** [comment]
- 作業：ubuntuでテスト回してみたら通った
- 思っていること：OS X上でテスト回したときより項目増えてるの原因気になる。とりあえずこれでコード修正入れる！

**Comment by pyonnuka** [comment]
- 作業：railsでサーバ起動できるように設定を進める
- 思っていること：作業ログを参照して同じように進めれば大丈夫そう

**Comment by pyonnuka** [comment]
- 作業：テストが動かなくなった。rails consoleも動かない。
- 思っていること：rubyのバージョンがおかしい？rbenvが消えててwhichで見てもなくなってる。

**Comment by pyonnuka** [comment]
- 作業：rbenvのパスを再設定した
- 思っていること：正常通りに動くようになった！

**Comment by pyonnuka** [comment]
- 作業：Redmineへのプルリク（チケット発行）の手順確認
- 思っていること：英語ちょっと不安

**Comment by pyonnuka** [comment]
- 作業：ja.ymlの翻訳のTypoを修正
- 思っていること：プルリクのときに説明しやすいように修正前のスクショとっておこう

**Comment by pyonnuka** [comment]
- 作業：前項の変更をコミット
- 思っていること：変更logみて、コミットメッセージ考えた

**Comment by pyonnuka** [comment]
- 作業：パッチ作成を始めた
- 思っていること：ドキュメントにやり方が載ってたのでその通りにやってみよう

**Comment by cesare** [comment]
> プルリクのときに説明しやすいように修正前のスクショとっておこう

:+1:

**Comment by pyonnuka** [comment]
- 作業：チケット作成
- 思っていること：これからの開発者との会話が少し不安
