### ISSUE TITLE
OSS Hack Weekend: Sesta: material-design-lite JS: 作業ログ

### ISSUE THREAD

**Issue by sesta** [clear-code/sezemi-2015#37]
1日目の対象OSS : https://github.com/peachananr/onepage-scroll
2日目の対象OSS : https://github.com/google/material-design-lite

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by sesta** [comment]
- 作業 : コードをダウンロードして実際に動かしてみる
- 思っていること : 一度動かしたので問題ないはず

**Comment by sesta** [comment]
- 作業 : 一度ドキュメントを読んで、できることを再確認する
- 思っていること: 英語が苦手なのでがんばる

**Comment by sesta** [comment]
- 作業 : リロードしたら変になった
- 思っていること: 絶対issueはたってるけど直したい

備考 : 変になるとはどういうことか

下のURLにアクセスして
http://www.thepetedesign.com/demos/onepage_scroll_demo.html#2
リロードすると、最初に若干みだれる

たぶん次の手順で発生すると思う
- ページにアクセスする
- 右端のボタンをクリックして、表示してる内容を切り替える
- URLの末尾に「#2」などのアンカーがつく
- リロードするとアンカーの場所に無理にアニメーションを使って飛ぼうとする
- くずれる

スクロール時はアンカーを使っていないようなので
どうにかクリック時も同じような処理にできれば治るかも

**Comment by sesta** [comment]
- 作業 : 戻ろうと思っても戻れない
- 思っていること : 仕様な気がしないでもない

備考 : 戻れないとは

最近のブラウザはスワイプで前のページで戻れたりするが
このライブラリを適用した領域上ではスワイプが効かないため
戻れない

スクロール関係のイベントをoverrideしてるせいなのかも
正直、仕様な気がしないでもない

**Comment by sesta** [comment]
- 作業 : スマホでスクロールしたら、変な空間ができる
- 思っていること : スクロールしたときに、pcで見たときと同じ動きになってほしい

備考 : スマホのブラウザの仕様では

スマホのブラウザはページの端まで来たときに
端だとわかるように、変な空間がでるようになってる
これはブラウザのアプリの仕様なので、手が出せない気がする

**Comment by sesta** [comment]
- 作業 : スクロールで現れる領域( 以下セクション )の数を増やすと、ボタンの位置が中央じゃなくなる
- 思っていること : せっかくセクションの数を増やせるのだから、対応すべきでは

備考 : 中央でなくなる理由

読み込ませるように指示されているcss「onepage-scroll.css」のなかの

``` css
.onepage-pagination {
  position: absolute;
  right: 10px;
  top: 50%;
  z-index: 5;
  list-style: none;
  margin: 0;
  padding: 0;
}
```

のtopの指定の仕方が問題では

**Comment by sesta** [comment]
- 作業 : 横に切り替えるようなオプションをつけてみた
- 思っていること : 横に切り替わるようになるのに、ボタンは縦のまま

備考 : cssのクラスとかで場合分けすれば簡単に直りそう

**Comment by sesta** [comment]
- 作業 : 設定できるオプションの調査
- 思っていること : オプションを説明するための章があってもいいろ思う

備考 : 現在はソースコード内のコメントでオプションについて説明している

**Comment by sesta** [comment]
- 作業 : 既存のIssueのチェック
- 思っていること : 英語が苦手なのでがんばる

**Comment by mumoshu** [comment]
順調そうですね :+1:

**Comment by sesta** [comment]
いまのところはって感じです！(ﾟ □ ﾟ )

**Comment by mumoshu** [comment]
- 自分で使ったことがあったのですんなりテストできた
- 戻ろうと思っても戻れない問題
  - ブラウザの戻るボタンだと戻れる
  - トラックパッドだと戻れない
  - 左右のスワイプを検知する必要がないときも全部検知してしまっているのでは？という気付き
  - まだコード読んでない
    - でも仮説立てて取り組むのはよいことだと思います！
  - スマフォで上下にスクロール仕切った時の動きが気持ち悪い
    - 対応悩み中
- 各ページをsectionと読んでいる。sectionを足すとページが増えるが、ページインジケータが下に伸びていく。
  - top: 50%になっているので、それを変えればいけるのではないかと思っている
- 縦じゃなくて横にもスクロールできるように設定できる
  - ただし、その時でもページインジケータは縦向きになっていて、違和感
  - CSSいじれば横スクロールのときはページインジケータも横置きにできるのではないかと思っている
- `updateURL: true` (デフォルトはfalse) にすると、スクロールしたときのURL書き換えを行う
  - falseにするとスクロールしたときのURL書き換えは行わない（でも、クリックしたときの書き換えは行う、わかりづらい)
- issue 150くらいある
  - 上記の問題はどこかにあるのでは
  - (フィードバック)全部読むのは大変だよね。関連するキーワードで絞り込んで読むなり、タイトルだけ流し読みするほうがよいかも。
  - 既存のマージされてるプルリを読むと、そのプロジェクトでマージされやすいプルリがわかって良いです

**Comment by sesta** [comment]
- 作業 : 既存のプルリクを確認
- 思っていること : 既にありそう

**Comment by sesta** [comment]
- 作業 : ボタンがセクションの数にかかわらず中央に来るようにする
- 思っていること : cssをいじれば簡単になおるはず

**Comment by sesta** [comment]
- 作業 : プルリクの作成
- 思っていること : マージしてもらえるようにがんばる

**Comment by sesta** [comment]
- 作業 : スワイプで戻れるようにする
- 思っていること : スワイプのイベントが何かあればいけそう

**Comment by sesta** [comment]
- 作業 : 新しいOSSにチャレンジ、まずはドキュメントを読んで動かす
- 思っていること : プルリクを送る自信はないがチャレンジしたいOSSです

備考 : チャレンジするOSS
https://github.com/google/material-design-lite

**Comment by sesta** [comment]
- 作業 : テンプレートの中にリンク切れのようなものを発見
- 思っていること : テンションあがってきた

備考 : googleへのコントリビュート

**Comment by sesta** [comment]
- 作業 : ドキュメントに従い実行
- 思っていること : うまくいかない

備考 : ドキュメントで指定されたようにクローンしてもだめ

ドキュメントでは以下のようなコマンドでクローンすればよいとかいてある

```
git clone --bare https://github.com/google/material-design-lite.git
```

ドキュメントに中には、上のコマンドによって取得できるはずの
ファイルやディレクト一覧が示してあるが
上のコマンドでは取得できない、下のコマンドなら大丈夫だった

```
git clone https://github.com/google/material-design-lite.git
```

**Comment by sesta** [comment]
作業 : ドキュメントを読んで gulp serve できるようにする
思っていること : git cloneからつまづいているので辛いかも

備考 : 細かく色々やっているので、ここにリストアップしていきます
何か問題が発生したら
新しいコメントで追加します。
- nodeとnpmのアップデート
- git clone して npm installを実行
- gulp start を実行
- 実行できた

**Comment by sesta** [comment]
作業 : ( 解決！ ) npm install でエラー発生
思っていること : すごくつまりそうな気がする
解決方法 : 今使っているユーザに権限を与える

備考 : 以下のコマンドを実行

```
npm install && npm install -g gulp
```

するとある程度処理が進んだ後以下のエラーが

```
gulp-sass@1.3.3 node_modules/gulp-sass
├── clone@0.1.19
├── map-stream@0.1.0
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── node-sass@2.1.1 (get-stdin@4.0.1, object-assign@2.1.1, replace-ext@0.0.1, cross-spawn@0.2.9, chalk@0.5.1, nan@1.8.4, semver@4.3.6, shelljs@0.3.0, mkdirp@0.5.1, npmconf@2.1.2, meow@3.3.0, gaze@0.5.1, sass-graph@1.3.0, request@2.58.0, pangyp@2.2.1)
npm ERR! tar.unpack untar error /Users/SestaMac/.npm/gulp/3.9.0/package.tgz
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.0
npm ERR! path /usr/local/lib/node_modules/gulp
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/gulp'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/gulp']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/gulp',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/gulp',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/SestaMac/Documents/develop/oss/material-design-lite/npm-debug.log
```

調べたら、必要なディレクトリに権限を与えればよさそう
具体的には下のコマンドをうてばよい

```
sudo chown -R username ~/.npm
sudo chown -R username /usr/local
```

参考URL : http://okapie.sakura.ne.jp/cm_sample.html

**Comment by sesta** [comment]
作業 : テンプレートの実行
思っていること : リンク切れではなく、gulpを実行していなかっただけだった。googleは悪くない

**Comment by mumoshu** [comment]
(メモ) 2日目は新しいOSS(material-design-lite)に取り組んでいます!

**Comment by sesta** [comment]
作業 : Issueの確認
思っていること : 直せる場所がない

**Comment by mumoshu** [comment]
> 思っていること : 直せる場所がない

www

**Comment by mumoshu** [comment]
振り返り
- 手順を見直すことで、バグと思っていたところがバグでないと判明してGood :+1:
- 「用途のわからないhead.jpgファイルへの参照がcss内にある」という問題に気づけた。細かいところまでよく見られてますね
  - 話し合った感じでは、バグですね
  - CONTRIBUTING.mdを参照しながらコントリビュートしてみましょう :fire:

**Comment by sesta** [comment]
作業 : head.jpgが無い問題の修正
思っていること : チョットデキル気がしてきた

備考 : 問題の場所
https://github.com/google/material-design-lite/blob/master/templates/blog/styles.css#L10

**Comment by sesta** [comment]
作業 : head.jpgに関してちょっと前にissueがあったので確認する
思っていること : 英語が難しそう

**Comment by mumoshu** [comment]
フィードバック
- head.jpgが導入されたプルリを見つけて、そこで合意の上でプルリがマージされていた
- でもプルリの説明を読んでも意味がわからない
  - プルリの説明からリンクされてる動画を見てみると何かわかるかも

**Comment by sesta** [comment]
作業 : issue を元にfixできそうなので、ブランチを切って修正する
思っていること : 修正は簡単そう

備考 : 例のissue
https://github.com/google/material-design-lite/issues/560

**Comment by sesta** [comment]
作業 : プルリク作成
思っていること : ついにきた

**Comment by mumoshu** [comment]
```
# 内容を変えてコミットを"作り直す"
git add 変更点
git commit --amend
# コミットを作り直すと歴史が書き換わる。そのままgit pushすると操作ミスなどの防護的な意味で「歴史書き換えようとしてますよ」とエラーにしてくれる。しかし、ここではコミットを作り直したいという意思があってやっているので、`-f` (強制=forceのf)をつけて防護策を回避する（と、git pushできる）
git push origin fix_template_blog_background:issue-560 -f
```

**Comment by sesta** [comment]
作業 : プルリク完了
思っていること : よかった

**Comment by mumoshu** [comment]
@Sesta さんが教えてくれた [英語コミットコメントに使えるオシャレフレーズ集](http://qiita.com/ken_c_lo/items/4cb49f0fb74e8778804d) 便利ですね!

**Comment by sesta** [comment]
ありがとうございます！
自分も学生スタッフの @20tkts14 君に教えてもらったので
彼に感謝です( ´ ▽ ` )ﾉ
