### ISSUE TITLE
OSS Hack Weekend: ramesses2nd: s2n: C: 作業ログ

### ISSUE THREAD

**Issue by ramesses2nd** [clear-code/sezemi-2015#38]
https://github.com/awslabs/s2n

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by ramesses2nd** [comment]
- 作業：makeしてs2nをビルド
- 思っていること：全工程が無事に終わるはず

**Comment by ramesses2nd** [comment]
- 作業：unit testで失敗
- 思っていること：すでにhttps://github.com/awslabs/s2n/issues/97 で言及されている問題と同じだろう。
- 環境：OS X 10.10.4, Libre SSL2.2.1

備考：エラーメッセージは次の通り

``` text
Running s2n_override_openssl_random_test.c                 ... FAILED test 20
(mock_called) == (1) is not true  (s2n_override_openssl_random_test.c line 114)
Error Message: 'no error'
```

**Comment by ramesses2nd** [comment]
- 作業：サンプルコードを実行してみる
- 思っていること：サーバとクライアントのコードなので、動くだろう

**Comment by ramesses2nd** [comment]
- 作業：サンプルコードの実行に失敗した。
- 思っていること：権限？それともipとポート番号の設定が悪い？

備考：エラーメッセージは以下の通り

実行手順

```
$sudo ./s2nd [IPアドレス] [ポート番号]
```

した後に、別のターミナルから

```
$sudo ./s2nc [IPアドレス] [ポート番号]
```

を実行

s2nc（クライアント）のエラー

``` text
Error getting new connection: 'client connections not allowed'
```

s2nd（サーバ）のエラー、ただしクライアント側を動作させた後に生じる

``` text
Failed to negotiate: 'connection is closed' -1
```

**Comment by ramesses2nd** [comment]
- 作業：サンプルコードが動かない問題が解決
- 思っていること：ドキュメントに書いてあったが、以下の環境変数が設定されていなかった。

環境変数の設定

```
$export S2N_ENABLE_CLIENT_MODE=1
```

**Comment by ramesses2nd** [comment]
- 作業：ドキュメントの調査
- 思ったこと：typo?っぽいのがある

**Comment by ramesses2nd** [comment]
- 作業：タイポを修正、プルリクエストを送った
- 思ったこと：すぐに英語が出てこない...

**Comment by ramesses2nd** [comment]
- 作業：unit testに失敗する原因を調査
- 思ったこと：s2nのせいではないかも

**Comment by ramesses2nd** [comment]
- 作業：travis ciが失敗してる
- 思ったこと：opensslが解凍できないって...

**Comment by ramesses2nd** [comment]
- 作業：travis ciの失敗はcurlコマンドに-Lオプションが付いていないから
- 思ったこと：すでにPRが出ているから、マージしてほしい

**Comment by ramesses2nd** [comment]
- 作業：makeでunit testを行うけれど、一つ失敗したらそこでテストをやめています
- 思ったこと：makefileの書き方調べるか...

**Comment by ramesses2nd** [comment]
- 作業：makefileを修正して、PRを出した。
- 思ったこと：英語やらなきゃ...

**Comment by ramesses2nd** [comment]
- 作業：gdbをインストール
- 思ったこと：うごかない... コード署名してるのに

**Comment by ramesses2nd** [comment]
- 作業：gdbを起動できた
- 思ったこと：コード署名がなくても、sudoで動かせるのか....

**Comment by ramesses2nd** [comment]
- 作業：マージされました！
- 思ったこと：typoだし、割とすんなり

**Comment by ramesses2nd** [comment]
- 作業：makefileへのPRに対してコメントが来たので、それに対する返答を考える
- 思ったこと：やらなきゃ！

**Comment by ramesses2nd** [comment]
- 作業：テスト周りを調査　https://github.com/awslabs/s2n/blob/master/docs/DEVELOPMENT-GUIDE.md#tests
- 思ったこと：いいマクロってあるのか？

**Comment by ramesses2nd** [comment]
- 作業：PR( https://github.com/awslabs/s2n/pull/141 )への返答を考える
- 思ったこと：相手の考えを汲み取らないと

**Comment by ramesses2nd** [comment]
- 作業：PRへ変更を送った。（コミット付き）
- 思ったこと：返信がくるのはいつだろう？

**Comment by ramesses2nd** [comment]
- 作業：メモを残さなさすぎたので、追記
- 追記：unit testのコードを読む -> マクロで対処は無理そう -> makefileで対処しよう -> makefileの書き方を調べる -> opensslのバージョンを表示させるように実装。上のコメントへ

**Comment by gfx** [comment]
testまわりは整理するのが面倒で後回しにされがちだし、けっこううれしい修正かなと思います。お疲れさまでした。
