### ISSUE TITLE
リーダブルコード：メビュー：メンターの視点を聞こう！

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#4]
リーダブルコード勉強会では「他の人のコードからリーダブルなコードを見つける」という方法を体験します。今はまだうまく見つけられないでしょうが、いろんな視点からコードを読めるようになると、さらにうまく見つけられるようになります。コードを読む視点を増やすために、自分が書いたコードをメンターに読んでもらって、メンターならどんな視点でコードを読むのか聞いてみましょう。

自分のコードを読んでもらってメンターの視点を聞きたい人はコメント欄に次の情報を記入してください。
- 必須：読んでもらいたいコードが入っているリポジトリー
- 任意：読んでもらいたいメンター
- 任意：備考（特に読んでもらいたいところ、自分が工夫したところ、など）

「読んでもらいたいメンター」を指定した場合は（できるだけ）そのメンターが読んでメンターの視点でコメントを書きます。メンターを指定していない場合はメンターの誰かがコードを読んでメンターの視点でのコメントを書いていきます。

コメントは実際のGitHub上のコードにコメントします。そのため、読んでもらった参加者だけでなく、他の参加者もメンターの視点を知ることができます。（メンターは参加者に直接説明するだけでなく、GitHub上にもコメントを残してあげてください。そうすれば、本人が後でふりかえることもできますし、他の参加者が新しい視点を得ることができます。）

メンターは次の通りです。
- cesare
- sunaot
- tatsuo
- upinetree
- mrkn
- kinkinkon1009
- jflute
- horie1024
- repeatedly
- bash0C7
- catatsuy
- zonuexe
- kawahara
- sasamoriyusuke
- suzukiyuichi
- bynnchapu
- arthurbryant
- haneri
- adammunoz
- nkmr1040
- redfigure
- myokoym
- kou
- piroor
- okkez

なお、「メビュー」は「Mentor's View」の略です。「レビュー」と似ていますが「レビュー」とは違います。「レビュー」は「問題がないかチェックする」ことが目的ですが、「メビュー」は「メンターの視点を共有する」ことが目的です。

**Comment by kou** [comment]
メビュー依頼例：
- 読んでもらいたいコードが入っているリポジトリー： https://github.com/kou/kou-readable-code-2014-08-11 （ https://github.com/rabbit-shocker/rabbit とかリーダブルコード勉強会以外で書いたコードでもよい）
- 読んでもらいたいメンター： @kou （あるいは「誰でもよいです！」）
- 備考： `while read`と一緒に使うのは`cat`がよいかリダイレクトがいいのか悩みながら書きました。

**Comment by using923** [comment]
依頼チェックテスト

**Comment by 20tkts14** [comment]
テスト

**Comment by using923** [comment]
テスト

**Comment by using923** [comment]
テスト
