### ISSUE TITLE
OSS Hack Weekend: yokoto: lunchy: Ruby: 作業ログ

### ISSUE THREAD

**Issue by yokoto** [clear-code/sezemi-2015#49]
https://github.com/eddiezane/lunchy

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by yokoto** [comment]
- 作業：動かせるか確認  
  - すべてのコマンドが動くか確認する
- 思っていること：動かせた

**Comment by yokoto** [comment]
- 作業：プルリク用にブランチ作る
- 思っていること：名前どうしよう。→ スラッシュで区切るといいらしい。  部署名/機能名/やること

**Comment by yokoto** [comment]
- 作業：masterのバージョンで動くか確認
- 思っていること：動いた  
  備考：確認方法  
  - `rake -T` タスクのリスト  
  - `rake install` masterのバージョンをインストール

**Comment by yokoto** [comment]
- 作業：1行加えてプルリクエスト  
- 思っていること：送れてよかった  
  備考：
  - ローカルでの変更を反映し確認するには`rake install`する必要があった。  
  - コンソールで確認するとき変数やクラスを初期化するのは大事。

**Comment by yokoto** [comment]
- 作業：seattlerb/minitestをインストール
- 思っていること：READMEのtypoが結構ある

**Comment by rust** [comment]
> 思っていること：READMEのtypoが結構ある

とりあえず PR 送ってみるとか！

**Comment by yokoto** [comment]
> > 思っていること：READMEのtypoが結構ある  
> 
>  とりあえず PR 送ってみるとか！  

とりあえず送ってみます！

**Comment by yokoto** [comment]
- 作業：これからプルリクする  
- 思っていること：これでいいのか

**Comment by yokoto** [comment]
- 作業：プルリクした
- 思っていること：コミットの整え方を学べてよかった  
  備考：
  - [横着で神経質な私とあなたに贈るgit add -p](http://qiita.com/crifff/items/1abf08bca4ce51db4775)

**Comment by yokoto** [comment]
- 作業：テストを書く  
- 思っていること：自分の環境にあるファイルに対する、標準出力のテストの方法  
  備考：
  - rspecのとき、beforeでファイルを作ってafterで消すようにする  
  - 可能なときは環境に依存しないように実際のプログラムの方も書き換えるようにするといい
