### ISSUE TITLE
OSS Hack Weekend: S-Shimotori: Quick: Swift: 作業ログ

### ISSUE THREAD

**Issue by S-Shimotori** [clear-code/sezemi-2015#50]
https://github.com/Quick/Quick

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by S-Shimotori** [comment]
- 作業：pull request
- 思っていること：慣らしでドキュメントから。

**Comment by S-Shimotori** [comment]
- 作業：自分のプロジェクトのQuickのぶらんちをmasterにまーじ
- 思っていること：ビルドが異様に遅いしアプリを実行できないのでつらい。

``` text
dyld_sim`dyld_fatal_error:
    0x10830e000 <+0>: int3   
->  0x10830e001 <+1>: nop    < Thread 1: EXC_BREAKPOINT(code=EXC_I386_BPT, subcode=0x0)
```

**Comment by S-Shimotori** [comment]
家でやってきたこと
1. 捨てプロジェクトを作って[Documentation](https://github.com/Quick/Quick/tree/swift-2.0/Documentation)のOrganized Tests with Quick Examples and Example Groupsまでやってみる
   →[Effective Tests Using XCTest: Arrange, Act, and Assert](https://github.com/Quick/Quick/blob/swift-2.0/Documentation/ArrangeActAssert.md)のソースコードに誤りを発見
2. 既存プロジェクト(XCTest使用)にQuickを入れて置き換え
   →テストは通ったがアプリが起動しなくなった(エラーは上記のとおり)
3. 既存プロジェクトのQuickに置き換えたところにRealm model classを混ぜてみた
   →エラー

**Comment by S-Shimotori** [comment]
- 作業：アプリが即落ちるのでインストール直前から履歴戻しまくって原因探す
- 思っていること：原因がわからないのでつらい

→インストール直前に戻して

``` Podfile
use_frameworks!

pod '他のやつ'

target 'HogeTests' do
    pod 'Quick', '~> 0.3.0'
    pod 'Nimble', '~> 1.0.0'
end
```

で起動成功

**Comment by S-Shimotori** [comment]
- 作業：アプリが落ちるブランチからcherry-pickで使えるコミットを救出
- 思っていること：1個解決したのでよかった

**Comment by S-Shimotori** [comment]
- 作業：モブclassからRealm用クラスに変えてテストするとエラー出るのでそれをなんとかする
- 思っていること：過去のissueにありそう

SuiteHook.swift

``` swift
final internal class SuiteHooks {
    //...

    internal func executeBefores() {
        assert(!beforesAlreadyExecuted)    //Thread 1: EXC_BAD_INSTRUCTION(code=EXC_I386_INVOP, subcode=0x0)
        for before in befores {
            before()
        }
        beforesAlreadyExecuted = true
    }

    internal func executeAfters() {
        //...
    }
}
```

→データベース側のせいでした

**Comment by S-Shimotori** [comment]
- 作業：ぷるりくのネタを考える
- 思ったこと：これとか[Multiple `it`s within `context` are not evaluated · Issue #324 · Quick/Quick](https://github.com/Quick/Quick/issues/324)

**Comment by S-Shimotori** [comment]
- 作業：↑の対策を考える
- 思ったこと：Stringもらってその名前で関数作ってるけど、ダブった時の処理がないように見受けられる。  
  https://github.com/Quick/Quick/blob/swift-2.0/Quick/QuickSpec.m#L99-108

**Comment by Matsue** [comment]
現在取り上げているissueですが、[関連するissue](https://github.com/Quick/Quick/issues/299)へのPRがOpenしたままになっています。

https://github.com/Quick/Quick/pull/295#discussion_r30947227

作者の懸念事項や意見が書かれているので、上記の状況を参考にした改修になると良いと思います。

**Comment by S-Shimotori** [comment]
- 作業：名前がダブってもクラス名と行数を自動でつけてユニークにする
- 思ったこと：ファイル名だと長いのでクラス名で代用した。fetchしてない差分が混じったのでなおさないといけない

https://github.com/S-Shimotori/Quick/blob/fix-issue324/Quick/QuickSpec.m

**Comment by S-Shimotori** [comment]
issue番号間違えてました。

https://github.com/S-Shimotori/Quick/tree/fix-issue299

**Comment by S-Shimotori** [comment]
- 作業：ソースコードを綺麗にした
- 思ったこと：ObjCきもい

**Comment by S-Shimotori** [comment]
- 作業：コミットを綺麗にした
- 思ったこと：fetchと本家のコミットルールにあわせるのたいへん

**Comment by S-Shimotori** [comment]
ob-c, swift, 両方覚えるのつらいっすねwお疲れ様でした！
