### ISSUE TITLE
OSS Hack Weekend: NakanoMizuki: Mixer2: Java: 作業ログ

### ISSUE THREAD

**Issue by mi-nakano** [clear-code/sezemi-2015#52]
Mixer2 
https://github.com/nabedge/mixer2

Mixer2-sample
https://github.com/nabedge/mixer2-sample

Mixer2ドキュメント
http://mixer2.org/site/ja/index.html

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by mi-nakano** [comment]
- 作業：開発用にMixer2をインポートする
- 思っていること：前回インポートしたので大丈夫

**Comment by mi-nakano** [comment]
- 作業：Mixer2-sampleのissue#20を直す
- 思っていること：該当箇所の出力メッセージを修正すれば良いはず

備考：issue#20は以下

> カートにいれた商品をチェックアウトして配送先を入力する画面で、
> たとえば"your first name"を入れる欄を空欄にしておくと
> hibernateのデフォルトのエラーメッセージが出るだけ。
> もっと親切なメッセージにするべき
> https://github.com/nabedge/mixer2-sample/issues/20

**Comment by mi-nakano** [comment]
- 作業：issue#20の修正
- 思っていること：メッセージを書き換えることには成功した。どのようなメッセージに修正するのが妥当か。

**Comment by mi-nakano** [comment]
- 作業：#20の修正内容をフォークしたリポジトリにプッシュ
- 思っていること：これをプルリクエストして大丈夫か？

備考：修正内容は以下

https://github.com/NakanoMizuki/mixer2-sample/commit/295a885cee0646cb1f171c22b94ba27b891f2520

修正前
![2015-07-11 11 49 03](https://cloud.githubusercontent.com/assets/7775726/8632007/e50a718c-27c2-11e5-83e4-edd6a1538494.png)
修正後
![2015-07-11 11 26 05](https://cloud.githubusercontent.com/assets/7775726/8632018/388a03fe-27c3-11e5-967b-9dc266d4c832.png)

**Comment by mi-nakano** [comment]
- 作業：変更内容をプルリクエストで送る
- 思っていること：メンターの方に相談しながらやる

**Comment by mi-nakano** [comment]
- 作業：プルリクエストを送った
- 思っていること：おそらくなんらかの修正をする必要がありそう。

**Comment by mi-nakano** [comment]
- 作業：プルリクエストに返事が来た。修正の必要あり。
- 思っていること：まずは返事を読んで修正

**Comment by mi-nakano** [comment]
- 作業：フォークしたリポジトリが古くなっていたので、プルリクエストをリベースした
- 思っていること：プルリクエストの修正はまだ

**Comment by mi-nakano** [comment]
- 作業：エラーメッセージの表示を変更
- 思っていること：モデルのクラスファイルのアノテーションを変更することでメッセージを変えることができた。あとはこれをプロパティファイルで指定できるようにする。

**Comment by mi-nakano** [comment]
- 作業：エラーメッセージをmessages.propertiesで指定することに成功
- 思っていること：これでプルリクエストを修正する。

**Comment by mi-nakano** [comment]
- 作業：PRを修正、マージされた
- 思っていること：初マージ！

**Comment by mi-nakano** [comment]
- 作業：他のissueに取り組む
- 思っていること：新しいサンプルを作るissue#24 が良さそう。

**Comment by mi-nakano** [comment]
- 作業：fakeSMTPをダウンロードして動かした。
- 思っていること：次はCommons-emailを動かしてfakeSMTPで動作を確認する。続きは明日

**Comment by mi-nakano** [comment]
- 作業：Commons-emailを用いてHTMLメールを送る
- 思っていること：まずは依存性の解決で外部JARを利用できるようにする必要が有る。

**Comment by mi-nakano** [comment]
- 作業：外部JARの依存性解決
- 思っていること：外部のJARを自作プロジェクト内で使用できた。次はCommons-emailを用いてHTMLメールを送る。

備考：
pom.xmlにタグを追加

```
     <dependencies>
        <dependency>
            <groupId>org.mixer2</groupId>
            <artifactId>mixer2</artifactId>
            <version>${mixer2.version}</version>
        </dependency>
        <dependency>
            <groupId>javax.mail</groupId>
            <artifactId>javax.mail-api</artifactId>
            <version>${javax.mail.api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-email</artifactId>
            <version>1.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.api.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
    </dependencies>
```

**Comment by nabedge** [comment]
おおー。"maven" = 「達人」に一歩近づきましたね。

**Comment by mi-nakano** [comment]
- 作業：Commons-emailのサンプルコードの実行
- 思っていること：mavenで依存性を解決できていることを確認できた。

備考：
サンプルコード
https://commons.apache.org/proper/commons-email/userguide.html

``` java
public static void main(String[] args) throws EmailException{
        logger.debug("log test");
        Email email = new SimpleEmail();
        email.setHostName("smtp.googlemail.com");
        email.setSmtpPort(465);
        email.setAuthenticator(new DefaultAuthenticator("username", "password"));
        email.setSSLOnConnect(true);
        email.setFrom("user@gmail.com");
        email.setSubject("TestMail");
        email.setMsg("This is a test mail ... :-)");
        email.addTo("foo@bar.com");
        email.send();
    }
```

**Comment by mi-nakano** [comment]
- 作業：Commons-emailでfakeSMTPにHTMLメールを送る
- 思っていること：次はHTMLをMixer2で変更してから送る

備考：

> 動作確認
> ![2015-07-12 12 41 40](https://cloud.githubusercontent.com/assets/7775726/8636270/969b551c-2893-11e5-9f80-89187b8131c4.png)

**Comment by mi-nakano** [comment]
- 作業：Mixer2でHtmlを変更したものをメールで送る
- 思っていること：単純な実行サンプルが完成した、実行方法を示したREADME.mdを作る

備考：
![2015-07-12 13 22 26](https://cloud.githubusercontent.com/assets/7775726/8636388/84bf8d08-2899-11e5-826a-95ce1f9b6617.png)

**Comment by mi-nakano** [comment]
- 作業：README.md を追加
- 思っていること：PRを作成して、メンターの方に見てもらう。

**Comment by mi-nakano** [comment]
- 作業：PRを送った
- 思っていること：おそらく修正が必要なので、返事をもらったら修正。

https://github.com/nabedge/mixer2-sample/pull/27

**Comment by mi-nakano** [comment]
- 作業：PRの修正
- 思っていること：修正に漏れがあったので、さらに修正
  不要なフォルダを消し忘れていた
  https://github.com/NakanoMizuki/mixer2-sample/commit/3c122582304c8e3d51b4223ae98208146bf82c30
