### ISSUE TITLE
OSS Hack Weekend: satoichiki: rws-php-sdk: 作業ログ

### ISSUE THREAD

**Issue by ichiki1023** [clear-code/sezemi-2015#53]
作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by ichiki1023** [comment]
- 作業：インストール完了
- 思っていること：ドキュメント通りに進めれば問題なくインストールが出来た

サンプルの実行結果

```
$ php index.php 
int(30)
```

**Comment by ichiki1023** [comment]
- 作業：今後の作業予定
- 思っていること：環境構築が完了したため、以下の開発を考えている  
  ー　バグがあるか  
  ー　修正・改善出来る機能はあるか  
  ー　追加出来る機能はあるか  
  ー　下位バージョンの対応 PHP5.2.10以下で動作可能か  
  ー　コメントを追加する部分はあるか

**Comment by ichiki1023** [comment]
- 作業：sampleディレクトリのindex.phpを実行
- 思っていること：どのように動くのか確認

**Comment by ichiki1023** [comment]
- 作業：config.php.sampleをconfig.phpにリネームし、アプリID、アプリシークレットIDを入力

備考：sample/config.phpを修正

``` php
define('RAKUTEN_APP_ID', '#PLEASE_EDIT#');
define('RAKUTEN_APP_SECRET', '#PLEASE_EDIT#');
define('RAKUTEN_APP_AFFILITE_ID', '#PLEASE_EdIT#');
```

**Comment by ichiki1023** [comment]
- 作業：index.phpにアプリID、アプリシークレットIDを入力
- 思っていること：

備考：sample/index.phpの以下のコードを修正

``` php
    // アプリIDをセット Set Application ID
    $rwsclient->setApplicationId(RAKUTEN_APP_ID);
    // アフィリエイトIDをセット (任意) Set Affiliate ID (Optional)
    $rwsclient->setAffiliateId(RAKUTEN_APP_AFFILITE_ID);
```

**Comment by ichiki1023** [comment]
- 作業： sampleの実装確認
- 思っていること：しっかりと動作が出来るか

備考：sampleを動かした時のスクリーンショット

![2015-07-11 12 01 15](https://cloud.githubusercontent.com/assets/7994534/8632050/add60788-27c4-11e5-86b4-4d8fc1b77b27.png)

**Comment by ichiki1023** [comment]
- 作業：商品検索を行う
- 思っていること ： 商品が正しく検索されるだろうか

備考：エラー？バグ？タイトルがグルメカタログギフトの商品の説明にcssが含めれている。
![2015-07-11 12 04 14](https://cloud.githubusercontent.com/assets/7994534/8632052/fdf6fede-27c4-11e5-92b5-744a52472e55.png)

**Comment by ichiki1023** [comment]
- 作業：SDKではなくAPIを直接アクセスしてバグの確認
- 思っていること：SDKではなくて、APIにも同様のバグがあるのだろうか。

備考：SDKと同様の結果がAPIにも見られました。DB自体にこのtextが入っている可能性が高い
https://app.rakuten.co.jp/services/api/IchibaItem/Search/20140222?applicationId=【自分のAPIキー】&keyword=%E3%82%B0%E3%83%AB%E3%83%A1

**Comment by ichiki1023** [comment]
- 作業：cssの商品説明のcssを取り除く

備考：考えらられる取り除くべきcssの要素一覧
・コメントアウト
・cssの要素名で中括弧で閉じているモノ
・pやh2などのcssの要素

**Comment by ichiki1023** [comment]
- 作業：sampleで、セキュリティに問題がないか確認
- 思っていること：XSS対策はされているか確認を行う

**Comment by ichiki1023** [comment]
- 作業：phpの別のバージョンでも動作出来るのか確認
- 思っていること：サポートされているバージョンで最も古いphp5.2.3を確認する

**Comment by kou** [comment]
お疲れ様でした！
