### ISSUE TITLE
OSS Hack Weekend: YU-TAYU: RakutenWebService: Ruby: 作業ログ

### ISSUE THREAD

**Issue by YU-TAYU** [clear-code/sezemi-2015#57]
https://github.com/rakuten-ws/rws-ruby-sdk

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by YU-TAYU** [comment]
- 作業:対象OSSがアップデートされていたのでインストールし直す。
- 思っていること：gemのuninstallのやり方を知りたい。

**Comment by YU-TAYU** [comment]
- 作業：bundleでのインストールの仕方、アップデートする場合について
- 思っていること：OSS開発には直接的に関係はないが、実際に使う時に方法は知っておきたい。

**Comment by YU-TAYU** [comment]
- 作業：アップデートしたものを使ってみる。
- 思っていること：前回ひっかかった部分が直っているかどうかを試して、確認したい。

**Comment by YU-TAYU** [comment]
* 作業：アップデートしたものを使ってみる。
* 思っていること：前回ひっかかった部分が直っているかどうかを試して、確認したい。

**Comment by YU-TAYU** [comment]
- 作業：masterを追従する
- 思っていること：やり方わからない

**Comment by YU-TAYU** [comment]
- 作業：やり方とgit remote --help で調べながらgit remote add した。
- 思っていること：できたが、この後どうしたら自分のcloneしたものと合わせるのか、方法がわからない。

**Comment by YU-TAYU** [comment]
- 作業 : 前回のIssueのエラーが直ってないから直したい。
  思っていること：エラーはプログラムの中に`require 'uri'`を入れないと動かないのであれば、問題のコード自体に`require'uri'`と入れれば良いのではないかと思う。

**Comment by YU-TAYU** [comment]
- 作業 : rakeコマンドで現在cloneしたものを使える環境にする。
  思っていること：何がどう動いているのかを把握しきれていないので確認しておく。

**Comment by YU-TAYU** [comment]
- 作業 : 前回のIssueのrequire 'uri' なしで実行できるようにする。
- 思っていること : client.rbに追加したらいける気がする。

**Comment by YU-TAYU** [comment]
- 作業：直して、無事に動いたのでpull requrestをした。

備考：前回のIssueのリンクが#{番号}でできることを知った。

**Comment by YU-TAYU** [comment]
- 作業：無事にmergeされたので、README.mdをさらに理解しやすいようにする。
- 思っていること：rankingの使い方に初心者は苦しんだので、使用例をつけようと考えている。

**Comment by YU-TAYU** [comment]
- 作業：README.mdのranking部分の使い方を補足した。
- 思っていること：他に補足した方が良い部分がないか確認しようと思う。

**Comment by YU-TAYU** [comment]
- 作業：属性名のURLをREADME.mdに追記
- 思っていること：I can't write English……

**Comment by YU-TAYU** [comment]
- 作業：pull request をした。
- 思っていること： English を勉強しよう。

**Comment by rust** [comment]
>  English を勉強しよう。

:+1: :+1:

**Comment by YU-TAYU** [comment]
- 作業：何をするか考えよう。
- 思っていること：直したかったところは直したため、今日はどこをやるか探してみながら考えてみよう。

**Comment by YU-TAYU** [comment]
- 作業：RakutenWebServiceは一区切りつけて、colorboxの使い方のサンプルをプルリすることに挑戦してみる。
- 思っていること：自分が使い方に困ったから、サンプルがGitHubにあると幸せになれるかもしれない。

**Comment by YU-TAYU** [comment]
- 作業：サンプルのhtmlを書く
- 思っていること：写真はサンプルのものをお借りするとして、サンプルのクリッカブルマップを作成する必要がありそう。コードは前に書いたものをアレンジすれば、最低限のことはできるかもしれない。

備考 :  sample_map.htmlとか…？

**Comment by YU-TAYU** [comment]
- 作業：英語でプルリ
- 思っていること：書き方に悩む

備考 : English is short sentenses. (paragraph), add noun.

**Comment by YU-TAYU** [comment]
- 作業：何をするか考える。
- 思っていること：また何か探してみる。

**Comment by YU-TAYU** [comment]
フィードバック：他の人のプルリを見る。diffの部分でコメントを追加することで補足できる。
