### ISSUE TITLE
Feedback: リポジトリ名から使用言語やチームを判別しやすくする

### ISSUE THREAD

**Issue by piroor** [clear-code/sezemi-2015#6]
イベント中、他の人がどのように実装しているのかを参考にするために「sezemi」でリポジトリを検索したものの、他の言語のチームの人のリポジトリだったためにあまり参考にならなかったり、メンターのリポジトリだったために読めるコードがなかった、といった事態が発生していた。

リポジトリ名に言語名かチーム名を含めておくと、参加者がリポジトリを検索して他の人のコードを参考にしやすくなるのではないか？

**Comment by kou** [comment]
こういうときは、同じ言語の人は目の前だったり隣だったりにいるので、直接GitHubアカウント名を聞くようにして欲しいです。そうすることで参加者間でリーダブルなコードについて相談するきっかけにつながると期待するからです。
