### ISSUE TITLE
OSS Hack Weekend: butanosuke: onepage-scroll: Javascript: 作業ログ

### ISSUE THREAD

**Issue by Butanosuke** [clear-code/sezemi-2015#60]
https://github.com/peachananr/onepage-scroll

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by Butanosuke** [comment]
- 作業：ドキュメントを読む。
- 思っていること：使ったことがないので不安はあるけど頑張るぞ！

**Comment by Butanosuke** [comment]
- 作業：サンプルを実行しコードを読んでいく。
- 思っていること：ドキュメントを読む限りかなり使いやすそうです。

**Comment by Butanosuke** [comment]
- 作業：クリックだけでなくスクロールでもアンカーの値が変わるようにしたい。
- 思っていること：スクロールしてからリロードすると最後にクリックしたところに飛んでしまうのでなんとかならないかなぁ。

**Comment by Butanosuke** [comment]
- 作業：自分の作ったページで実行してみる。
- 思っていること：使ってみてから考えよう。

**Comment by mumoshu** [comment]
順調そうですが、都度作業ログを書けると更に良いですね :+1:

https://github.com/clear-code/sezemi-2015/blob/master/oss-hack-weekend/scenario1.md#1030-開発

**Comment by mumoshu** [comment]
> 思っていること：使ってみてから考えよう。

これは結構よいプラクティスな気がするw

**Comment by mumoshu** [comment]
- 自分の作ったページで実行中
- どのファイルを使えばよいかわからない
  - .min.jsの意味最初はわからなかった（けど、調べてみてわかった）

**Comment by Butanosuke** [comment]
- 作業：オプションの設定でスクロールでもアンカーをつけられることが発覚。
- 思っていること：ドキュメントはしっかり読もう。

**Comment by Butanosuke** [comment]
- 作業：一番下から一番上へスクロールする（あるいはその逆）ときアンカーがおかしくなるので修正する。
- 思っていること：これは直したい。

**Comment by Butanosuke** [comment]
- 作業：アンカーを付与しているところを見つけたが一番上, 一番下の判定をどうするか悩む。
- 思っていること：どこかで保持していそうな感じはする。

備考：保持してありました。修正完了

**Comment by Butanosuke** [comment]
- 作業：pull requestのドキュメントを考える。
- 思っていること：英語は苦手なので頑張ろう。

**Comment by Butanosuke** [comment]
- 作業：教えてもらいながら少しコミットを変更しプルリクを出した。
- 思っていること：gitすごい。

**Comment by Butanosuke** [comment]
- 作業：Riotの使い方を学ぶため、サンプルアプリを作ってみる。
- 思っていること：使ったことがないものなので少し時間がかかるかも。

備考：参考にしたサイト
http://qiita.com/cognitom/items/8010e0779950df574cc9
http://qiita.com/cognitom/items/eb6d56485fe517ccd9ee

**Comment by Butanosuke** [comment]
- 作業：ふわっとわかったので、Issueを読んでいく。
- 思っていること：発展途上な感じなのでバグは結構ありそう。

**Comment by mumoshu** [comment]
@Butanosuke 「Riotの使い方を学ぶ」ときにどのような手段をとったか（ドキュメントをどのように読んだ、サンプルをどのように動かした、サンプルアプリをどのように作ってみた）ということも作業ログに書いておくと、あとで振り返りができてよさそうです！

**Comment by mumoshu** [comment]
振り返り
- Riot使いやすいのでどうしよう
  - 既存Issueからバグを探してみたらよいのではないか
  - バグ対応するときは、まずローカル環境でバグを再現するところから始めるとよいと思います

**Comment by Butanosuke** [comment]
- 作業：バグ再現しようとするもIssueと同じ状態にならない。
- 思っていること：jadeのversion違いとかもありえる？

備考：やろうとしてるIssueのURL
https://github.com/riot/riot/issues/938

**Comment by Butanosuke** [comment]
- 作業：バージョンアップが盛んなので、ドキュメントに書かれている文法で書けるのかどうかを実際にサンプルを作ってみて調べる。
- 思っていること：bug系のIssueはだいたい修正されていたのでbug探しをしよう。

**Comment by Butanosuke** [comment]
- 作業：index.mdを読み漁る。
- 思っていること：ドキュメント読めば読むほど使いたさ増す。

**Comment by Butanosuke** [comment]
- 作業：リンク切れのURLを見つけたので他にもないか探す。
- 思っていること：頻繁に更新されているので意外と多そう。

**Comment by Butanosuke** [comment]
- 作業：リンクが切れているわけではなく、マークダウンが相対パスになっているからGitHubからだと飛べないだけでした。
- 思っていること：GitHubではよくあることらしくびっくりした。
