### ISSUE TITLE
OSS Hack Weekend: tiwawan: Processing: Java: 作業ログ

### ISSUE THREAD

**Issue by tiwawan** [clear-code/sezemi-2015#63]
https://github.com/processing/processing

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by tiwawan** [comment]
- 作業：インストールした
- 思っていること：すんなり通ってしまった

**Comment by tiwawan** [comment]
- 作業：サンプルを動かす
- 思っていること：おおむね問題なく動いている
  備考：
  Complex3D
  NullPointerException
  java.lang.NullPointerException
  at jogamp.newt.driver.x11.ScreenDriver.collectNativeMonitorModesAndDevicesImpl(ScreenDriver.java:124)
  at jogamp.newt.ScreenImpl.collectNativeMonitorModes(ScreenImpl.java:630)
  at jogamp.newt.ScreenImpl.initMonitorState(ScreenImpl.java:566)
  at jogamp.newt.ScreenImpl.createNative(ScreenImpl.java:196)
  at jogamp.newt.ScreenImpl.addReference(ScreenImpl.java:235)
  at processing.opengl.PSurfaceJOGL.initScreen(PSurfaceJOGL.java:126)
  at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:105)
  at processing.core.PApplet.initSurface(PApplet.java:10241)
  at processing.core.PApplet.runSketch(PApplet.java:10128)
  at processing.core.PApplet.main(PApplet.java:9897)

**Comment by tiwawan** [comment]
- 作業：サンプルコード（SimpleRead）を動かす
- 思っていること：×を押しても閉じなくなった（シリアル通信用のコードをシリアルケーブルを繋がずに動かしたのでうまく動かなくて当然ではある）

**Comment by tiwawan** [comment]
- 作業：pdf関連のサンプルを動かす
- 思っていること：beginRecord()は便利そうだ
  pdfを作ったが生成したpdfファイルの在り処（すなわちサンプルスケッチの在り処）がよくわからない

**Comment by tiwawan** [comment]
- 作業：pdf関連のサンプルの在り処を探す
- 思っていること：サンプルスケッチの.pdeはあったが生成したpdfがない。なぜ？

**Comment by tiwawan** [comment]
- 作業：サンプルプログラムで生成したpdfを探す
- 思っていること：サンプルコードの.pdeが二箇所にあったらしい。一箇所には生成されていたがもう一箇所には生成されていなかった。

備考:
- LargePage.pdeのコメント

```
 * 
 * Saves one frame as a PDF with a size larger
 * than the screen. When PDF is used as the renderer
 * (the third parameter of size) the display window 
 * does not open. The file is saved to the sketch folder.
 */
```
- 俺が今まで見ていた場所：
  processing/java/libraries/pdf/examples
- pdfの在り処：
  processing/build/linux/work/modes/java/libraries/pdf/examples/

**Comment by tiwawan** [comment]
- 作業：pdf関連のサンプルを動かす
- 思っていること：
  スケッチフォルダを開く（Ctrl+K）という操作ができた。これで一発で生成したpdfが見れた。

**Comment by tiwawan** [comment]
- 作業：Pull Resquestの下書き
- 思っていること：以下のようでどうか。
  Environment: Ubuntu 14.0, Processing 3

I ran example of PDF library named "LargePage", and I had difficulty in finding the generated pdf file.
The comment in LargePage says "The file is saved to the sketch folder," but I think this is unfriendly because we usually open example from "File->Examples..." so we don't care about where sketch folder is.
Fortunately, we can open sketch folder by "Sketch->Show Sketch Folder." How about adding a comment about this?

**Comment by tiwawan** [comment]
- 作業：ウェブ上のExamples（https://processing.org/examples/）をコピペして実行
- 思っていること：動いた
  Math/Sine and cosineはProcessing 3+向けと書かれているが、2.2.1でも動いた。

**Comment by tiwawan** [comment]
- 作業：外部ツールのBootstrapを使ってみる
- 思っていること：これもGitHub上のOSSなのでコントリビュートできるかもしれない

**Comment by tiwawan** [comment]
- 作業：外部ツールのBootstrapを使ってみる
- examplesフォルダが空で使い方がわからない
  実行してみたところ.txt templetesが必要だと言われたが・・・？

**Comment by tiwawan** [comment]
- 作業：Issuesを眺める
- 思っていること：問題を発見するのは難しい

**Comment by tiwawan** [comment]
- 作業：Issuesで報告されているバグを再現する
- 思っていること：再現できませんでした。
  簡単なバグがそうそう放置されているわけがないよなあ

**Comment by tiwawan** [comment]
- 作業：Issuesを眺める
- 思っていること：レンダラー関連のバグが多いようである。環境に依存する部分が大きいのだろうか。Windowsで動かしていた時はちょくちょくうまく行かないことがあったがLinuxで作業しているとあまり不具合に出会わない。

**Comment by tiwawan** [comment]
- 作業：Processing上で日本語を入力してみる
- 思っていること：エディタ上では豆腐になってしまうが実行したらちゃんと日本語が表示されていた。
  エディタのフォントを日本語と英語で変えるようにすればうまく行く可能性が微レ存…？すでになにか方法があるかもしれないので調べる

**Comment by tiwawan** [comment]
- 作業：Processing上で日本語を入力してみる
- 思っていること：設定でフォントを変更したら日本語が入力できるようになった
  ツールバーがデフォルトで日本語なのに、エディターはデフォルトで日本語が表示できないのはアンバランスな感じがするので改善の可能性を探りたい

**Comment by tiwawan** [comment]
- 作業：Editorのコードを読む
- 思っていること：AWTやらSwingやら使っているらしい、難しい
- 備考：ファイルは"processing/java/src/processing/mode/java/JavaEditor.java"

**Comment by tiwawan** [comment]
- 作業：エディタのコードを読む
- 思っていること：すごく複雑である。クラスの構成図か何かないだろうか。JavaEditorクラスの親クラスにEditorクラスもあるようだがどっちを編集すればいいのか…？（たぶん前者）

**Comment by tiwawan** [comment]
- 作業：エディタのコードを読む
- 思っていること："processing/java/src/processing/mode/java/pdex/JavaTextArea.java"を編集すべきかもしれない

**Comment by tiwawan** [comment]
iso-8859

**Comment by tiwawan** [comment]
- 作業：JavaTextArea.javaを読む
- 思っていること：Eclipseを使い始めた。見やすい。

**Comment by tiwawan** [comment]
- 作業：JavaTextAreaPainter.javaを読む
- 思っていること：JEditTextArea.javaを継承している。これはProcessingの中で定義されたクラスではないようだ。

**Comment by tiwawan** [comment]
- 作業：JavaMode.javaを読む
- 思っていること：JavaModeクラスの中で"font"を検索したが見つからなかった。Modeクラスを継承しているようなのでそちらを読む。

**Comment by tiwawan** [comment]
- Mode.javaを読む
- 思っていること：getFontなるメソッドが見つかった。

```
...
  public Font getFont(String attribute) {
    return theme.getFont(attribute);
  }
...
```

さらに、

```
...
public void setupGUI() {
    try {
      // First load the default theme data for the whole PDE.
      theme = new Settings(Base.getContentFile("lib/theme.txt"));
...
```

これが核心に近い？
次はBaseクラスとtheme.txtを読む
- 備考：
  Mode.javaは　processing/app/src/processing/app　内にある。
  javaのコードを大きく分けて二箇所のフォルダで管理しているようだ。processing/app/src/processing/app内のファイルはJavaモードでもPythonモードでも使えるコードなのだろうと予想。

**Comment by tiwawan** [comment]
- 作業：Base.javaを読む
- 思っていること：Baseクラスは何も継承していない。ここが最深部のようだ（？）
  getContextFileについては、

```
  static protected File processingRoot;

  /**
   * Get reference to a file adjacent to the executable on Windows and Linux,
   * or inside Contents/Resources/Java on Mac OS X.
   */
  static public File getContentFile(String name) {
    if (processingRoot == null) {
      // Get the path to the .jar file that contains Base.class
      String path = Base.class.getProtectionDomain().getCodeSource().getLocation().getPath();
      // Path may have URL encoding, so remove it
      String decodedPath = PApplet.urlDecode(path);

      if (decodedPath.contains("/app/bin")) {  // This means we're in Eclipse
        if (Base.isMacOS()) {
          processingRoot =
            new File(path, "../../build/macosx/work/Processing.app/Contents/Java");
        } else if (Base.isWindows()) {
          processingRoot =  new File(path, "../../build/windows/work");
        } else if (Base.isLinux()) {
          processingRoot =  new File(path, "../../build/linux/work");
        }
      } else {
        // The .jar file will be in the lib folder
        File jarFolder = new File(decodedPath).getParentFile();
        if (jarFolder.getName().equals("lib")) {
          // The main Processing installation directory.
          // This works for Windows, Linux, and Apple's Java 6 on OS X.
          processingRoot = jarFolder.getParentFile();
        } else if (Base.isMacOS()) {
          // This works for Java 8 on OS X. We don't have things inside a 'lib'
          // folder on OS X. Adding it caused more problems than it was worth.
          processingRoot = jarFolder;
        }
        if (processingRoot == null || !processingRoot.exists()) {
          // Try working directory instead (user.dir, different from user.home)
          System.err.println("Could not find lib folder via " +
            jarFolder.getAbsolutePath() +
            ", switching to user.dir");
          processingRoot = new File(System.getProperty("user.dir"));
        }
      }
    }
    return new File(processingRoot, name);
  }
```

Fileを返す（設定をデコードしている訳ではない）。設定ファイルのフォルダの環境ごとの違いを吸収するのが主な目的のメソッドだったようだ。

**Comment by tiwawan** [comment]
- 作業：theme.txtを読む
- 思っていること：拡張子がtxtなのが面白い。  

```
editor.gutter.text.font = processing.mono,plain,11
```

これか？
ビルドした時点ですでにメニューバーが日本語になっていたが、それをどこでやっているのか探る。
- 備考：theme.txtの場所は  
  processing/build/shared/lib  
  さらに、  
  processing/build/shared/lib/fonts  
  にいくつかフォントが入っている。

**Comment by tiwawan** [comment]
- 作業：Processingの設定画面を見てみる
- 思っていること：
  ![screenshot from 2015-07-12 11 08 12](https://cloud.githubusercontent.com/assets/4486076/8636056/a7f1c218-2886-11e5-9edc-b96f37cf3ca1.png)
  「複雑なテキスト入力を有効にする」にチェックしたら逆に日本語が入力できなくなった

**Comment by tiwawan** [comment]
- 作業：preference関連のコードを探す
- 思っていること：先ほどのコメントの「複雑なテキスト入力を有効にする」の件はバグの可能性があるのでなぜそうなっているのか原因を探るつもりである。  
  Base.java

``` java
static private void createAndShowGUI(String[] args) {
 ...
    // Load the languages
    Language.init();

    // run static initialization that grabs all the prefs
    Preferences.init();
```

Language, Preferencesが関係していそうだ。

**Comment by nabedge** [comment]
なんかすごい。コードの海にディープダイビングしてる！

**Comment by tiwawan** [comment]
- 作業：main関数を探す
- 思っていること：プログラムを実行してから呼び出される順に関数を見ていくと見通しがいいのではないかと思いmain関数をまず探そうと思った。  
  Base.java l150

``` java
  static public void main(final String[] args) {
    EventQueue.invokeLater(new Runnable() {
        public void run() {
          try {
            createAndShowGUI(args);
          } catch (Throwable t) {
            showBadnessTrace("It was not meant to be",
                             "A serious problem happened during startup. Please report:\n" +
                             "http://github.com/processing/processing/issues/new", t, true);
          }
        }
    });
  }
```

Baseクラス内にあるようだ。
直前のコメントに貼ったcreateAndShowGUI()は約2番めに呼ばれる関数であることがわかった。

**Comment by tiwawan** [comment]
- 作業：Language.javaを読む
- 思っていること：createAndShowGUI()内で呼ばれているLanguage.init()の内容を知りたい。  
  Language.java

``` java
  /** Singleton constructor */
  static public Language init() {
    if (instance == null) {
      synchronized (Language.class) {
        if (instance == null) {
          instance = new Language();
        }
      }
    }
    return instance;
  }
```

Singleton constructorとは↓のことか？OSSでデサインパターンの知識もつけて圧倒的成長:muscle::muscle::muscle:
https://ja.wikipedia.org/wiki/Singleton_%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3  

真のコンストラクタは以下  
Base..java l51

```
  private Language() {
    String systemLanguage = Locale.getDefault().getLanguage();
    language = loadLanguage();
    boolean writePrefs = false;

    if (language == null) {
      language = systemLanguage;
      writePrefs = true;
    }

    // Set available languages
    languages = new HashMap<String, String>();
    for (String code : listSupported()) {
      Locale locale = Locale.forLanguageTag(code);
      languages.put(code, locale.getDisplayLanguage(locale));
    }

    // Set default language
    if (!languages.containsKey(language)) {
      language = "en";
      writePrefs = true;
    }

    if (writePrefs) {
      saveLanguage(language);
    }

    // Get bundle with translations (processing.app.language.PDE)
    //bundle = ResourceBundle.getBundle(Language.FILE, new Locale(this.language), new UTF8Control());
    try {
      bundle = new LanguageBundle(language);
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
```

Locale.getDefault().getLanguage()が、自動で言語を選択するためのコードであるようだ。これがあったから自分の環境ではメニューバーが日本語になっていたと予想。

**Comment by tiwawan** [comment]
- 作業：Localeについて知る
- 思っていること：LocaleはProcessingのクラスではなくjava.util.Localeであるようだ。
  http://docs.oracle.com/javase/jp/6/api/java/util/Locale.html  

> Locale オブジェクトは、地理的、政治的、または文化的に特定の地域を表しています。ある操作で Locale を必要とするタスクがある場合、その操作をロケールに依存する操作といいます。 この場合、情報は Locale によりユーザーに合わせて調整されます。たとえば、数値を表示するのは、ロケールに依存する操作です。 この数値は、ユーザーの国や地域、文化の習慣や規則に従ってフォーマットする必要があります。
> 
> Locale オブジェクトを作成するには、このクラスのコンストラクタを使用します。
> 
> ```
> Locale(String language)
> Locale(String language, String country)
> Locale(String language, String country, String variant)
> ```
> 
> 言語の引数は、有効な ISO 言語コードです。これらのコードは、ISO-639 で定義される 2 桁の小文字です。

---

> static Locale     getDefault()
>          Java Virtual Machine のこのインスタンスに対して、デフォルトロケールの現在の値を取得します。

**Comment by tiwawan** [comment]
- 作業：loadLanguage, saveLanguage
- 思っていること：  
  Language.java  

``` java
  static protected final String PREF_FILE = "language.txt";
  static protected final File prefFile = Base.getSettingsFile(PREF_FILE);
  ...
  /** Read the saved language */
  static private String loadLanguage() {
    try {
      if (prefFile.exists()) {
        String language = PApplet.loadStrings(prefFile)[0];
        language = language.trim().toLowerCase();
        if (language.trim().length() != 0) {
          return language;
        }
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
    return null;
  }


  /**
   * Save the language directly to a settings file. This is 'save' and not
   * 'set' because a language change requires a restart of Processing.
   */
  static public void saveLanguage(String language) {
    try {
      Base.saveFile(language, prefFile);
    } catch (Exception e) {
      e.printStackTrace();
    }
    Base.getPlatform().saveLanguage(language);
  }
```

language.txtから設定をとっているようだ

**Comment by tiwawan** [comment]
- 作業：Preferencesについて知る
- 思っていること：  
  Preferences.java

``` java
public class Preferences {
  // had to rename the defaults file because people were editing it
  static final String DEFAULTS_FILE = "defaults.txt"; //$NON-NLS-1$
  static final String PREFS_FILE = "preferences.txt"; //$NON-NLS-1$

  static HashMap<String, String> defaults;
  static HashMap<String, String> table = new HashMap<String, String>();
  static File preferencesFile;


  static public void init() {
    // start by loading the defaults, in case something
    // important was deleted from the user prefs
    try {
      // Name changed for 2.1b2 to avoid problems with users modifying or
      // replacing the file after doing a search for "preferences.txt".
      load(Base.getLibStream(DEFAULTS_FILE));
    } catch (Exception e) {
      Base.showError(null, "Could not read default settings.\n" +
                           "You'll need to reinstall Processing.", e);
    }

...

  static public void load(InputStream input) throws IOException {
    HashMap<String, String> platformSpecific = new HashMap<>();

    String[] lines = PApplet.loadStrings(input);  // Reads as UTF-8
    for (String line : lines) {
      if ((line.length() == 0) ||
          (line.charAt(0) == '#')) continue;

      // this won't properly handle = signs being in the text
      int equals = line.indexOf('=');
      if (equals != -1) {
        String key = line.substring(0, equals).trim();
        String value = line.substring(equals + 1).trim();
        if (!isPlatformSpecific(key, value, platformSpecific)) {
          table.put(key, value);
        }
      }
    }
    // Now override the keys with any platform-specific defaults we've found.
    for (String key : platformSpecific.keySet()) {
      table.put(key, platformSpecific.get(key));
    }
  }
```

preferences.txtの中身を=の左右で切ったペアをtableの中に放り込んでいるらしい

**Comment by tiwawan** [comment]
- 作業：preferences.txtを読む
- 思っていること：

```
buttons.hide.image=false
chooser.files.native=false
console.auto_clear=true
console.font.size=12
console.length=500
console.lines=4
contribution.backup.on_install=true
contribution.backup.on_remove=true
editor.caret.blink=true
editor.caret.block=false
editor.divider.size=0
editor.font.family=Takaoゴシック
editor.font.size=12
editor.indent=true
editor.input_method_support=true
editor.keys.alternative_cut_copy_paste=true
editor.keys.home_and_end_travel_far=false
editor.keys.home_and_end_travel_smart=true
editor.keys.shift_backspace_is_delete=false
editor.laf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
editor.smooth=true
editor.tabs.expand=true
editor.tabs.size=2
editor.token.comment1.style=#666666,plain
editor.token.comment2.style=#666666,plain
editor.token.function1.style=#006699,plain
editor.token.function2.style=#006699,plain
editor.token.function3.style=#669900,plain
editor.token.function4.style=#006699,bold
editor.token.invalid.style=#666666,bold
editor.token.keyword1.style=#33997e,plain
editor.token.keyword2.style=#33997e,plain
editor.token.keyword3.style=#669900,plain
editor.token.keyword4.style=#d94a7a,plain
editor.token.keyword5.style=#e2661a,plain
editor.token.keyword6.style=#33997e,plain
editor.token.label.style=#666666,bold
editor.token.literal1.style=#7D4793,plain
editor.token.literal2.style=#718a62,plain
editor.token.operator.style=#006699,plain
editor.untitled.prefix=sketch_
editor.untitled.suffix=yyMMdd
editor.watcher=true
editor.window.height.default=600
editor.window.height.min=500
editor.window.width.default=500
editor.window.width.min=400
examples.processing.mode.java.JavaMode.visible=Examples:Examples/Demos:Examples/Topics/Create Shapes:Examples/Topics/Cellular Automata:Examples/Topics/Drawing:Examples/Topics:Examples/Books:Examples/Topics/Textures:Examples/Topics/Simulate
export.application.embed_java=true
export.application.fullscreen=false
export.application.stop=true
export.delete_target_folder=true
instance_server.key=0.818758459940237
instance_server.port=41774
last.sketch.count=0
last.sketch.mode=processing.mode.java.JavaMode
last.sketch.restore=true
launcher=xdg-open
mode.last=processing.mode.java.JavaMode
pdex.autoSave.autoSaveByDefault=true
pdex.autoSave.autoSaveEnabled=false
pdex.autoSave.promptDisplay=true
pdex.autoSaveInterval=5
pdex.completion=false
pdex.completion.trigger=false
pdex.dbgOutput=false
pdex.errorCheckEnabled=true
pdex.importSuggestEnabled=true
pdex.warningsEnabled=true
pdex.writeErrorLogs=false
platform.auto_file_type_associations=true
preproc.color_datatype=true
preproc.enhanced_casting=true
preproc.output_parse_tree=false
preproc.save_build_files=false
preproc.substitute_floats=true
preproc.substitute_unicode=true
preproc.web_colors=true
proxy.host=
proxy.http.host=
proxy.http.port=
proxy.https.host=
proxy.https.port=
proxy.port=
proxy.socks.host=
proxy.socks.port=
recent.count=10
run.display=1
run.options=
run.options.memory=false
run.options.memory.initial=64
run.options.memory.maximum=256
run.present.bgcolor=#666666
run.present.stop.color=#cccccc
run.window.bgcolor=#DFDFDF
sketchbook.path=/home/tiwawan/sketchbook
sketchbook.path.three=/home/tiwawan/sketchbook
toolbar.hide.image=false
update.check=true
update.id=5274890482117385628
update.last=1436666801566
```

input_method_supportが設定ウインドウの「複雑なテキスト入力を有効にする」に相当している？要検証
- 備考：
  preferences.txtはホームフォルダの下の.processingフォルダ内にある。

**Comment by tiwawan** [comment]
- 作業：input_method_supportが設定ウインドウの「複雑なテキスト入力を有効にする」に相当しているか検証
- 思っていること  
  設定ウインドウ上で「複雑なテキスト入力を有効にする」のチェックを外す->input_method_supportがtrueからfalseになった。  
  逆にinput_method_supportをtrueに書き換えてからProcessingを起動すると「複雑なテキスト入力を有効にする」にチェックが入っていた。

**Comment by tiwawan** [comment]
- 作業：JEditTextArea.javaを読む
- 思っていること：  
  grepした結果JEditTextArea内でinput_method_supportを使っているらしいことがわかった。  
  JEditTextArea.java

```
  /**
   * Inline Input Method Support for Japanese.
   */
  public InputMethodRequests getInputMethodRequests() {
    if (Preferences.getBoolean("editor.input_method_support")) {
      if (inputMethodSupport == null) {
        inputMethodSupport = new InputMethodSupport(this);
      }
      return inputMethodSupport;
    }
    return null;
  }
```

**Comment by tiwawan** [comment]
- 作業：input_method_supportおよびgetInputMethodRequestsを含むソースを探す。
- 思っていること：

```
$ grep -r getInputMethodRequests --include='*.java'
app/src/processing/app/syntax/JEditTextArea.java:  public InputMethodRequests getInputMethodRequests() {
```

```
tiwawan@tiwawan-X200MA:~/Documents/processing$ grep -r input_method_support --include='*.java'
app/src/processing/app/syntax/JEditTextArea.java:    if (Preferences.getBoolean("editor.input_method_support")) {
app/src/processing/app/ui/PreferencesFrame.java:    Preferences.setBoolean("editor.input_method_support", inputMethodBox.isSelected()); //$NON-NLS-1$
app/src/processing/app/ui/PreferencesFrame.java:    inputMethodBox.setSelected(Preferences.getBoolean("editor.input_method_support")); //$NON-NLS-1$
```

getInputMethodRequests()が定義されただけでどこでも呼ばれていない？？？

**Comment by tiwawan** [comment]
- 作業：getInputMethodRequestsをコメントアウトしてビルド
- 思っていること：BUILD SUCCESSFULだった。やはりgetInputMethodRequestsはどこでも使われていないのか？
  コメントアウトしてから実行したらなぜか「複雑なテキスト入力を有効にする」のオンオフによらず常に日本語入力ができるようになってしまった。もしかしたらProcessingのバグではなくこちらのOSの問題か何かなのかもしれない…

**Comment by tiwawan** [comment]
- 作業：getInputMethodRequestsのコメントアウトを元に戻して実行
- 思っていること：日本語が入力できないバグが再現できた。getInputMethodRequestsがなにかしら関わっていそうだが呼びだされている場所がわからない。

**Comment by tiwawan** [comment]
- 作業：getInputMethodRequests() の真偽判定を逆転させて実行
- 思っていること  
  JEditTextArea.java

```
  public InputMethodRequests getInputMethodRequests() {
    if (!Preferences.getBoolean("editor.input_method_support")) {
      if (inputMethodSupport == null) {
        inputMethodSupport = new InputMethodSupport(this);
      }
      return inputMethodSupport;
    }
    return null;
  }
```

真偽判定を逆転させて（!Preferences.getBoolean("editor.input_method_support")）再起動させると、逆転させる前と逆の（つまり期待通りの）結果が得られた。  
再起動の問題かもしれないと考えたが、逆転させないと再起動させても動作が期待と逆のままだった。

**Comment by tiwawan** [comment]
https://github.com/clear-code/sezemi-2015/issues/63#fullscreen* 作業：getInputMethodRequests()の中にバグを入れて呼び出し元を探る。
- 思っていること：  
  ゼロ除算のバグを入れたコード

```
  public InputMethodRequests getInputMethodRequests() {
    int a=1/0;
    if (Preferences.getBoolean("editor.input_method_support")) {
      if (inputMethodSupport == null) {
        inputMethodSupport = new InputMethodSupport(this);
      }
      return inputMethodSupport;
    }
    return null;
  }
```

エラーメッセージ
![screenshot from 2015-07-12 15 56 51](https://cloud.githubusercontent.com/assets/4486076/8636792/e6eeddc0-28ae-11e5-8add-2dc443a0b3e0.png)

Processing外のInputMethodAdapterとかいうところから呼びだされている。
getInputMethodRequests()はorg.gjt.sp.jedit.textarea.TextAreaからオーバーロードしたメソッドだったらしい。  
たぶん内部的に使われているのだろう:pensive:

**Comment by tiwawan** [comment]
- 作業：InputMedhodSupportとは何か探る
- 思っていること：getInputMethodRequests()内で作られているInputMethodSupportとは一体何なのか知りたいにゃん:cat:  
  InputMethodSupportはProcessingのコードらしい。  
  http://processing.org/reference/javadoc/everything/processing/app/syntax/im/InputMethodSupport.html  
  まじか〜〜〜〜〜〜〜〜〜〜

**Comment by kou** [comment]
お疲れ様でしたにゃん :cat:
