### ISSUE TITLE
OSS Hack Weekend: linerlock: *** 作業ログ (Scala)

### ISSUE THREAD

**Issue by takahisa** [clear-code/sezemi-2015#64]
作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by takahisa** [comment]
- 作業　knockoff (scala向けmarkdown parserのインストール)

git cloneしてきたソースコードをsbtでビルドしている

**Comment by takahisa** [comment]
- インストールに失敗した

useGpgが無いというエラー、build.sbt内で起きているのでおそらくsbt-pluginがはいっていない

**Comment by takahisa** [comment]
http://www.scala-sbt.org/sbt-pgp/
addSbtPlugin("com.typesafe.sbt" % "sbt-pgp" % "0.8.3")
を~/.sbt/0.13/plugins.sbtに追加することで解決した

**Comment by takahisa** [comment]
*ビルド&テストに成功した

**Comment by takahisa** [comment]
試しにmarkdown入力を食わせてみたらindentationがされていない(X)HTMLが出てきたのでこれも直したい

**Comment by mumoshu** [comment]
> addSbtPlugin("com.typesafe.sbt" % "sbt-pgp" % "0.8.3")
> を~/.sbt/0.13/plugins.sbtに追加することで解決した

素晴らしいですね :+1:
そして、これコントリビュートできるポイントかもしれないですね（そもそも~/.sbt/0.13/plugins.sbtという個人設定をいじらないとビルドできないってどうなんだろう、他の人は気付けるのか)

**Comment by mumoshu** [comment]
(他の方への参考) knockoffのGitHubレポジトリはこちらですね https://github.com/tristanjuricek/knockoff

**Comment by takahisa** [comment]
```
- foo
- bar
```

というmarkdownから

```
<li>foo
</li>

<li>bar
</li>
```

という出力が得られるが、閉じ括弧前の改行は含めないように変更したい。
参考: http://spec.commonmark.org/0.19/

**Comment by linerlock** [comment]
ダメダメ英語力を振り絞ってissueを立てました。
https://github.com/tristanjuricek/knockoff/issues/44

**Comment by mumoshu** [comment]
@linerlock (/ω・＼)ﾁﾗｯ 作業ログあると振り返りに役立ちます！ぜひ書いていただけるとうれしいです

**Comment by takahisa** [comment]
pullrequestを出しました

**Comment by rizaudo** [comment]
:tada: :clap:

**Comment by mumoshu** [comment]
素晴らしい! :tada:

**Comment by cosmo0920** [comment]
> 素晴らしいですね :+1:
> そして、これコントリビュートできるポイントかもしれないですね（そもそも~/.sbt/0.13/plugins.sbtという個人設定をいじらないとビルドできないってどうなんだろう、他の人は気付けるのか)

横からスミマセン、こちらも確実にPull Requestできる箇所だと思います。
sbtのドキュメントにプロジェクト固有のsbt-pluginを設定できるとの記述があります。
http://www.scala-sbt.org/0.13.5/docs/Extending/Plugins.html#using-a-binary-sbt-plugin

是非こちらもPull Requestに挑戦してみてください！

**Comment by takahisa** [comment]
簡単にPRを書いて出しておきました。
