### ISSUE TITLE
OSS Hack Weekend: kentya6 (学生サポーター): Alamofire: Swift 作業ログ

### ISSUE THREAD

**Issue by kentya6** [clear-code/sezemi-2015#67]
https://github.com/Alamofire/Alamofire

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by kentya6** [comment]
- 作業 : [Alamofire](https://github.com/Alamofire/Alamofire)リポジトリをクローンして実行
- 思っていること : iOSシミュレータで問題なく実行できた

**Comment by kentya6** [comment]
- 作業 : テストコード実行
- 思っていること : TargetをiOS Exampleにして、Cmd+UでXCTestを実行し、問題なくテストが通ったことを確認した

**Comment by kentya6** [comment]
- 作業 : プルリク内容の調査(データアップロードの際にfileNameをあえて指定しない状況があるのかどうか)
- 思っていること : [Multipart-Uploadに関するプルリク](https://github.com/Alamofire/Alamofire/pull/569)では、既存のメソッドの`fileName`パラメータをオプショナルにすればいけるから、既存のメソッドをリファクタリングしたほうがいいかなーと言っている。
  一方で、fileNameをオプショナルにした際にサーバ側としては特にメリットを感じないので、fileNameを指定しない(nilにする)状況というのは、かなり稀ではないかという意見。
  オプショナル対応にするプルリクを送れるけど、fileNameをあえて指定しない状況というのがあるのかが分からない。

メンターの方に質問したところ、fileNameがどうでもいいというシチュエーションは結構あるけど、その場合は"image.jpg"のように適当な値をつけて送るので、アプリケーション側でnilを指定する場合に対応する必要性はあまり感じないとのこと。

**Comment by kentya6** [comment]
- 作業 : プルリク内容の決定
- 思っていること : 上記のfileNameに関するプルリクエストは必要ないと判断したため、別の内容を探した。
  Alamofireのサンプルを実行してみると、UploadやDownloadに関するサンプルがないことに気づいた。
  UploadやDownloadは機能ベースでは実装されていてXCTestでテストが書かれているので、それならばUploadやDownloadに関する機能のサンプルを加えればいいと判断した。
  Uploadのサンプルとしたときに、どこにアップロードすればいいか分からなかったので(XCTestでは変換したバイトデータが期待値とあっているかで検証していた)、まずはDownloadのサンプルを作ることにした。

**Comment by kentya6** [comment]
- 作業 : サンプル構成の決定
- 思っていること : 既存のAlamofireサンプルでは、GET, POST, PUT, DELETEの4つのサンプルがあり、それぞれのレスポンスのHeaderとBodyをUITableViewで表示するというものだった。
  今回実装するDownloadサンプルはGETリクエストだが、ファイルをダウンロードするサンプルにするので特にBodyの内容が表示されるということがない。
  ダウンロードしたデータのバイトデータを出力するのは行数が長くなるので、ファイル名をBodyに出力する構成にした。
  構成としては、
1. 一時的なファイル保存パスを設定
2. ファイルのダウンロード
3. ダウンロードしたファイル名の出力
4. ダウンロードしたファイルの削除

でいく予定。
既存のサンプルコードの設計思想を崩さないように意識してサンプルを実装する。

**Comment by kentya6** [comment]
- 作業 : サンプル機能の実装
- 思っていること : 上記の1~4の流れを実現するプログラムを書いたので、後はAlamofireのサンプルに組み込むだけになった。
  現状のサンプルだと、Bodyを表示するUITableViewCellに文字列形式でレスポンスを出力するようになっていたので、Downloadサンプルではそのまま適用できないことがわかった。
  そのため、Download系のサンプルの場合はUITableViewCellに表示する内容を切り替えるために、どの種類のリクエストなのか判別する必要があったが、現状のAlamofireサンプルだとその検出ができない。
  そのため、新しく遷移元のidentifierを保存する変数を設けて識別するようにした。

**Comment by kentya6** [comment]
作業 : サンプル機能の実装完了(要リファクタリング?)
思っていること : Alamofireのサンプルコードに新しくDownloadリクエストを追加し、ボタンを押すとUIを変更せずにDownloadができていることを示すようなサンプルプログラム(ダウンロードしたファイル名を表示)ができた。
サンプルを組み込んで実装ができたので、プルリクエストを出す準備はできたけど、まだコード整形が終わってないので、少し整形してからコミットしてプッシュ、プルリクエストを送ろうと思う。

**Comment by kentya6** [comment]
作業 : サンプル機能内容の変更
思っていること : メンターの方にチェックしてもらったところ、ダウンロードができたことを示すためにファイル名を出力するのではなく、ファイルの内容を出力したほうがよいとのことだったので、ファイルの内容を出力する方針に切り替える。

**Comment by kentya6** [comment]
作業 : サンプル機能の実装完了
思っていること : メンターの方のアドバイスの通り、ファイル名の出力ではなく、ファイル内容を出力する実装にした。
これで機能としては終わったが、従来のサンプルコードとAlamofireのリクエスト形式が異なるのでsegue identifierを保持する変数を作成したこともあり、少々従来のサンプルコードに比べて可読性が下がったと感じている。
もう少しスマートな記述がないものか考え中。

**Comment by kentya6** [comment]
作業 : サンプルコードをよりシンプルに
思っていること : サンプルコードということで、他の部分の例にならってエラーハンドリングをなくしたり、一度しか使用しない変数を削除することで、少し見やすいコードになった。

**Comment by kentya6** [comment]
作業 : Pull Requestを送る
メッセージ : I added download request sample in sample project.
To recognize segue transition, I added `segueIdentifier` variable.

**Comment by gfx** [comment]
I've added a request sample on `download()` in the sample project.

とかかなあ。 冠詞は忘れないように…。

**Comment by kentya6** [comment]
ありがとうございます！

**Comment by kentya6** [comment]
おかげでPRを出せました！
https://github.com/Alamofire/Alamofire/pull/579
