### ISSUE TITLE
OSS Hack Weekend：pull request紹介

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#73]
メンターは自分が最終チェックをしたissue/pull requestを紹介してください。

ここにコメントで書いてもらったissue/pull requestをメンターに紹介してもらうので、ここには自分が紹介するときにヒントに使える情報だけ書いていれば十分です。

**Comment by rust** [comment]
https://github.com/rakuten-ws/rws-ruby-sdk/pull/23
https://github.com/rakuten-ws/rws-ruby-sdk/pull/24

プログラミング歴3ヶ月だけど、前回のBeginnersで見つけた問題を今回解決しているのはすごくいいことだと感じました。

**Comment by edvakf** [comment]
https://github.com/tristanjuricek/knockoff/pull/45

**Comment by edvakf** [comment]
https://github.com/tototoshi/scala-csv/pull/47

**Comment by okkez** [comment]
- https://bugs.ruby-lang.org/issues/11345

Ruby のドキュメントに関する報告。

**Comment by okkez** [comment]
- https://github.com/itamae-kitchen/itamae/pull/144

yak shaving になりかけていたのを、そうならないように冷静に判断していたのがよかったです。

**Comment by gfx** [comment]
（最終チェックした成果物ではないですが / trackbackしないようにリンクにはしませんが）
- SwiftHTTP/pull/133 by @gates1de - HTTP client実装ではエラーハンドリングに手を抜きがちなので、そこの不備を発見できてよい
- SwiftHTTP/pull/134 by @HSKKOU - HTTP clientのテストは手を抜きがちなので、それをmockをつかってオフラインで実行できるようにするのは大変よい

**Comment by piroor** [comment]
https://github.com/ffaker/ffaker/pull/216
より良いやり方を議論（ https://github.com/clear-code/sezemi-2015/issues/41 ）して、そのエッセンスが詰まったPRになっている。

https://github.com/Alamofire/Alamofire/pull/579
既存のものを参考に機能追加

https://github.com/shuyuhey/tmux/commit/c95bdbeb7a36dd03d203c3051650ef8680a9fc0e
メールでのやり取り

**Comment by nabedge** [comment]
https://github.com/nabedge/mixer2-sample/pull/26
６月末のhack4beginnersのときにforkしたリポジトリのときよりも、
本家のほうでコードが変更されている、というワナをよく乗り越えましたw。
（OSS開発ではよくあることです）

次からは、masterブランチではなく、トピック用のブランチ（この場合はissue-26とかいう名前）でプルリクを出せるようにしましょう！

**Comment by mumoshu** [comment]
@Butanosuke さんの [Make the page number go between 1 and the last page number. by Butanosuke · Pull Request #268 · peachananr/onepage-scroll](https://github.com/peachananr/onepage-scroll/pull/268) ブラウザのアドレスバーを注意深く見てないと気づけないバグを発見して修正したプルリ。バグフィックスぷるりの説明に、問題の概要、次に具体例…というような丁寧な内容を書いてくれました。これなら作者にも伝わる！  :+1:

@Sesta さんの [Align pagination in the middle by Sesta · Pull Request #267 · peachananr/onepage-scroll](https://github.com/peachananr/onepage-scroll/pull/267)
デモアプリを見るだけでは気づけないバグを発見して修正したプルリ。見た目の修正なので、変更内容をスクショで説明。「英語を頑張らなくても、わかりやすいぷるりの説明は書ける！」ということを示してくれました :+1:

**Comment by cesare** [comment]
@yokoto さん
- https://github.com/seattlerb/minitest/pull/563
- https://github.com/clear-code/sezemi-2015/issues/49#issuecomment-120681587

当初のコミットに、無関係な更新が入っていたのに気づいて、対処方法を探して、要らない更新を消してから PR にしたのが良かったです。

**Comment by noriki-nakamura** [comment]
- @shopetan さん
  - https://github.com/scikit-learn/scikit-learn/pull/4951
  - コミュニティとの意思疎通が大変(そう)だった。
  - 英語は気負わず `Broken English` でも良いので、意味が通じるように頑張って欲しい。
- @satoichiki さん
  - https://github.com/rakuten-ws/rws-php-sdk/issues/21
  - Pull Request ではないけど、利用してみて素直な改善提案が個人的に共感が持てた。
    - 個人的にはCSS除去をする方法を検討するのが難しいような気がした。

**Comment by Matsue** [comment]
@S-Shimotori さん
Fix access value in document: ttps://github.com/Quick/Quick/pull/344
Weekend最初のPR！:confetti_ball:

Fix same name test function: ttps://github.com/Quick/Quick/pull/345
動的に生成されるテストコードメソッドの名前重複を解決。コードを読み込んでの修正、なおかつ関連したissueに挙げられていたRPよりも、より良い案を提案していてよかったです！:tada:

@mthiroshi さん
PRには至りませんでしたが、Androidにおける外部アプリ(Amazon MP3)との連携でExceptionの発生元がわからない状況で着実に根強くデバッグを実行していて素晴らしいと思いました。もうすこしでPR!

**Comment by kyuns** [comment]
https://github.com/masahino/mruby-nkf/pull/1
@neisunwereさん
（PR最終チェック者ではないですが）
自分が使いたいmruby製のエディタ[rumin](https://github.com/ncq/rumin)をビルドする途中で気づいたmruby-nkfのバグを素直に修正してPRだしている点が良いと思いました。またエディタのほうでもバグがあるっぽいので引き続き継続してPR出せそうなので頑張って欲しいと思いました。

**Comment by suzukiyuichi** [comment]
@rizaudo さん

Emacs: C/EmacsLisp　makefile　生成部分の修正。mercurialなのでログ貼り付け
以下

```
hogehoge@Rizaudo:~/project/yatex% hg branch default
marked working directory as branch default
(branches are permanent and global, did you want a bookmark?)
hogehoge@Rizaudo:~/project/yatex% hg log -v yatexmth.el
changeset:   417:1ab1b9ba8698
branch:      dev
parent:      413:368a86a179ff
user:        HIROSE Yuuji <yuuji@gentei.org>
date:        Sun Jul 12 10:03:55 2015 +0900
files:       yatexmth.el
description:
Remove superfluous string in autoload line
```

twitterで開発者と直接やり取りしたところがすばらしいと思いました。
https://twitter.com/hiroseyuuji/status/620037680613621760

あと日本語の変な和訳の修正。

私も含め日本人でも日本語で表現するのが苦手な人も多いと思うので、プログラム以外ではなく言語ファイル直すところは今後もがんばってほしいと思います。

**Comment by repeatedly** [comment]
- @neisunwere : masahino/mruby-nkf/pull/1

ruminのインストールの過程で，mruby-nkfが最新のmrubyの変更に追従出来てないことに気づいて，その修正をPR．また，PRしたことをruminのissueで報告し，インストールで問題が起きることを報告．(すでにkyunsさんが書かれてますが，一応最終確認したので報告)
- @prpr-man

mikutterがglibのバージョンの関係でセグフォで死ぬ問題．
mikutterがgithubではなく独自のRedmineで管理していて，アカウントも登録性のため，ドキュメントやバグ報告などはまだ出来てない． https://github.com/clear-code/sezemi-2015/issues/34#issuecomment-120589302 のように準備は出来ているので，アカウントが出来たらすぐ報告は可能．

その過程で，ruby-gnomeのREADMEが普通のtextだったのをmarkdownにするPRは送り済み: ruby-gnome2/ruby-gnome2/pull/484

**Comment by rust** [comment]
- @hoshitocat さん
  - Ransack/pull/562
  - 修正したいことは事前に決めていたようですが、そのためにひたすら頑張ってコードを読んでいた。ぎりぎりになったがなんとかPR出せたこと。
- @totzYuta
  - tw/pull/67
  - 初日は Sinatra を対象としていたが方針転換してCUIクライアントの機能追加に。こちらも最後の最後にPRを出すまでいけた。

**Comment by nabedge** [comment]
- https://twitter.com/yusuke/status/620082572383490049
- https://twitter.com/sezemi_seplus/status/620087496139935744

**Comment by zonuexe** [comment]
- @shunsuke227ono
  - 未PR https://github.com/clear-code/sezemi-2015/issues/39#issuecomment-120593775
  - Rakeやminitestにまたがる問題で、わかりにくいメッセージを安易に直そうとせずいろいろ考えている

**Comment by gfx** [comment]
- https://github.com/stepmania/stepmania/pull/721 by @HirotakaTakayama
- https://github.com/awslabs/s2n/pull/141 by @ramesses2nd

**Comment by kohei-takata** [comment]
https://github.com/makky3939
https://github.com/facebook/react/graphs/contributors
Reactに4つPRを出し、4つマージ。
contributorsの88位に。
