### ISSUE TITLE
OSS Hack 4 Beginners：メンターのOSS開発参加初期の頃のエピソード

### ISSUE THREAD

**Issue by kou** [clear-code/sezemi-2015#9]
先輩の経験談が学生の参考になるかもしれない。

もし、今の自分だったり、今の仕事に活きていることがあるならそれを入れてもらうとよいかもしれない。

質疑応答の時間が余った場合はここにあるエピソードを順に本人に紹介してもらう。

**Comment by nabedge** [comment]
- 俺がいま量産しているコードは実はクソコードなのではないか？という疑心暗鬼にさいなまれることがある
- それでも長く継続していると、ポツリポツリと突然プルリクが来たりする。
- ヘビーユーザーらしき人が質問とともに添付したソースコードにとあるプロジェクト名or会社名が書いてあったりして、ああ、いまそこに来てるあの会社かぁ、とか思ってニヤニヤしたりする。

**Comment by tnakamot** [comment]
最初に飛び込んだプロジェクトがOpenOffice.orgであった。まだOpenOffice.orgのバージョン1がリリースされたばかりの頃で、コードは1000万行以上あるのにビルドシステムはあまり洗練されておらず、dependencyを解決するだけで相当な時間がかかった。当時の自作マシンでCPUはPentinum 3の800 MHzぐらいだったと思うが、コンパイルだけで丸一日。夜にコンパイル回して、朝みたらエラーが出ているので、直して再度コンパイル回すとか、そんな感じで簡単に数週間は過ぎた。

当時はコンパイルが通るだけでヒーローだった。

OSS開発に初めて関わる場合、最初の段階でつまづくことがあることが多々あるかもしれないが、根気よくやるとそれで初めて見える世界というのもあるので頑張ってみてほしい。

**Comment by jflute** [comment]
関わった開発プロジェクトで実際に便利なツール、でも、とある場面で非常に弱い。
友人の教わった別の便利なツール、その「とある場面」にめっぽう強い。
でも、そのツールだけで開発するのはつらい。

二つ足し合わせたらすっごい便利になるんじゃん！？
ということで、家でちょいちょい作り始めたのがOSS活動の始まりです。

随分古いですが、Apache Torque + S2Dao から DBFlute が生まれました。
オープンソースは０から作る必要は無く、合成して新しいものを作ることもできるのです。

**Comment by koichiro** [comment]
- 最初はパッチ送っても名前おぼえてもらえない（日本人の名前はむずかしい）
- コミット権をもらうには直接会うチャンスを活かすといいかも

**Comment by satoryu** [comment]
- 本当になんでもいい。https://github.com/ruby-ldap/ruby-net-ldap/pull/165
- 鉄は熱いうちに打たないと辛い。https://github.com/activeldap/activeldap/pull/55

**Comment by cesare** [comment]
node.js に pull request してマージされたことがあります。
- きっかけは、使っていてバグを踏んだこと
  - 該当箇所のソースを眺めていたら直せそうだったので修正してみた
  - せっかくなので、テストコードを添えて pull request にしてみた
- マージ前に「送ってくれたコードの所有権はウチになるけどいい？」と同意を求められたりして興味深かった。
- 著名 OSS の Changelog とか Authors に自分の名前が載るとドヤ顔できる (知人から「これお前？」と訊かれたり)

メジャー OSS でも、貢献できそうであれば遠慮なく突撃してみると良いと思います :innocent:
